### ISSUE TITLE
Error with LinkPeaks()

### ISSUE THREAD

**Issue by yjhuang1** [stuart-lab/signac#1214]
Hello,

I'm repeatedly running into an error when running LinkPeaks() on my multi-assay (RNA + ATAC) signac object, and would appreciate any suggestions!

Brief backstory -- I'd also previously encountered an error when running RegionStats(), which I rectified by removing non-standard chromosomes as suggested by [this github post](https://github.com/timoast/signac/discussions/612). I'm including the steps leading up to the LinkPeaks() function, just in case I've introduced an error during this process / am missing something here.

> #extract counts, subset to remove peaks from non standard chromosomes and create new assay with subsetted counts
> DefaultAssay(so) <- 'peaks'
> peaks <- GetAssayData(so,slot="counts")
> 
> Peak_list=data.frame(rownames(peaks))
> Peak_list$peak_ids=Peak_list$rownames.peaks.
>   Peak_list$peak_id_chr=gsub("-.*","",Peak_list$peak_ids)
>   Peak_list_filt=Peak_list %>% dplyr::filter(peak_id_chr %in% c(paste0("chr",seq(1:22)),"chrX","chrY","chrM"))
> 
> peak_std = peaks[Peak_list_filt$peak_ids,]
> 
> so[["peak_std"]] <- CreateChromatinAssay(
>   counts = peak_std,
>   fragments = Fragments(so), 
>   min.cells = 0, min.features = -1 )
> 
> DefaultAssay(so) <- 'peak_std'
> 
> 
> #re-annotate new peak assay
> library(EnsDb.Mmusculus.v79)
> annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)
> 
> #Change levels to match chr style
> ucsc.levels <- str_replace(string=paste("chr",seqlevels(annotations),sep=""), pattern="chrMT",  replacement="chrM")
> seqlevels(annotations) <- ucsc.levels
> 
> #Add the gene information to the object
> Annotation(so) <- annotations
> 
> #Add GC content info
> library(BSgenome.Mmusculus.UCSC.mm10)
> so <- RegionStats(so, genome = BSgenome.Mmusculus.UCSC.mm10)
> 
> #Link peaks to genes
> 
> so <- LinkPeaks(
>   object = so,
>   peak.assay ="peak_std",
>   expression.assay ="SCT"
> )
> 

The LinkPeaks() function resulted in the following error:

> Testing 17426 genes and 90822 peaks
> Found gene coordinates for 14335 genes
>   |                                                  | 0 % ~calculating  Error in MatchRegionStats(meta.feature = meta.use, query.feature = pk.use[x,  : 
>   count not present in meta.features
> 

My session info:

> > sessionInfo()
> R version 4.0.2 (2020-06-22)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS:   /gpfs/fs02/apps/R/4.0.2/lib64/R/lib/libRblas.so
> LAPACK: /gpfs/fs02/apps/R/4.0.2/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats4    parallel  stats     graphics  grDevices utils     datasets 
> [8] methods   base     
> 
> other attached packages:
>  [1] BSgenome.Mmusculus.UCSC.mm10_1.4.0 BSgenome_1.56.0                   
>  [3] rtracklayer_1.48.0                 Biostrings_2.56.0                 
>  [5] XVector_0.28.0                     EnsDb.Mmusculus.v79_2.99.0        
>  [7] ensembldb_2.12.1                   AnnotationFilter_1.12.0           
>  [9] GenomicFeatures_1.40.1             AnnotationDbi_1.50.3              
> [11] Biobase_2.48.0                     GenomicRanges_1.40.0              
> [13] GenomeInfoDb_1.24.2                IRanges_2.22.2                    
> [15] S4Vectors_0.26.1                   BiocGenerics_0.34.0               
> [17] RColorBrewer_1.1-3                 pheatmap_1.0.12                   
> [19] forcats_0.5.2                      stringr_1.4.0                     
> [21] dplyr_1.0.9                        purrr_0.3.4                       
> [23] readr_2.1.2                        tidyr_1.2.0                       
> [25] tibble_3.1.8                       ggplot2_3.3.6                     
> [27] tidyverse_1.3.2                    Signac_1.6.0                      
> [29] sp_1.5-0                           SeuratObject_4.1.1                
> [31] Seurat_4.1.1                      
> 
> loaded via a namespace (and not attached):
>   [1] utf8_1.1.4                  reticulate_1.24            
>   [3] tidyselect_1.1.2            RSQLite_2.2.1              
>   [5] htmlwidgets_1.5.4           grid_4.0.2                 
>   [7] docopt_0.7.1                BiocParallel_1.22.0        
>   [9] Rtsne_0.16                  munsell_0.5.0              
>  [11] codetools_0.2-16            ica_1.0-3                  
>  [13] future_1.27.0               miniUI_0.1.1.1             
>  [15] withr_2.5.0                 spatstat.random_2.2-0      
>  [17] colorspace_1.4-1            progressr_0.10.1           
>  [19] knitr_1.30                  rstudioapi_0.14            
>  [21] ROCR_1.0-11                 tensor_1.5                 
>  [23] listenv_0.8.0               slam_0.1-50                
>  [25] GenomeInfoDbData_1.2.3      polyclip_1.10-0            
>  [27] bit64_4.0.5                 farver_2.0.3               
>  [29] parallelly_1.32.1           vctrs_0.4.1                
>  [31] generics_0.1.3              xfun_0.32                  
>  [33] biovizBase_1.36.0           BiocFileCache_1.12.1       
>  [35] lsa_0.73.3                  ggseqlogo_0.1              
>  [37] R6_2.4.1                    DelayedArray_0.14.1        
>  [39] bitops_1.0-6                spatstat.utils_2.3-1       
>  [41] cachem_1.0.6                assertthat_0.2.1           
>  [43] promises_1.2.0.1            scales_1.1.1               
>  [45] nnet_7.3-14                 googlesheets4_1.0.1        
>  [47] rgeos_0.5-9                 gtable_0.3.0               
>  [49] globals_0.16.1              goftest_1.2-3              
>  [51] rlang_1.0.5                 RcppRoll_0.3.0             
>  [53] splines_4.0.2               lazyeval_0.2.2             
>  [55] gargle_1.2.0                dichromat_2.0-0            
>  [57] checkmate_2.0.0             spatstat.geom_2.4-0        
>  [59] broom_1.0.1                 reshape2_1.4.4             
>  [61] abind_1.4-5                 modelr_0.1.9               
>  [63] backports_1.1.10            httpuv_1.6.3               
>  [65] Hmisc_4.4-1                 tools_4.0.2                
>  [67] ellipsis_0.3.2              spatstat.core_2.4-4        
>  [69] ggridges_0.5.3              Rcpp_1.0.9                 
>  [71] plyr_1.8.6                  base64enc_0.1-3            
>  [73] progress_1.2.2              zlibbioc_1.34.0            
>  [75] RCurl_1.98-1.2              prettyunits_1.1.1          
>  [77] rpart_4.1-15                openssl_1.4.3              
>  [79] deldir_1.0-6                pbapply_1.5-0              
>  [81] cowplot_1.1.1               zoo_1.8-10                 
>  [83] SummarizedExperiment_1.18.2 haven_2.5.1                
>  [85] ggrepel_0.9.1               cluster_2.1.0              
>  [87] fs_1.5.2                    magrittr_2.0.3             
>  [89] data.table_1.13.0           scattermore_0.8            
>  [91] lmtest_0.9-40               reprex_2.0.2               
>  [93] RANN_2.6.1                  googledrive_2.0.0          
>  [95] SnowballC_0.7.0             ProtGenerics_1.20.0        
>  [97] fitdistrplus_1.1-8          matrixStats_0.57.0         
>  [99] hms_1.1.2                   patchwork_1.1.2            
> [101] mime_0.9                    xtable_1.8-4               
> [103] XML_3.99-0.5                jpeg_0.1-8.1               
> [105] sparsesvd_0.2-1             readxl_1.4.1               
> [107] gridExtra_2.3               compiler_4.0.2             
> [109] biomaRt_2.44.1              KernSmooth_2.23-17         
> [111] crayon_1.5.1                htmltools_0.5.3            
> [113] mgcv_1.8-31                 later_1.3.0                
> [115] tzdb_0.3.0                  Formula_1.2-3              
> [117] lubridate_1.8.0             DBI_1.1.0                  
> [119] tweenr_2.0.1                dbplyr_2.2.1               
> [121] rappdirs_0.3.1              MASS_7.3-51.6              
> [123] Matrix_1.4-1                cli_3.3.0                  
> [125] igraph_1.3.4                pkgconfig_2.0.3            
> [127] GenomicAlignments_1.24.0    foreign_0.8-80             
> [129] plotly_4.10.0               spatstat.sparse_2.1-1      
> [131] xml2_1.3.3                  rvest_1.0.3                
> [133] VariantAnnotation_1.34.0    digest_0.6.25              
> [135] sctransform_0.3.4           RcppAnnoy_0.0.19           
> [137] spatstat.data_2.2-0         cellranger_1.1.0           
> [139] leiden_0.4.2                fastmatch_1.1-3            
> [141] htmlTable_2.1.0             uwot_0.1.14                
> [143] curl_4.3                    shiny_1.7.2                
> [145] Rsamtools_2.4.0             lifecycle_1.0.1            
> [147] nlme_3.1-148                jsonlite_1.8.0             
> [149] askpass_1.1                 viridisLite_0.3.0          
> [151] fansi_0.4.1                 pillar_1.8.1               
> [153] lattice_0.20-41             fastmap_1.1.0              
> [155] httr_1.4.2                  survival_3.1-12            
> [157] glue_1.6.2                  qlcMatrix_0.9.7            
> [159] png_0.1-7                   bit_4.0.4                  
> [161] ggforce_0.3.4               stringi_1.7.8              
> [163] blob_1.2.1                  latticeExtra_0.6-29        
> [165] memoise_2.0.1               irlba_2.3.5                
> [167] future.apply_1.9.0  

Appreciate any help with this!

**Comment by timoast** [comment]
Can you update to the latest release and see if you still have this issue?

**Comment by yjhuang1** [comment]
Thanks @timoast for the suggestion -- unfortunately, the issue persists even after updating Signac

my sessionInfo():

> R version 4.1.1 (2021-08-10)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Mojave 10.14.6
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] stringr_1.4.1                      dplyr_1.0.10                       BSgenome.Mmusculus.UCSC.mm10_1.4.3 BSgenome_1.62.0                   
>  [5] rtracklayer_1.54.0                 Biostrings_2.62.0                  XVector_0.34.0                     EnsDb.Mmusculus.v79_2.99.0        
>  [9] ensembldb_2.18.4                   AnnotationFilter_1.18.0            GenomicFeatures_1.46.5             AnnotationDbi_1.56.2              
> [13] Biobase_2.54.0                     GenomicRanges_1.46.1               GenomeInfoDb_1.30.1                IRanges_2.28.0                    
> [17] S4Vectors_0.32.4                   BiocGenerics_0.40.0                Signac_1.7.0                       sp_1.5-0                          
> [21] SeuratObject_4.1.1                 Seurat_4.1.1                       BiocManager_1.30.18               
> 
> loaded via a namespace (and not attached):
>   [1] utf8_1.2.2                  reticulate_1.26             tidyselect_1.1.2            RSQLite_2.2.17              htmlwidgets_1.5.4           grid_4.1.1                 
>   [7] docopt_0.7.1                BiocParallel_1.28.3         Rtsne_0.16                  munsell_0.5.0               codetools_0.2-18            ica_1.0-3                  
>  [13] interp_1.1-3                future_1.28.0               miniUI_0.1.1.1              withr_2.5.0                 spatstat.random_2.2-0       colorspace_2.0-3           
>  [19] progressr_0.11.0            filelock_1.0.2              knitr_1.40                  rstudioapi_0.14             ROCR_1.0-11                 tensor_1.5                 
>  [25] listenv_0.8.0               MatrixGenerics_1.6.0        slam_0.1-50                 GenomeInfoDbData_1.2.7      polyclip_1.10-0             bit64_4.0.5                
>  [31] farver_2.1.1                parallelly_1.32.1           vctrs_0.4.1                 generics_0.1.3              xfun_0.33                   biovizBase_1.42.0          
>  [37] BiocFileCache_2.2.1         lsa_0.73.3                  ggseqlogo_0.1               R6_2.5.1                    bitops_1.0-7                spatstat.utils_2.3-1       
>  [43] cachem_1.0.6                DelayedArray_0.20.0         assertthat_0.2.1            promises_1.2.0.1            BiocIO_1.4.0                scales_1.2.1               
>  [49] nnet_7.3-17                 rgeos_0.5-9                 gtable_0.3.1                globals_0.16.1              goftest_1.2-3               rlang_1.0.5                
>  [55] RcppRoll_0.3.0              splines_4.1.1               lazyeval_0.2.2              dichromat_2.0-0.1           checkmate_2.1.0             spatstat.geom_2.4-0        
>  [61] yaml_2.3.5                  reshape2_1.4.4              abind_1.4-5                 backports_1.4.1             httpuv_1.6.6                Hmisc_4.7-1                
>  [67] tools_4.1.1                 ggplot2_3.3.6               ellipsis_0.3.2              spatstat.core_2.4-4         RColorBrewer_1.1-3          ggridges_0.5.3             
>  [73] Rcpp_1.0.9                  plyr_1.8.7                  base64enc_0.1-3             progress_1.2.2              zlibbioc_1.40.0             purrr_0.3.4                
>  [79] RCurl_1.98-1.8              prettyunits_1.1.1           rpart_4.1.16                deldir_1.0-6                pbapply_1.5-0               cowplot_1.1.1              
>  [85] zoo_1.8-10                  SummarizedExperiment_1.24.0 ggrepel_0.9.1               cluster_2.1.4               magrittr_2.0.3              data.table_1.14.2          
>  [91] scattermore_0.8             lmtest_0.9-40               RANN_2.6.1                  SnowballC_0.7.0             ProtGenerics_1.26.0         fitdistrplus_1.1-8         
>  [97] matrixStats_0.62.0          hms_1.1.2                   patchwork_1.1.2             mime_0.12                   xtable_1.8-4                XML_3.99-0.10              
> [103] jpeg_0.1-9                  sparsesvd_0.2-1             gridExtra_2.3               compiler_4.1.1              biomaRt_2.50.3              tibble_3.1.8               
> [109] KernSmooth_2.23-20          crayon_1.5.1                htmltools_0.5.3             mgcv_1.8-40                 later_1.3.0                 Formula_1.2-4              
> [115] tidyr_1.2.1                 DBI_1.1.3                   tweenr_2.0.2                dbplyr_2.2.1                MASS_7.3-58.1               rappdirs_0.3.3             
> [121] Matrix_1.4-1                cli_3.4.0                   igraph_1.3.4                pkgconfig_2.0.3             GenomicAlignments_1.30.0    foreign_0.8-82             
> [127] plotly_4.10.0               spatstat.sparse_2.1-1       xml2_1.3.3                  VariantAnnotation_1.40.0    digest_0.6.29               sctransform_0.3.4          
> [133] RcppAnnoy_0.0.19            spatstat.data_2.2-0         leiden_0.4.3                fastmatch_1.1-3             htmlTable_2.4.1             uwot_0.1.14                
> [139] restfulr_0.0.15             curl_4.3.2                  shiny_1.7.2                 Rsamtools_2.10.0            rjson_0.2.21                lifecycle_1.0.2            
> [145] nlme_3.1-159                jsonlite_1.8.0              viridisLite_0.4.1           fansi_1.0.3                 pillar_1.8.1                lattice_0.20-45            
> [151] KEGGREST_1.34.0             fastmap_1.1.0               httr_1.4.4                  survival_3.4-0              glue_1.6.2                  qlcMatrix_0.9.7            
> [157] png_0.1-7                   bit_4.0.4                   ggforce_0.3.4               stringi_1.7.8               blob_1.2.3                  latticeExtra_0.6-30        
> [163] memoise_2.0.1               irlba_2.3.5                 future.apply_1.9.1

**Comment by timoast** [comment]
If you can share the object that recreates this issue I can take a look, you can email a download link to tstuart@nygenome.org

**Comment by timoast** [comment]
Thanks for sending the object, I ran the following code and wasn't able to reproduce the issue (ran without error):

```r
library(Signac)
library(Seurat)
library(BSgenome.Mmusculus.UCSC.mm10)

obj <- readRDS("~/20220915_ObjectForLinkPeaksTroubleshooting.rds")
obj <- RegionStats(obj, assay = 'peaks', BSgenome.Mmusculus.UCSC.mm10)

obj <- LinkPeaks(
  object = obj,
  peak.assay = "peaks",
  expression.assay = "SCT"
)
```

The object you sent didn't have a `peak_std` assay in it, not sure if that's the reason

**Comment by yjhuang1** [comment]
Thanks for taking a peek, @timoast ! I tried to run the code you posted and ended up with the following error:

```
obj <- RegionStats(obj, assay = 'peaks', BSgenome.Mmusculus.UCSC.mm10)
Error in .getOneSeqFromBSgenomeMultipleSequences(x, name, start, NA, width,  : 
  sequence GL456216.1 not found
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chrM, chr1_GL456210_random, chr1_GL456211_random, chr1_GL456212_random, chr1_GL456213_random, chr1_GL456221_random, chr4_GL456216_random, chr4_GL456350_random, chr4_JH584292_random, chr4_JH584293_random, chr4_JH584294_random, chr4_JH584295_random, chr5_GL456354_random, chr5_JH584296_random, chr5_JH584297_random, chr5_JH584298_random, chr5_JH584299_random, chr7_GL456219_random, chrX_GL456233_random, chrY_JH584300_random, chrY_JH584301_random, chrY_JH584302_random, chrY_JH584303_random, chrUn_GL456239, chrUn_GL456359, chrUn_GL456360, chrUn_GL456366, chrUn_GL456367, chrUn_GL456368, chrUn_GL456370, chrUn_GL456372, chrUn_GL456378, chrUn_GL456379, chrUn_GL456381, chrUn_GL456382, chrUn_GL456383, chrUn_GL456385, chrUn_GL456387, chrUn_GL456389, chrUn_GL456390, chrUn_GL456392, chrUn_GL456393, chrUn_GL456394, chrUn_GL456396, chrUn_JH584304
  - in 'y': GL456216.1, GL456233.1, JH584292.1, JH584295.1, JH584304.1
  Make  [... truncated]
```

My previous solution for this was to create the peak_std assay, using the code I included in my original post. But the code you provided seemed to work as is for you, without any need for additional work-arounds. I'm admittedly a little perplexed. I confirmed that I was running the latest releases for Seurat, Signac and BSgenome.Mmusculus.UCSC.mm10. Any ideas for why it doesn't seem to work for me?

**Comment by timoast** [comment]
If you install from the develop branch it should fix that error: `devtools::install_github("timoast/signac", ref = "develop")`
