### ISSUE TITLE
Bigwig Track

### ISSUE THREAD

**Issue by sarah-howles** [stuart-lab/signac#1234]
I'm struggling to get Bigwig track to work, advice appreciated on where I've gone wrong with my syntax much appreciated

> listbigwigs <- list("/Users/sarahhowles/Desktop/Sequencing/ccapture/bigwigs/PTEC/PTEC.mean-summary.CYP24A1.bigWig", "/Users/sarahhowles/Desktop/Sequencing/ccapture/bigwigs/HK2/HK2.mean-summary.CYP24A1.bigWig")
> names(listbigwigs) <- c("PTEC", "HK2")

> bigwig <- BigwigTrack(region = gr1,
+                        bigwig = listbigwigs,
+                        type = "coverage")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'import' for signature '"list", "missing", "missing"'

**Comment by timoast** [comment]
What version of Signac are you using?

**Comment by sarah-howles** [comment]
1.4.0, do I need to upgrade?

**Comment by timoast** [comment]
Yes, please try updating to the current release and see if you still have this issue

**Comment by sarah-howles** [comment]
Thank you - now working with 1.8.0!
