### ISSUE TITLE
Motif plotting incorrect TF motif

### ISSUE THREAD

**Issue by Abigail575** [stuart-lab/signac#1240]
Hello,

The code is working fine for me but when I run PlotMotifs() for a particular TF, it returns a plot of some other TF and I am not sure why. For example, If I run the code below it returns a plot for SPZ1:

    library(Signac)
    library(Seurat)
    library(JASPAR2020)
    library(TFBSTools)
    library(BSgenome.Mmusculus.UCSC.mm10)
    library(patchwork)
    set.seed(1234)

    # Get a list of motif position frequency matrices from the JASPAR database
    pfm <- getMatrixSet(
     x = JASPAR2020,
     opts = list(collection = "CORE", tax_group = 'vertebrates', all_versions = FALSE)
    )

    # add motif information
    pbmc <- AddMotifs(
    object = pbmc,
    genome = BSgenome.Mmusculus.UCSC.mm10,
    pfm = pfm
    )

    da_peaks <- FindMarkers(
    object = pbmc,
    ident.1 = "endocrine",
    ident.2 = "acinar",
    only.pos = TRUE,
    test.use = 'LR',
    min.pct = 0.05,
    latent.vars = 'nCount_peaks'
    )

    # get top differentially accessible peaks
    top.da.peak <- rownames(da_peaks[da_peaks$p_val < 0.005, ])
 
    # test enrichment
    enriched.motifs <- FindMotifs(
    object = pbmc,
    features = top.da.peak
    )

    MotifPlot(
    object = pbmc,
    motifs = head(rownames(enriched.motifs))
    )
    head(rownames(enriched.motifs))

    MotifPlot(
    object = pbmc,
    motifs = (enriched.motifs$motif.name == "FOXA2"))

Any suggestions much appreciated. Thanks!

**Comment by timoast** [comment]
The problem here is that `(enriched.motifs$motif.name == "FOXA2")` gives a logical vector, not the motif ID to plot. I've added some better input checking so that we will error if a character vector is not supplied. I also added the ability to plot using the motif name as well as ID, so you can just pass "FOXA2" for example

**Comment by Abigail575** [comment]
Thanks very much, it's working for me now :)
