### ISSUE TITLE
Error in RunChromVAR( ) fuction on scATAC seurat object

### ISSUE THREAD

**Issue by kanirudh12** [stuart-lab/signac#1254]
Hi, 
I'm using ChromVAR on a Seurat object to analyze scATAC-seq data where I used Signac merge(disjoin) function for a combined peaks file.

      R version 4.2.1 (2022-06-23 ucrt)
      Platform: x86_64-w64-mingw32/x64 (64-bit)
      Running under: Windows 10 x64 (build 22000)
      
      Matrix products: default
      
      locale:
      [1] LC_COLLATE=English_India.utf8  LC_CTYPE=English_India.utf8   
      [3] LC_MONETARY=English_India.utf8 LC_NUMERIC=C                  
      [5] LC_TIME=English_India.utf8    
      
      attached base packages:
      [1] stats4    stats     graphics  grDevices utils     datasets  methods   base     
      
      other attached packages:
       [1] BSgenome.Hsapiens.UCSC.hg38_1.4.4 BSgenome_1.64.0                  
       [3] rtracklayer_1.56.1                Biostrings_2.64.1                
       [5] XVector_0.36.0                    GenomicRanges_1.48.0             
       [7] GenomeInfoDb_1.32.4               IRanges_2.30.1                   
       [9] S4Vectors_0.34.0                  BiocGenerics_0.42.0              
      [11] Signac_1.7.0                      patchwork_1.1.2                  
      [13] TFBSTools_1.34.0                  JASPAR2020_0.99.10               
      [15] sp_1.5-0                          SeuratObject_4.1.1               
      [17] Seurat_4.1.1                     

After forming the Position Frequency Matrix:

    pfm <- getMatrixSet(
      x = JASPAR2020,
      opts = list(collection = "CORE", tax_group = 'vertebrates', all_versions = FALSE)
    )

I only kept the standard chromosome set present in my Seurat file:

    main.chroms <- standardChromosomes(BSgenome.Hsapiens.UCSC.hg38)
    keep.peaks <- as.logical(seqnames(granges(HPAP.motif)) %in% main.chroms)
    HPAP.motif2 <- HPAP.motif[keep.peaks, ]

Added Motifs to my database:

      HPAP.motif2 <- AddMotifs(
        object = HPAP.motif2,
        genome = BSgenome.Hsapiens.UCSC.hg38,
        pfm = pfm
      )

which returned the following warning but no errors:

      Building motif matrix
      Warning: Each of the 2 combined objects has sequence levels not in the other:
        - in 'x': chrM, chr1_GL383518v1_alt, chr1_GL383519v1_alt, chr1_GL383520v2_alt, chr1_KI270759v1_alt,
        .

But now, RunChromVAR shows error:

      HPAP.motif2 <- RunChromVAR(
        object = HPAP.motif2,
        genome = BSgenome.Hsapiens.UCSC.hg38
      )

    Error in chol.default(cov(norm_mat)) : 
    the leading minor of order 2 is not positive definite

@timoast, I am not familiar with the biocomputational analysis. I will be obliged to receive your valuable input.

**Comment by timoast** [comment]
Can you try updating to the latest Signac release and see if you still have this issue?

**Comment by Jayesh1411** [comment]
Hi @timoast, 

Thank you very much for your kind response. We tried updating Signac, the same error still persists. We are able to add the motif information from "JASPER" but we are not able to utilize ChromVar.

**Comment by Jayesh1411** [comment]
Hi @timoast,
Thank you very much for updating the function. The function now doesn't result in the same error, but there is a different error may be as a result of  higher memory usage. The error says :

` Mm.ATAC.integrated2 <- RunChromVAR(Mm.ATAC.integrated2, genome = BSgenome.Mmusculus.UCSC.mm10)

Computing GC bias per region
Warning: Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chrM, chr1_GL455991_alt, chr1_GL455992_alt, chr1_GL455993_alt, chr1_GL456005_alt, chr1_JH584315_alt, chr1_JH584320_alt, chr1_JH584321_alt, chr1_JH584322_alt, chr2_GL456024_alt, chr3_GL456006_alt, chr3_GL456007_alt, chr3_GL456008_alt, chr3_GL456042_alt, chr3_GL456044_alt, chr3_GL456045_alt, chr3_GL456048_alt, chr3_GL456049_alt, chr3_JH584323_alt, chr4_GL455994_alt, chr4_GL456009_alt, chr4_GL456010_alt, chr4_GL456053_alt, chr4_GL456064_alt, chr4_GL456075_alt, chr4_GL456076_alt, chr4_GL456077_alt, chr4_JH584268_alt, chr4_JH584269_alt, chr4_JH584324_alt, chr4_JH584325_alt, chr4_JH584326_alt, chr5_GL455995_alt, chr5_GL456011_alt, chr6_GL456012_alt, chr6_GL456025_alt, chr6_GL456026_alt, chr6_GL456054_alt, chr6_GL456065_alt, chr6_JH584264_alt, chr7_GL455989_alt, chr7_GL456013_alt, chr7_GL456014_alt, chr8_GL455996_alt, chr8_GL455997_alt, chr10_GL456015_alt, chr11_GL455998_alt, chr11_GL456016_alt, chr11_GL456060_alt, chr11_JH584265_alt, chr11_JH584316_alt, chr11_JH584317_alt, chr11_JH584327_alt, chr12_GL456017_alt, chr12_GL456068_alt, chr12_GL456074_alt, chr12_GL456078_alt, chr12_GL456349_alt, chr13_GL455990_alt, chr13_GL455999_alt, chr13_JH584305_alt, chr14_GL456019_alt, chr14_GL456020_alt, chr15_GL456000_alt, chr15_JH584270_alt, chr16_GL456001_alt, chr16_GL456028_alt, chr16_JH584306_alt, chr16_JH584307_alt, chr16_JH584310_alt, chr16_JH584311_alt, chr16_JH584312_alt, chr16_JH584313_alt, chr16_JH584314_alt, chr17_GL456002_alt, chr17_GL456021_alt, chr17_GL456022_alt, chr17_GL456069_alt, chr17_JH584266_alt, chr17_JH584267_alt, chr17_JH584308_alt, chr17_JH584309_alt, chr17_JH584328_alt, chr17_JH590470_alt, chr18_GL456070_alt, chr18_JH584318_alt, chr19_GL456079_alt, chr19_JH584319_alt, chrX_GL456003_alt, chrX_GL456004_alt, chrX_GL456031_alt, chrX_GL456032_alt, chrX_GL456033_alt, chrY_GL456071_alt, chrY_GL456072_alt, chrY_GL456073_alt, chrY_GL456080_alt, chrY_GL456081_alt, chrY_GL456082_alt, chrna_GL456050_alt, chr1_GL456210_random, chr1_GL456211_random, chr1_GL456212_random, chr1_GL456213_random, chr1_GL456221_random, chr4_GL456216_random, chr4_GL456350_random, chr4_JH584292_random, chr4_JH584293_random, chr4_JH584294_random, chr4_JH584295_random, chr5_GL456354_random, chr5_JH584296_random, chr5_JH584297_random, chr5_JH584298_random, chr5_JH584299_random, chr7_GL456219_random, chrX_GL456233_random, chrY_JH584300_random, chrY_JH584301_random, chrY_JH584302_random, chrY_JH584303_random, chrUn_GL456239, chrUn_GL456359, chrUn_GL456360, chrUn_GL456366, chrUn_GL456367, chrUn_GL456368, chrUn_GL456370, chrUn_GL456372, chrUn_GL456378, chrUn_GL456379, chrUn_GL456381, chrUn_GL456382, chrUn_GL456383, chrUn_GL456385, chrUn_GL456387, chrUn_GL456389, chrUn_GL456390, chrUn_GL456392, chrUn_GL456393, chrUn_GL456394, chrUn_GL456396, chrUn_JH584304, chr1_KV575232_fix, chr1_KV575233_fix, chr1_KV575234_fix, chr2_KV575235_fix, chr2_KV575236_fix, chr3_KQ030484_fix, chr3_KZ289064_fix, chr3_KZ289065_fix, chr3_KZ289066_fix, chr4_JH792826_fix, chr4_KQ030485_fix, chr4_KQ030486_fix, chr4_KQ030487_fix, chr4_KQ030488_fix, chr4_KQ030489_fix, chr4_KZ289067_fix, chr4_KZ289068_fix, chr4_KZ289069_fix, chr4_KZ289070_fix, chr5_JH792827_fix, chr5_KV575237_fix, chr6_KK082442_fix, chr6_KK082443_fix, chr7_JH792828_fix, chr7_KV575238_fix, chr7_KV575239_fix, chr8_KV575240_fix, chr9_KB469738_fix, chr9_KQ030490_fix, chr10_KQ030491_fix, chr10_KZ289071_fix, chr10_KZ289072_fix, chr11_KB469739_fix, chr11_KZ289076_fix, chr12_KB469740_fix, chr12_KZ289082_fix, chr14_KZ289083_fix, chr14_KZ289084_fix, chr15_KQ030492_fix, chr15_KQ030493_fix, chr15_KV575241_fix, chr15_KZ289085_fix, chr15_KZ289086_fix, chr16_KB469741_fix, chr17_KB469742_fix, chr17_KZ289087_fix, chr17_KZ289088_fix, chr17_KZ289089_fix, chr18_JH792829_fix, chr18_KZ289090_fix, chr18_KZ289091_fix, chr19_JH792830_fix, chr19_KQ030494_fix, chr19_KV575242_fix, chrX_JH792831_fix, chrX_KQ030495_fix, chrX_KQ030496_fix, chrX_KQ030497_fix, chrX_KZ289092_fix, chrX_KZ289093_fix, chrX_KZ289094_fix, chrX_KZ289095_fix, chrY_JH792832_fix, chrY_JH792833_fix, chrY_JH792834_fix, chr1_KK082441_alt, chr11_KZ289073_alt, chr11_KZ289074_alt, chr11_KZ289075_alt, chr11_KZ289077_alt, chr11_KZ289078_alt, chr11_KZ289079_alt, chr11_KZ289080_alt, chr11_KZ289081_alt
  - in 'y': GL456210.1, GL456211.1, GL456212.1, GL456216.1, GL456221.1, GL456233.1, JH584292.1, JH584295.1, JH584304.1
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).Selecting background regions
Computing deviations from background
Error in serialize(data, node$con) : error writing to connection
Error in serialize(data, node$con) : error writing to connection
`

**Comment by Jayesh1411** [comment]
@timoast, Kindly provide your valuable feedback. 
Thank you

**Comment by Jayesh1411** [comment]
Hi @timoast,
Thank you very much for updating the function. The function now doesn't result in the same error, but **there is a different error may be as a result of higher memory usage.** The error says: **Error in serialize(data, node$con) : error writing to connection**

`Mm.ATAC.integrated2 <- RunChromVAR(Mm.ATAC.integrated2, genome = BSgenome.Mmusculus.UCSC.mm10)
Computing GC bias per region
Warning: Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chrM, chr1_GL455991_alt, chr1_GL455992_alt, chr1_GL455993_alt, chr1_GL456005_alt, chr1_JH584315_alt, chr1_JH584320_alt, chr1_JH584321_alt, chr1_JH584322_alt, chr2_GL456024_alt, chr3_GL456006_alt, chr3_GL456007_alt, chr3_GL456008_alt, chr3_GL456042_alt, chr3_GL456044_alt, chr3_GL456045_alt, chr3_GL456048_alt, chr3_GL456049_alt, chr3_JH584323_alt, chr4_GL455994_alt, chr4_GL456009_alt, chr4_GL456010_alt, chr4_GL456053_alt, chr4_GL456064_alt, chr4_GL456075_alt, chr4_GL456076_alt, chr4_GL456077_alt, chr4_JH584268_alt, chr4_JH584269_alt, chr4_JH584324_alt, chr4_JH584325_alt, chr4_JH584326_alt, chr5_GL455995_alt, chr5_GL456011_alt, chr6_GL456012_alt, chr6_GL456025_alt, chr6_GL456026_alt, chr6_GL456054_alt, chr6_GL456065_alt, chr6_JH584264_alt, chr7_GL455989_alt, chr7_GL456013_alt, chr7_GL456014_alt, chr8_GL455996_alt, chr8_GL455997_alt, chr10_GL456015_alt, chr11_GL455998_alt, chr11_GL456016_alt, chr11_GL456060_alt, chr11_JH584265_alt, chr11_JH584316_alt, chr11_JH584317_alt, chr11_JH584327_alt, chr12_GL456017_alt, chr12_GL456068_alt, chr12_GL456074_alt, chr12_GL456078_alt, chr12_GL456349_alt, chr13_GL455990_alt, chr13_GL455999_alt, chr13_JH584305_alt, chr14_GL456019_alt, chr14_GL456020_alt, chr15_GL456000_alt, chr15_JH584270_alt, chr16_GL456001_alt, chr16_GL456028_alt, chr16_JH584306_alt, chr16_JH584307_alt, chr16_JH584310_alt, chr16_JH584311_alt, chr16_JH584312_alt, chr16_JH584313_alt, chr16_JH584314_alt, chr17_GL456002_alt, chr17_GL456021_alt, chr17_GL456022_alt, chr17_GL456069_alt, chr17_JH584266_alt, chr17_JH584267_alt, chr17_JH584308_alt, chr17_JH584309_alt, chr17_JH584328_alt, chr17_JH590470_alt, chr18_GL456070_alt, chr18_JH584318_alt, chr19_GL456079_alt, chr19_JH584319_alt, chrX_GL456003_alt, chrX_GL456004_alt, chrX_GL456031_alt, chrX_GL456032_alt, chrX_GL456033_alt, chrY_GL456071_alt, chrY_GL456072_alt, chrY_GL456073_alt, chrY_GL456080_alt, chrY_GL456081_alt, chrY_GL456082_alt, chrna_GL456050_alt, chr1_GL456210_random, chr1_GL456211_random, chr1_GL456212_random, chr1_GL456213_random, chr1_GL456221_random, chr4_GL456216_random, chr4_GL456350_random, chr4_JH584292_random, chr4_JH584293_random, chr4_JH584294_random, chr4_JH584295_random, chr5_GL456354_random, chr5_JH584296_random, chr5_JH584297_random, chr5_JH584298_random, chr5_JH584299_random, chr7_GL456219_random, chrX_GL456233_random, chrY_JH584300_random, chrY_JH584301_random, chrY_JH584302_random, chrY_JH584303_random, chrUn_GL456239, chrUn_GL456359, chrUn_GL456360, chrUn_GL456366, chrUn_GL456367, chrUn_GL456368, chrUn_GL456370, chrUn_GL456372, chrUn_GL456378, chrUn_GL456379, chrUn_GL456381, chrUn_GL456382, chrUn_GL456383, chrUn_GL456385, chrUn_GL456387, chrUn_GL456389, chrUn_GL456390, chrUn_GL456392, chrUn_GL456393, chrUn_GL456394, chrUn_GL456396, chrUn_JH584304, chr1_KV575232_fix, chr1_KV575233_fix, chr1_KV575234_fix, chr2_KV575235_fix, chr2_KV575236_fix, chr3_KQ030484_fix, chr3_KZ289064_fix, chr3_KZ289065_fix, chr3_KZ289066_fix, chr4_JH792826_fix, chr4_KQ030485_fix, chr4_KQ030486_fix, chr4_KQ030487_fix, chr4_KQ030488_fix, chr4_KQ030489_fix, chr4_KZ289067_fix, chr4_KZ289068_fix, chr4_KZ289069_fix, chr4_KZ289070_fix, chr5_JH792827_fix, chr5_KV575237_fix, chr6_KK082442_fix, chr6_KK082443_fix, chr7_JH792828_fix, chr7_KV575238_fix, chr7_KV575239_fix, chr8_KV575240_fix, chr9_KB469738_fix, chr9_KQ030490_fix, chr10_KQ030491_fix, chr10_KZ289071_fix, chr10_KZ289072_fix, chr11_KB469739_fix, chr11_KZ289076_fix, chr12_KB469740_fix, chr12_KZ289082_fix, chr14_KZ289083_fix, chr14_KZ289084_fix, chr15_KQ030492_fix, chr15_KQ030493_fix, chr15_KV575241_fix, chr15_KZ289085_fix, chr15_KZ289086_fix, chr16_KB469741_fix, chr17_KB469742_fix, chr17_KZ289087_fix, chr17_KZ289088_fix, chr17_KZ289089_fix, chr18_JH792829_fix, chr18_KZ289090_fix, chr18_KZ289091_fix, chr19_JH792830_fix, chr19_KQ030494_fix, chr19_KV575242_fix, chrX_JH792831_fix, chrX_KQ030495_fix, chrX_KQ030496_fix, chrX_KQ030497_fix, chrX_KZ289092_fix, chrX_KZ289093_fix, chrX_KZ289094_fix, chrX_KZ289095_fix, chrY_JH792832_fix, chrY_JH792833_fix, chrY_JH792834_fix, chr1_KK082441_alt, chr11_KZ289073_alt, chr11_KZ289074_alt, chr11_KZ289075_alt, chr11_KZ289077_alt, chr11_KZ289078_alt, chr11_KZ289079_alt, chr11_KZ289080_alt, chr11_KZ289081_alt
  - in 'y': GL456210.1, GL456211.1, GL456212.1, GL456216.1, GL456221.1, GL456233.1, JH584292.1, JH584295.1, JH584304.1
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).Selecting background regions
Computing deviations from background
Error in serialize(data, node$con) : error writing to connection
Error in serialize(data, node$con) : error writing to connection`

@timoast, Kindly provide your valuable feedback.

**Comment by Jayesh1411** [comment]
@timoast, I tried running the updated function on a better system with more memory, it has solved the issue. 
Thank you very much for such a wonderful package- "Signac" and for considering our query consideration.
