### ISSUE TITLE
Not all cells could be found in the fragments file

### ISSUE THREAD

**Issue by seigfried** [stuart-lab/signac#1259]
Hello,
I found this issue in the closed tickets but I really could not find how to fix it.

![image](https://user-images.githubusercontent.com/20457676/197733105-ba2b00e7-278f-4e9c-a9a7-7d5566d0e4b0.png)

I tried to put in tolerance=0, max_lines=NULL in the CreateChromatinAssay command.
I see some comments in the closed threads about how the format between GEX and ATAC may not match
So I tried to look at the fragments file

```
gzip -cd atac_fragments.tsv.gz | head
chr1	10043	10332	GGATAACCAGCTAATT-8	1
chr1	10048	10339	CAAGTATGTGTCCTGC-18	1
chr1	10054	10334	GATTGTTCATCCAGGT-8	1
chr1	10055	10125	AGTCGCATCGTTTCGC-6	2
chr1	10061	10126	AGGAACCAGTAAGAAC-20	1
chr1	10065	10435	AACAAAGGTGTTCCCA-8	1
chr1	10066	10126	TTGTCCGGTTTCAGGA-18	1
chr1	10067	10126	TCTTAGTTCATTGTTC-15	3
chr1	10067	10132	GCGCAAACATTAGGTT-6	8
chr1	10067	10137	ATCCTTAGTAAGGTTT-15	1
```

They look the same so I do not know how to fix this error

**Comment by timoast** [comment]
Can you search for the cell barcodes in the fragment file and confirm they're actually there?

Could you also show the full code and output of `sessionInfo()`?

**Comment by seigfried** [comment]
Dear Tim,
I have been struggling with this multiome analysis.

The atac_fragments.tsv.gz was about 2 GB in size
Then, I used the Signac FilterCells function using the barcodes from the single cell gene expression data.
The filtered atac fragments file is now only 120MB in size

1) I still get the same error.
2) Then I tried tolerance=0, same error
3) Then I tried maxlines=NULL, it gave an error saying unused arguments

Is there a way to intersect my seurat single cell object removing barcodes which dont exist in the atac_fragments file?
The Signac FilterCells, if I understand correctly, does the reverse i.e. removes atac_fragments not found in selected barcodes

**Comment by seigfried** [comment]
```
library(Signac)
library(Seurat)
library(EnsDb.Hsapiens.v86)
library(BSgenome.Hsapiens.UCSC.hg38)
library(tidyverse)

set.seed(1234)

counts <- Read10X_h5("/home/shirgaonkarn/Work/20221025_Multiome/raw_feature_bc_matrix.h5")

pbmc <- CreateSeuratObject(
  counts = counts$`Gene Expression`,
  assay = "RNA",
  project = "Multiome",
  min.cells = 3,
  min.features = 200
)

pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

pbmc <- subset(
    x = pbmc,
    subset = nFeature_RNA > 200 &
    percent.mt < 20
)

FilterCells(
  fragments = "/home/shirgaonkarn/Work/20221025_Multiome/atac_fragments.tsv.gz",
  cells = rownames(pbmc@meta.data),
  outfile = "atac_fragments_filtered.tsv.gz",
  buffer_length = 256L,
  verbose = TRUE
)

annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- "UCSC"

# Warning message in .Seqinfo.mergexy(x, y):
# "The 2 combined objects have no sequence levels in common. (Use
#  suppressWarnings() to suppress this warning.)"
# Warning message in .Seqinfo.mergexy(x, y):
# "The 2 combined objects have no sequence levels in common. (Use
#  suppressWarnings() to suppress this warning.)"
# Warning message in .Seqinfo.mergexy(x, y):
# "The 2 combined objects have no sequence levels in common. (Use
#  suppressWarnings() to suppress this warning.)"

pbmc[["ATAC"]] <- CreateChromatinAssay(
    counts = counts$Peaks,
    sep = c(":", "-"),
    fragments = "/home/shirgaonkarn/Work/20221025_Multiome/atac_fragments_filtered.tsv.gz",
    annotation = annotation,
    tolerance=0,
    max_lines=NULL
)

# Computing hash
# Error in ValidateCells(object = frags, verbose = verbose, ...): unused argument # (max_lines = NULL)
# Traceback:
# 
# 1. CreateChromatinAssay(counts = counts$Peaks, sep = c(":", "-"), 
#  .     fragments = #"/home/shirgaonkarn/Work/20221025_Multiome/atac_fragments_filtered.tsv.gz", 
# .     annotation = annotation, tolerance = 0, max_lines = NULL)
#2. CreateFragmentObject(path = fragments, cells = cells, validate.fragments = #validate.fragments, 
# .     verbose = verbose, ...)

```

**Comment by timoast** [comment]
I would suggest removing `tolerance=0`, as this makes it search for every single cell barcode in your object.

You should also remove `max_lines`, the parameter name should be `max.lines`

**Comment by seigfried** [comment]
Thanks for the inputs. It didnt work but I managed to solve the issue.
I took the peaks matrix from the h5, created a separate Seurat object and did a subset by cell barcodes i identified from the gene expression matrix
This method, however clumsy, has worked and the CreateChromatinAssay step worked like a charm

Thanks for all your help
