### ISSUE TITLE
Error in loading Signac h5Seuratobject

### ISSUE THREAD

**Issue by faniafeby13** [stuart-lab/signac#1265]
Hello,

currently, I am processing a multimodal (ScRNA- and scATAC-seq) single nuclei dataset using Signac. Because I have a problem with MACS2 installation in the Anaconda prompt on the Windows PC I'm working in, I decided to do the peak calling on a different device and saved my Signac object as h5Seuratobject.  However, when I tried to load the object with the LoadH5Seurat function, it had an error as follows:

liver_sc <- LoadH5Seurat("SeuratProject.h5Seurat")
Validating h5Seurat file
Initializing ATAC with data
Adding counts for ATAC
Adding feature-level metadata for ATAC
Adding miscellaneous information for ATAC
Error in initialize(value, ...) :
  invalid name for slot of class “Fragment”: cells__names__

Could you perhaps help me with my error case? Many thanks!

**Comment by timoast** [comment]
This looks like an issue with SeuratDisk, you can raise an issue there: https://github.com/mojaveazure/seurat-disk

In the meantime I'd suggest avoiding the use of h5seurat files
