### ISSUE TITLE
Problem with CreateChromatinAssay

### ISSUE THREAD

**Issue by Yuhanss** [stuart-lab/signac#1269]
Hi, when I tried to do the joint RNA and ATAC analysis: 10x multiomic analysis, after I ran:
 pbmc[["ATAC"]] <- CreateChromatinAssay(
  counts = counts$Peaks,
  sep = c(":", "-"),
  fragments = fragpath,
  annotation = annotation
)

I got an error message: _Computing hash, Checking for 11909 cell barcodes_

I used the same sample data (pbmc) downloaded from your website.

I couldn't figure out why this happened. Please see the console output:

<img width="636" alt="Screen Shot 2022-11-01 at 12 57 02 PM" src="https://user-images.githubusercontent.com/42656497/199326681-f6a78590-3f6b-43ab-a8ad-497685c944a0.png">
<img width="639" alt="Screen Shot 2022-11-01 at 12 57 18 PM" src="https://user-images.githubusercontent.com/42656497/199326697-fc9b8ef9-8266-4b14-9f75-72fd08725c8e.png">
<img width="633" alt="Screen Shot 2022-11-01 at 12 57 30 PM" src="https://user-images.githubusercontent.com/42656497/199326714-27a3c949-51f5-4407-a8c5-f6c926d04564.png">

I also checked the head(annotation):
GRanges object with 6 ranges and 5 metadata columns:
                  seqnames        ranges strand |           tx_id   gene_name
                     <Rle>     <IRanges>  <Rle> |     <character> <character>
  ENSE00001489430     chrX 276322-276394      + | ENST00000399012      PLCXD1
  ENSE00001536003     chrX 276324-276394      + | ENST00000484611      PLCXD1
  ENSE00002160563     chrX 276353-276394      + | ENST00000430923      PLCXD1
  ENSE00001750899     chrX 281055-281121      + | ENST00000445062      PLCXD1
  ENSE00001489388     chrX 281192-281684      + | ENST00000381657      PLCXD1
  ENSE00001719251     chrX 281194-281256      + | ENST00000429181      PLCXD1
                          gene_id   gene_biotype     type
                      <character>    <character> <factor>
  ENSE00001489430 ENSG00000182378 protein_coding     exon
  ENSE00001536003 ENSG00000182378 protein_coding     exon
  ENSE00002160563 ENSG00000182378 protein_coding     exon
  ENSE00001750899 ENSG00000182378 protein_coding     exon
  ENSE00001489388 ENSG00000182378 protein_coding     exon
  ENSE00001719251 ENSG00000182378 protein_coding     exon
  -------
  seqinfo: 25 sequences (1 circular) from GRCh38 genome

and the head(Fragments(pbmc[["ATAC"]])[[1]]):
  chrom start   end            barcode readCount
1  chr1 10066 10478 TCAAGAACAGTAATAG-1         1
2  chr1 10072 10191 AACCCGCAGGTAGCTT-1         1
3  chr1 10073 10340 CGCATATAGGTTACGT-1         2
4  chr1 10079 10192 GTAAGGTCACCCACAG-1         1
5  chr1 10079 10277 TATTCGTTCCGCCTCA-1         1
6  chr1 10079 10279 ATGAATGCATTGTCAG-1         7

Seems like the name of the chrom is consistent.

Could you please help me figure our why this error occur? Thank you so much!

Yuhan

**Comment by timoast** [comment]
What is the error message you see?

**Comment by Yuhanss** [comment]
> What is the error message you see?

Hi, 

The error message is attached below.
<img width="255" alt="Screen Shot 2022-11-01 at 2 33 25 PM" src="https://user-images.githubusercontent.com/42656497/199345978-57e23d29-ce4a-42c6-bff0-66d2050088ac.png">
Thanks

**Comment by timoast** [comment]
Ok, that's not an error message, just a progress message saying what part of the function is being run. This is normal and expected, do you see any actual error happening?

**Comment by Yuhanss** [comment]
> Ok, that's not an error message, just a progress message saying what part of the function is being run. This is normal and expected, do you see any actual error happening?

Oh I see! Thank you for your fast reply. I just ran the following codes and did not see any error messages. 

Thank you so much!
