### ISSUE TITLE
FeaturePlot and coverageplot discordant results

### ISSUE THREAD

**Issue by yamihn** [stuart-lab/signac#1273]
Hi again, I have another issue/bug and I appreciate if you can help me in some way. 
I plot on Coverageplot one region:

```
Idents(obj) <- "treatment_timepoint_cluster"
CoveragePlot(
  object = obj,
  region ="chr2-172549071-172549808",  
  ncol = 1,
  idents = c("0_KO_d8", "0_WT_d8", "4_KO_d8", "4_WT_d8"),
  peaks = TRUE,
extend.upstream = 2000,
extend.downstream = 2000,
  tile = FALSE,
  links = TRUE
)
```

![Tfap2c-Coverage](https://user-images.githubusercontent.com/109409803/200053374-a1c8b96d-6662-4311-91c8-abec10e39763.png)

It seems fine, but if I want to see that region on Featureplot:
```

FeaturePlot(obj, features = c("chr2-172549071-172549808"), pt.size =     1, order = TRUE, split.by = "treatment_timepoint", reduction= "umap", min.cutoff = 0)    
Warning message:
In FeaturePlot(obj, features = c("chr2-172549071-172549808"),  :
  All cells have the same value (0) of chr2-172549071-172549808.
```

![Rplot](https://user-images.githubusercontent.com/109409803/200053568-41ea944c-0e4a-4d85-bd9c-7fa4c22fc460.png)

Why can't see any cell with that region in WT_d8? in the coverageplot I see some peaks.
Please could you help me? Thank you!

**Comment by timoast** [comment]
How did you generate your count matrix?

**Comment by yamihn** [comment]
I subsetted my whole into three clusters and reclustered giving 0-5 new clusters. For the count matrix I used the whole peaks generated from multiome scATACseq

**Comment by timoast** [comment]
I mean where did the matrix itself come from originally

**Comment by yamihn** [comment]
Oh Im Sorry! The Matrix (both Rna and atac comes from here) 



sample <- c("KO_d6_r1", "KO_d6_r2", "KO_d8_r1", "KO_d8_r2", "WT_d6_r1", "WT_d6_r2", "WT_d8_r1", "WT_d8_r2")

for (sa in sample){
    print(sa)
inputdata.10x <- Read10X_h5(glue("/cellranger_count/{sa}/outs/filtered_feature_bc_matrix.h5"))
 
    rna_counts <- inputdata.10x$`Gene Expression`
    atac_counts <- inputdata.10x$Peaks
    
    obj <- CreateSeuratObject(counts = rna_counts)
    obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^mt-")
    print("seurat obj created")
    
# Now add in the ATAC-seq data
# we'll only use peaks in standard chromosomes
    grange.counts <- StringToGRanges(rownames(atac_counts), sep = c(":", "-"))
    grange.use <- seqnames(grange.counts) %in% standardChromosomes(grange.counts)
    atac_counts <- atac_counts[as.vector(grange.use), ]
    annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)

annotations <- renameSeqlevels(annotations, c(X="chrX", "1"="chr1", "2"="chr2", "3"="chr3", "4"="chr4", 
                               "5"="chr5", "6"="chr6", "7"="chr7", "8"="chr8", "9"="chr9", 
                               "10"="chr10", "11"="chr11", "12"="chr12", "13"="chr13", "14"="chr14",
                               "15"="chr15", "16"="chr16", "17"="chr17", "18"="chr18", "19"="chr19", 
                               "20"="chr20", "21"="chr21", "22"="chr22", Y="chrY", "MT"="chrM"))
#seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "mm10"
    
    print("annotations done")

 frag.file <- glue("/cellranger_count/{sa}/outs/atac_fragments.tsv.gz")

     print("frag.file loaded")
    chrom_assay <- CreateChromatinAssay(
    counts = atac_counts,
    sep = c(":", "-"),
    genome = 'mm10',
    fragments = frag.file,
    min.cells = 10,
    annotation = annotations
    )
    print("

Then standard workflow as filtering, scaling, integration was applied

**Comment by yamihn** [comment]
My intuition was that I cannot plot regions on FeaturePlot and make comparisons with coverages because coverage plot used fragment files, on the other hand featureplot keep regions from peak - matrix

**Comment by yamihn** [comment]
Hi @timoast , when I run AverageExpression on my object, I saw that some regions have expression 0 in some sample.
```
avg_exp_df_counts_scaled <- AverageExpression(obj, slot = "data", assays = "ATAC")

head(avg_exp_df_counts_scaled)
$ATAC
                                KO_d6      KO_d8       WT_d6       WT_d8
chr1-3123185-3124080      0.572863455 0.00000000 0.687911408  0.00000000
chr1-3191375-3192259      0.437417765 0.05462732 0.522291312  0.21944574
chr1-3253023-3253947      0.175969744 0.47336690 0.174664842  0.67635847
chr1-3324962-3325891      0.000000000 0.00000000 1.394897740  0.00000000
chr1-3359507-3360317      0.000000000 0.36658806 0.485131805  0.40292924
chr1-3360706-3361618      0.464566154 0.20628164 0.416932322  0.18914835
chr1-3395388-3396281      0.000000000 0.44726187 0.000000000  0.80423798
chr1-3399722-3400729      0.319702253 0.23032392 0.322801830  0.35267661
chr1-3447918-3448808      0.323267531 0.60474500 0.327735327  0.00000000
chr1-3449315-3450239      0.569800077 0.35738758 0.000000000  0.00000000
chr1-3549590-3550298      0.000000000 0.00000000 1.324061177  0.00000000
chr1-3560238-3561194      1.607163926 0.00000000 0.000000000  0.00000000
chr1-3610912-3611881      0.183558682 0.64108737 0.491112224  0.25022623
chr1-3636424-3637294      1.030873244 0.00000000 0.000000000  0.00000000
chr1-3647279-3648215      0.572605984 0.00000000 0.602703915  0.00000000
chr1-3648712-3649697      0.570168360 0.00000000 0.671655873  0.00000000
chr1-3670374-3671230      0.338109602 0.33855573 0.348827760  0.32185590
chr1-3671353-3672223      0.375840742 0.29976417 0.372006629  0.28641597
chr1-3681188-3682136      0.411617949 0.00000000 1.039456623  0.00000000
chr1-3912689-3913924      0.492668409 0.00000000 0.558152345  0.00000000
chr1-3953307-3954231      0.562898043 0.00000000 0.743727409  0.00000000
chr1-3955972-3956878      0.000000000 0.88078776 0.474969702  0.00000000
```

Also, when I found DARs, in min.pct2 or min.pct1 there are some 0 values:
```

ko_wt_d8_0
                                 p_val avg_log2FC pct.1 pct.2     p_val_adj           cluster
chr2-137116773-137117697  0.000000e+00 -11.378500 0.000 0.454  0.000000e+00 cluster0_KO_WT_d8
chr8-70700244-70701120    0.000000e+00  11.399219 0.381 0.000  0.000000e+00 cluster0_KO_WT_d8
chr14-87416349-87417141   0.000000e+00  11.123067 0.400 0.000  0.000000e+00 cluster0_KO_WT_d8
chr17-17625023-17625390   0.000000e+00  11.947686 0.466 0.000  0.000000e+00 cluster0_KO_WT_d8
chr7-133122786-133123595 7.091927e-313  11.600904 0.370 0.000 1.647029e-307 cluster0_KO_WT_d8
chr14-55491039-55491855  6.962498e-295 -11.248002 0.000 0.325 1.616971e-289 cluster0_KO_WT_d8
chr9-102718315-102718975 1.021954e-288 -11.399326 0.000 0.319 2.373385e-283 cluster0_KO_WT_d8
chr19-16133310-16134148  4.670746e-284 -11.483924 0.000 0.312 1.084734e-278 cluster0_KO_WT_d8
chr10-80150456-80151285  1.634972e-267  11.238123 0.327 0.000 3.797060e-262 cluster0_KO_WT_d8
chr11-87472206-87473311  5.646619e-267  11.538417 0.331 0.000 1.311371e-261 cluster0_KO_WT_d8
chr10-80160966-80161654  7.954081e-249  12.030843 0.306 0.000 1.847256e-243 cluster0_KO_WT_d8
chr1-178405462-178405848 4.819736e-246 -12.202445 0.000 0.279 1.119336e-240 cluster0_KO_WT_d8
chr14-54575350-54576263  4.659637e-242  11.315397 0.300 0.000 1.082154e-236 cluster0_KO_WT_d8
```

**Should I expect min.pct with 0?**

To find DARS I used:```

ko_wt_d8_0 <- FindMarkers(
  object = obj,
  subset.ident = "0",
  ident.1 = "KO_d8", 
  ident.2 = "WT_d8",
  min.pct = 0.1,
  test.use = 'LR', latent.vars = "nCount_ATAC", assay= "ATAC"
) %>%  ##0.2 0.25 0.1
  mutate(cluster= "cluster0_KO_WT_d8") %>% filter(p_val_adj < 0.05)  


```

**Comment by timoast** [comment]
I'm guessing that the way you constructed this object was by merging multiple separate objects together, and you didn't quantify the same peaks across all the different objects. You **absolutely** need to define a common peak set as shown in the [merge vignette](https://stuartlab.org/signac/articles/merging.html), otherwise peaks that were not quantified in one dataset will have a count of zero after merging. I think this is the reason for the difference between CoveragePlot (which uses the fragment file information) and FindMarkers differential testing (which uses the count matrix) in this issue and in https://github.com/stuart-lab/signac/issues/1264.

Please follow the steps shown in the merge vignette and that should solve these issues.

**Comment by yamihn** [comment]
Thank you so much! I'm sorry for the insistence, you have been very kind
