### ISSUE TITLE
In FoldChange function the parameter mean.fxn is ignored

### ISSUE THREAD

**Issue by Dena2021** [stuart-lab/signac#1274]
Using ChromatinAssay  the mean.fxn parameter in the functions FoldChange and FindMarkers is ignored. 

> library(Seurat)
> library(Signac)
> 
> mySeurat<-atac_small
> #in the seurat code
> mean.fxn <-  function(x) {
  return(log(x = rowMeans(x = x) + 1/10000, base = base))
 }
> 
> #my modifications
> meannolog <-  function(x) {
  return(x = rowMeans(x = x) + 1/10000)
 }

> cells_cl_0 <- WhichCells(mySeurat, expression = seurat_clusters == "0")[1:25]
> cells_cl_1 <- WhichCells(mySeurat, expression = seurat_clusters == "0")[26:50]

> my_fold<-FoldChange(mySeurat,ident.1 =cells_cl_0 , ident.2=cells_cl_1 , features='chr1-2241757-2247855',assay="peaks",slot="data")
> my_fold$avg_log2FC
[1] -1.062294

> my_fold<-FoldChange(mySeurat,ident.1 =cells_cl_0 , ident.2=cells_cl_1 , features='chr1-2241757-2247855',assay="peaks",slot="data",mean.fxn = meannolog)
> my_fold$avg_log2FC
[1] -1.062294
 sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /apps/easybd/easybuild/software/FlexiBLAS/3.0.4-GCC-11.2.0/lib64/libflexiblas.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Signac_1.7.0       sp_1.5-0           SeuratObject_4.1.0 Seurat_4.1.1      

```r
library(Seurat)
library(Signac)

mySeurat<-atac_small
#in the seurat code
mean.fxn <-  function(x) {
  return(log(x = rowMeans(x = x) + 1/10000, base = base))
}

#my modifications
meannolog <-  function(x) {
  return(x = rowMeans(x = x) + 1/10000)
}


cells_cl_0 <- WhichCells(mySeurat, expression = seurat_clusters == "0")[1:25]
cells_cl_1 <- WhichCells(mySeurat, expression = seurat_clusters == "0")[26:50]



my_fold<-FoldChange(mySeurat,ident.1 =cells_cl_0 , ident.2=cells_cl_1 , features='chr1-2241757-2247855',assay="peaks",slot="data")
my_fold$avg_log2FC

my_fold<-FoldChange(mySeurat,ident.1 =cells_cl_0 , ident.2=cells_cl_1 , features='chr1-2241757-2247855',assay="peaks",slot="data",mean.fxn = meannolog)
my_fold$avg_log2FC

```

**Comment by timoast** [comment]
This is already fixed in the latest release of Signac (1.8.0)
