### ISSUE TITLE
inquiry about Loading scATAC-seq matrices into R

### ISSUE THREAD

**Issue by jiangzh-coder** [stuart-lab/signac#1279]
Hi

i want to analyze some scATAC-seq data. And after unzip, i got 10 folders (1 patient per folder). In folder, there are 2 subfolders in whcih scRNAseq data and scATAC-seq data exist seperately. Within these 2 subfolders, there are files generated by cell ranger ( i attached 2 pic.)
How may i loading scATAC-seq matrices as well as scRNAseq data into R? Could you kindly provide some codes? 

![image](https://user-images.githubusercontent.com/68450512/201303711-cd11db24-6515-41b3-ba76-30a1a0072d63.png)

best wishes
Jiang

**Comment by timoast** [comment]
You can use the `Read10X()` function in Seurat. Please see the Seurat website for more information
