### ISSUE TITLE
Fraction of reads in promoters

### ISSUE THREAD

**Issue by Dragonmasterx87** [stuart-lab/signac#1287]
Sorry if this has been asked before Tim! Is there a way to calculate the fraction of reads in promoters? I know about the pct_reads_in_peaks but what about the percentage of peaks in promoter regions? This is for QC. Thank you!

**Comment by timoast** [comment]
You'd need to quantify counts in promoter regions (using the FeatureMatrix function), then you can run the FRiP function to find fraction of reads in promoters

**Comment by Dragonmasterx87** [comment]
Thanks bro, appreciate the quick answer! I will run it and get back to you if I have an issue. Cheers.
