### ISSUE TITLE
FindMarkers is extremely slow on peaks compared to RNA/SCT assay

### ISSUE THREAD

**Issue by alonmillet** [stuart-lab/signac#1288]
I've been processing a 10X multiome dataset of 5,000 cells, and have found that while FindMarkers usually runs in a matter of seconds on the RNA or SCT assays, it regularly takes anywhere from 10-90min to run on peaks, whether I select the ones generated by CellRanger ARC or the ones produced from MACS2 per the Signac multiome vignette. (FoldChange is lightning-fast, but obviously far less powerful.) Is it normal for FindMarkers to be this slow on peaks? 

The precise command in question is `FindMarkers(seu_filt, ident.1 = 0, ident.2 = 2, test.use = "LR", latent.vars = "atac_peak_region_fragments")`. This takes about 10min to run (comparing clusters 0 and 1 takes an estimated 90!) and the results look normal, but it feels unexpected for FindMarkers to be _that_ much slower on peaks data, even if the number of features is significantly larger.

**Comment by timoast** [comment]
The number of peaks that need to be tested can be 100x more than the number of genes tested for RNA, so this is basically scaling with the number of features tested. The LR test is quite a lot slower than the wilcoxon test (the default). You could try using Wilcoxon instead (although you won't be able to include a covariate), and the [presto](https://github.com/immunogenomics/presto) package has an extremely fast implementation.
