### ISSUE TITLE
Error in open.TabixFile(con = tabix.file) :    failed to open index file 

### ISSUE THREAD

**Issue by aliamrod** [stuart-lab/signac#1305]
I'm working with a number of sample files for an ATAC-seq analysis and have come across an error when running TSSEnrichment(seur_object, fast=FALSE), namely: 
```
Error in open.TabixFile(con = tabix.file) : 
  failed to open index file: /fragments.tsv.gz.tbi
```

Any suggestions on how to mitigate this error?

**Comment by timoast** [comment]
Closing this since I haven't heard back, feel free to reopen if you're still having issues and can answer the above question

**Comment by hassansaei** [comment]
Hello, 
I faced the same issue when running `TSSEnrichment(data_list_atac[[1]], fast = FALSE)`. Running `Fragments(data_list_atac[[1]])[[1]]@path` returned correct path '/Users/hassansaei/Desktop/CRE/biomni_Human_adult_kidney_snRNA_and_ATAC_seq/data/GSM4572187_Control1_fragments.tsv.gz'. I am running Signac version 1.14.0.

Extracting TSS positions

Finding + strand cut sites

Error in open.TabixFile(con = tabix.file): failed to open index file: /Users/hassansaei/Desktop/CRE/biomni_Human_adult_kidney_snRNA_and_ATAC_seq/data/GSM4572187_Control1_fragments.tsv.gz.tbi
Traceback:

1. CreateRegionPileupMatrix(object = object, regions = tss.positions, 
 .     assay = assay, cells = cells, verbose = verbose)
2. MultiRegionCutMatrix(regions = plus.strand, object = object, 
 .     assay = assay, cells = cells, verbose = FALSE)
3. open(con = tabix.file)
4. open.TabixFile(con = tabix.file)
5. .handleSimpleError(function (cnd) 
 . {
 .     watcher$capture_plot_and_output()
 .     cnd <- sanitize_call(cnd)
 .     watcher$push(cnd)
 .     switch(on_error, continue = invokeRestart("eval_continue"), 
 .         stop = invokeRestart("eval_stop"), error = NULL)
 . }, "failed to open index file: /Users/hassansaei/Desktop/CRE/biomni_Human_adult_kidney_snRNA_and_ATAC_seq/data/GSM4572187_Control1_fragments.tsv.gz.tbi", 
 .     base::quote(open.TabixFile(con = tabix.file)))
