### ISSUE TITLE
Unable to use CallPeaks function

### ISSUE THREAD

**Issue by Priyadarshini-Rai** [stuart-lab/signac#1306]
```r
# insert reproducible example here
```
peaks <- CallPeaks(all.agg, macs2.path = "/mnt/alvand/apps/anaconda2/bin/macs2")

sh: 1: Syntax error: Unterminated quoted string
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/tmp/RtmpoFt7cT/SeuratProject_peaks.narrowPeak': No such file or directory

**Comment by shengyongniu** [comment]
I have the same error message. I tried to open the connection to the folder by `chmod +rw  ` as mentioned here: [](https://github.com/stuart-lab/signac/issues/473)   but it doesn't work.

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'temp_peak/SeuratProject_peaks.narrowPeak': No such file or directory

**Comment by momur** [comment]
Hello Signac team, 

I have the same error. I am working on joint RNA and ATAC analysis tutorial. It is working up to Peak calling part. MACS2 is installed in my system (Mac OS). 

I have tried `chmod +rw` as mentioned before but didn't work for me. 

`peaks <- CallPeaks(pbmc, macs2.path= "/mydir/opt/anaconda3/bin/MACS2", outdir = "/mydir/joint_signac_tutorial")`

```
Error in file(file, "rt"): cannot open the connection
Warning message in file(file, "rt"):
"cannot open file '/mydir/joint_signac_tutorial/SeuratProject_peaks.narrowPeak': No such file or directory"
1. CallPeaks(pbmc, outdir = "/mydir/joint_signac_tutorial")
2. CallPeaks.Seurat(pbmc, outdir = "../joint_signac_tutorial")
3. CallPeaks(object = object[[assay]], macs2.path = macs2.path, 
 .     outdir = outdir, broad = broad, format = format, effective.genome.size = effective.genome.size, 
 .     extsize = extsize, shift = shift, additional.args = additional.args, 
 .     name = name, cleanup = cleanup, verbose = verbose, ...)
4. CallPeaks.ChromatinAssay(object = object[[assay]], macs2.path = macs2.path, 
 .     outdir = outdir, broad = broad, format = format, effective.genome.size = effective.genome.size, 
 .     extsize = extsize, shift = shift, additional.args = additional.args, 
 .     name = name, cleanup = cleanup, verbose = verbose, ...)
5. CallPeaks(object = allfragpaths, macs2.path = macs2.path, outdir = outdir, 
 .     broad = broad, format = format, effective.genome.size = effective.genome.size, 
 .     extsize = extsize, shift = shift, additional.args = additional.args, 
 .     name = name, cleanup = cleanup, verbose = verbose, ...)
6. CallPeaks.default(object = allfragpaths, macs2.path = macs2.path, 
 .     outdir = outdir, broad = broad, format = format, effective.genome.size = effective.genome.size, 
 .     extsize = extsize, shift = shift, additional.args = additional.args, 
 .     name = name, cleanup = cleanup, verbose = verbose, ...)
7. read.table(file = paste0(outdir, .Platform$file.sep, name, "_peaks.narrowPeak"), 
 .     col.names = c("chr", "start", "end", "name", "score", "strand", 
 .         "fold_change", "neg_log10pvalue_summit", "neg_log10qvalue_summit", 
 .         "relative_summit_position"))
8. file(file, "rt")
```
The output directory is exist:
`dir.exists("/mydir/joint_signac_tutorial")`
`[1] TRUE`

I have also tried without specifying output directory. `peaks <- CallPeaks(pbmc)`
The error message:`Warning message in file(file, "rt"):
"cannot open file '/var/folders/x2/zwp2s_ns3pj8740fxjbvwtnh0000gn/T//Rtmp9x3MsQ/SeuratProject_peaks.narrowPeak': No such file or directory"` 
That folder is also exist. I tried changing permission but nothing worked so far. 

Do you have any suggestions on what else should I try ? 

Thanks!

**Comment by timoast** [comment]
Closing since I haven't heard back, please reopen if you're still having issues
