### ISSUE TITLE
 Plotting a heatmap of peak-to-gene links

### ISSUE THREAD

**Issue by TerezaClarence** [stuart-lab/signac#1307]
Dear Signac developers,

I was wondering if you could give me a suggestion on how to plot heatmap of peak-to-gene links, similar to the one provided in ArchR https://www.archrproject.com/bookdown/peak2genelinkage-with-archr.html (15.3.2); function plotPeak2GeneHeatmap().

I have a seurat multimodal object (RNA+ATAC) and I have already called the links for my peak assay, is there a way to plot the heatmap?

Thank you so much.

Best regards,
Tereza

**Comment by timoast** [comment]
I would suggest getting a list of all the linked genes, then making two separate heatmaps using the DoHeatmap function, one of the peaks and one of the linked genes. For now you need to make two separate heatmaps, we have a request for a similar function here: https://github.com/stuart-lab/signac/issues/1227
