### ISSUE TITLE
Questions about finding different gene-peak links based on rna and sct (related to seurat)

### ISSUE THREAD

**Issue by HelloWorldLTY** [stuart-lab/signac#1314]
Hi all, I contact two seperated datasets to generate the overall gene-peak link result. However, I found that the results I have based on RNA in the idenfitifcation process are very differernt from the results based on SCT. For two datasets, is it ok for me to directly contact them? Thanks.

**Comment by timoast** [comment]
If you're getting very different links from log-normalized and SCT-normalized expression data, it suggests that the normalized values are quite different for each cell. The question is whether you think SCT is providing an effective normalization for you expression data, and to answer that you would need to explore the dataset a little more, and ask the SCTransform developers for further help if needed.

**Comment by HelloWorldLTY** [comment]
Thanks a lot!
