### ISSUE TITLE
I  think it is necessary to recover the geneactivity construction function for scATAC-seq data without fragement 

### ISSUE THREAD

**Issue by HelloWorldLTY** [stuart-lab/signac#1320]
Hi, I find that the current Geneactivity() function can only work for scatac-seq data with peaks and fragement information. However, plenty of current data do not provide such information, and I think it is also an important feature, mentioned by this question with no answer:
https://www.biostars.org/p/9525109/

Therefore, I think it is still necessary to keep the original seurat functin, known as 
activity.matrix <- CreateGeneActivityMatrix(peak.matrix = peaks, annotation.file = "./ad paper dataset/Homo_sapiens.GRCh37.87.gtf", 
    seq.levels = c(1:22, "X", "Y"), upstream = 2000, verbose = TRUE)
For the current work. Or do we have any similar fuctions that can help us directly construct gene activity score matrix directly from peaks matrix? Thanks a lot.

**Comment by timoast** [comment]
We do not plan to support creating a gene activity matrix from an existing scATAC-seq count matrix. I consider the fragment file as required input for running a full scATAC-seq analysis, and this is generated by most scATAC-seq analysis pipelines.

**Comment by alekseybelikov** [comment]
Lots of GEO datasets do not have fragment files! Please bring back this function! Why this unnecessary stubborness that makes your package unusable for lots of datasets?!
