### ISSUE TITLE
FindAllMarkers Best recommendations

### ISSUE THREAD

**Issue by emanuelavilla** [stuart-lab/signac#1321]
Hello! 

Recently, I got interested in using FindAllMarkers for scATAC-Seq data. However, I had difficulties to run the command with the best combination of parameters. The command I am using is

cellType.DARs <- FindAllMarkers(scATAC.data, test.use = 'LR', logfc.threshold=0.25, min.pct = 0.25, latent.vars = "peak_region_fragments")

However, this takes hours!!!! 

Can you release some recommendations on how to use it? For example, if you suggest using the parallelisation, or increase the parameters, etc.

Best,

**Comment by timoast** [comment]
You can enable parallelization (see [here](https://stuartlab.org/signac/articles/future.html)). Alternatively, you can use a different test that is faster to compute. The wilcoxon ranked sum test implemented in [presto](https://github.com/immunogenomics/presto) is extremely fast and can be run on a Seurat object, and can also give good results for scATAC-seq data.
