### ISSUE TITLE
error of FindMotifs

### ISSUE THREAD

**Issue by crystal0721** [stuart-lab/signac#1325]
hi，
   Thanks for this great packages. When we used FindMarkers function to  get different peaks. while we used FindMotifs function with default parameters got following error：
'Error in MatchRegionStats(meta.feature = mf.choose, query.feature = mf.query,  :
  GC.percent not present in meta.features. Run RegionStats to compute GC.percent for each feature.'

we want to know how to solve it, thanks for your help.

**Comment by timoast** [comment]
You need to run the `RegionStats()` function first, as explained in the error message
