### ISSUE TITLE
AddMotifs. Error in motif_mats[[x]] : subscript out of bounds

### ISSUE THREAD

**Issue by Priyadarshini-Rai** [stuart-lab/signac#1327]
PFM = getMatrixSet(x = JASPAR2020, opts = list(collection = "CORE", tax_group = 'vertebrates', all_versions = FALSE, species = "Homo sapiens"))
Seurat_Object = AddMotifs(Seurat_Object, genome = BSgenome.Hsapiens.UCSC.hg38, pfm = PFM, assay = "peaks")
Building motif matrix
dimnames(.) <- NULL translated to
dimnames(.) <- list(NULL,NULL)
dimnames(.) <- NULL translated to
dimnames(.) <- list(NULL,NULL)
dimnames(.) <- NULL translated to
dimnames(.) <- list(NULL,NULL)
Finding motif positions
Error in motif_mats[[x]] : subscript out of bounds

**Comment by timoast** [comment]
Hi, can you please give some information about your Seurat object, how did you construct it? Can you also include the output of `sessionInfo()`

**Comment by timoast** [comment]
Closing this since I haven't heard back, please reopen if you're still having issues and can provide the requested information
