### ISSUE TITLE
Label transfer using gene score calculated with ArchR

### ISSUE THREAD

**Issue by Sebdumas** [stuart-lab/signac#1328]
Hello, 

I'm trying to transfer labels from scRNA-seq data to scATAC-seq data to label different subpopulations from a unique cell type (differences between clusters are smaller as compared with differences in between cell types)
I have tried using the gene score calculated by the ArchR pipeline (peak-independent) and the gene activity from Signac (peak-dependent) and found that prediction score is improved when using gene score. 

- Gene score is depth-normalized across all genes to a constant (10,000). Would you have recommendations whether to use this score as is (depth-normalized) or to apply a log transformation (e.g. Log2(gene score +1)) before scaling and running the _FindTransferAnchors()_ function ? 
I have tested both ways and differences are very minor with a slightly better prediction using the native depth-normalized gene score values.

- Do you have plans to implement this peak-independent method for the calculation of gene activity in Signac ?

- I feel the iterative overlap peak merging procedure as proposed by ArchR is also a very interesting option that would be great to implement in Signac as well (in addition to the current reduction method merging overlapping peaks). I would be glad to get your opinions on that.

Thank you, 
Kind regards,

Sébastien

**Comment by timoast** [comment]
> Would you have recommendations whether to use this score as is (depth-normalized) or to apply a log transformation (e.g. Log2(gene score +1)) before scaling and running the FindTransferAnchors() function ?

We recommend running log normalization, as shown in the Signac vignettes

> Do you have plans to implement this peak-independent method for the calculation of gene activity in Signac ?

The gene activity method used by the `GeneActivity()` function in Signac is **peak independent**. It sums the accessibility around the gene body and promoter.

> I feel the iterative overlap peak merging procedure as proposed by ArchR is also a very interesting option that would be great to implement in Signac as well (in addition to the current reduction method merging overlapping peaks). I would be glad to get your opinions on that.

Not very familiar with what is implemented in this iterative overlap ArchR method that you're referring to. Maybe check the `AggregateTiles()` function: https://stuartlab.org/signac/reference/aggregatetiles
