### ISSUE TITLE
the error of FindIntegrationAnchors

### ISSUE THREAD

**Issue by crystal0721** [stuart-lab/signac#1334]
hello terms；
       Thanks for this great R packages for scATAC-seq.  we had one question about  scATC subcluster analyis.   We had 28 samples and when we subset lymphoid  cells for subclustering analyis，while there were less than 50 cells in some samples，and got an error  at "FindIntegrationAnchors"  function. The error is as follows:

   Error in rbind(Embeddings(object = object.1[[reduction]]), Embeddings(object = object.2[[reduction]])) :
  number of columns of matrices must match (see arg 2)
Calls: FindIntegrationAnchors ... resolve.list -> signalConditionsASAP -> signalConditions
In addition: Warning message:
No filtering performed if passing to data rather than counts
Execution halted
 

```r
# insert reproducible example here
```

**Comment by timoast** [comment]
Hi, the `FindIntegrationAnchors()` function is part of the Seurat package, please raise an issue there instead: https://github.com/satijalab/seurat
