### ISSUE TITLE
Plot raw fragment count using CoveragePlot()

### ISSUE THREAD

**Issue by jayluo2** [stuart-lab/signac#1339]
It seems that all plotting normalize raw fragment counts across celltypes. I am wondering if it is possible to plot raw fragments without any normalization (akin to loading bigwig files of fragment counts into UCSC) using CoveragePlot()?

**Comment by timoast** [comment]
We don't currently have any option to do this. Any plots that don't normalize for number of cells will have the accessibility signal mainly driven by difference in cell number between groups, so I don't think it's something that we will plan on implementing. If you are interested in this I'd suggest creating a bigwig file from the fragment file and loading into a genome browser.
