### ISSUE TITLE
Integration of multiple scATAC data

### ISSUE THREAD

**Issue by emanuelavilla** [stuart-lab/signac#1343]
Hello!

I am following the vignette of multiple scATAC-Seq (https://stuartlab.org/signac/1.2.0/articles/integration.html) to integrate 3 datasets. 
However, I can only find the overlaps between 2 objects. 

What you would suggest as best practice?

**Comment by timoast** [comment]
Hi, an example is shown in the [merge vignette](https://stuartlab.org/signac/articles/merging.html)
