### ISSUE TITLE
Additional genomic ranges to CoveragePlot() not displaying

### ISSUE THREAD

**Issue by sabrinacamp2** [stuart-lab/signac#1346]
Hi,

I am supplying additional genomic ranges to the CoveragePlot() function to visualize motifs present within a peak. When I have a CoveragePlot created for a larger genomic regions, the motif annotations within a certain peak (highlighted in grey) are not present. However, when I limit the genomic region, the annotations show up again.
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/52207849/221307667-07725731-b02a-4153-92bf-660d5c308fe5.png">

I thought this may be due to the number of motifs I am trying to plot, so I limited the motifs to only the ones within the peak. Still, the motifs only show when limiting to a smaller genomic region. 
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/52207849/221307727-57e77abe-b5bc-42e4-8be2-1e0a4c3676e2.png">

Is there any way around this?

All the best,
Sabrina

**Comment by timoast** [comment]
I think the issue is that these ranges are just too small to be displayed when viewing a larger region. They look like only a few bp, I'd suggest making them wider for visualization purposes on the larger plot (eg, run `GenomicRanges::resize`)

**Comment by WangHaoPlan** [comment]
Hi, @sabrinacamp2  .  How do I add visualize motifs in CoveragePlot() function? can you help me ?  very very thankyou ~
