### ISSUE TITLE
Error in Counting fraction of reads in peaks under Working with datasets that were not quantified using CellRanger

### ISSUE THREAD

**Issue by akhst7** [stuart-lab/signac#1350]
A second line of a Counting fraction of reads in peaks tutorial under Working with datasets that were not quantified using CellRanger, 
`pbmc$fragments <- total_fragments[[colnames](https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html)(pbmc), "frequency_count"]
` does not produce a desired output.    

To subset the total_fragments (data frame) acceding to colname of pbmc, a line should be as follows;

`total.fragments[total.fragments$CB %in% colnames(pbmc),"frequency_count" ]`

**Comment by timoast** [comment]
Thanks @akhst7, I've fixed this now on the develop branch
