### ISSUE TITLE
Custom PlotFootprint() Display Request

### ISSUE THREAD

**Issue by anderswe** [stuart-lab/signac#1353]
Hello,

Love love love Signac - thank you so much.

I'd like to change the colours in ```PlotFootprint()``` of my groups specified with ```group.by```, as if setting ```cols = ``` in other Signac/Seurat functions.

I've tried manually adding:
```+scale_color_manual(values = my_pal)```
(or, in a related vein ```+NoLegend()```)

to

```PlotFootprint(obj, features = tf, group.by = cluster_var, label = F)```

but no dice --> I'd be very grateful for any advice!

Thank you!

**Comment by timoast** [comment]
Hi, you can do this using `scale_color_manual()` but it requires some accessing due to the way the plot is composed, eg:

```r
p <- PlotFootprint(...)
p[[1]][[1]] <- p[[1]][[1]] + scale_color_manual(...)
```

**Comment by anderswe** [comment]
Amazing, thank you!
