### ISSUE TITLE
Invert coordinates and add annotations from bed file in CoveragePlot

### ISSUE THREAD

**Issue by acv21** [stuart-lab/signac#1355]
Hello,

I have three questions related to CoveragePlot:

1. I am working with a gene transcribed on the negative strand, and I would like to invert the genomic coordinates so that the TSS is on the left (as it's less confusing when only looking at the gene). Is this possible?
2. I would like to add a track of annotated genomic regions, from a bed file. I think the "ranges" function could work for this, but can it take a bed file as input? Also, how can I make sure the annotations are right next to or above/below the highlighted genomic regions, and not on the right hand-side like [here](https://github.com/stuart-lab/signac/issues/1346)?
3. Lastly, is it possible to export the coverage tracks for each cluster in bigwig format and view them on UCSC?

Many thanks for your time!

**Comment by timoast** [comment]
> I am working with a gene transcribed on the negative strand, and I would like to invert the genomic coordinates so that the TSS is on the left (as it's less confusing when only looking at the gene). Is this possible?

Not possible

> I would like to add a track of annotated genomic regions, from a bed file. I think the "ranges" function could work for this, but can it take a bed file as input?

You need to read the bed file into R first and create the `granges`object using `rtracklayer::import()`

> Also, how can I make sure the annotations are right next to or above/below the highlighted genomic regions, and not on the right hand-side like https://github.com/stuart-lab/signac/issues/1346?

The legend for the genomic ranges is shown directly to the right of the genomic ranges track

> Lastly, is it possible to export the coverage tracks for each cluster in bigwig format and view them on UCSC?

You would need to use the `SplitFragments()` function to create separate fragment files for each group of cells, and then use other tools like bedtools genomecov and bedGraphToBigWog

**Comment by timoast** [comment]
> Would you consider implementing this feature in the future? It could be quite useful.

No but if anyone wants to submit a pull request for it I'd be happy to take a look

> Thank you, this sounds like a good option! I have a question on the buffer_length argument in SplitFragments() ("Size of buffer to be read from the fragment file. This must be longer than the longest line in the file."). I am not sure I understand this: how can I find this value out from my Seurat object?

This is more of a technical thing, in 99% of cases you can keep the default value. It's only needed if you have extremely long cell barcodes, and we need to allow for the extra characters in the C++ code.
