### ISSUE TITLE
Problem with "Counting fraction of reads in peaks" `FRiP()` in section "Working with datasets that were not quantified using CellRanger"

### ISSUE THREAD

**Issue by duyson1999** [stuart-lab/signac#1356]
#### This is the code (in the Signac document) for calculate fraction of reads in peaks when output data is FROM Cellranger:
```
pbmc$pct_reads_in_peaks <- pbmc$peak_region_fragments / pbmc$passed_filters * 100
```
#### From original documentation of 10X: "peak_region_fragments" means number of fragments overlapping peaks. So I think this formula is correct, it takes n_fragments that can be mapped to peaks divided by total n_fragments (can be mapped and not mapped to peaks) of a cells
---

#### This is the code (in the document) for calculate fraction of reads in peaks when output data is NOT FROM Cellranger:
```
# not run
total_fragments <- [CountFragments](https://stuartlab.org/signac/reference/CountFragments.html)("'../vignette_data/atac_v1_pbmc_10k_fragments.tsv.gz'")
pbmc$fragments <- total_fragments[[colnames](https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html)(pbmc), "frequency_count"]

pbmc <- [FRiP](https://stuartlab.org/signac/reference/FRiP.html)(
  object = pbmc,
  assay = 'peaks',
  total.fragments = 'fragments'
)
```
#### I checked the source code of `FRiP`, it will take [sum count of a cell (in matrix)] /  pbmc$fragments * 100. And [sum count of a cell (in matrix)] is $nCount_ in seurat@meta.data (automatically calculated when run `CreateSeuratObject`
----
#### The data from pbmc$passed_filters (from cellranger meta) and pbmc$fragments (calculated) are similar, but the pbmc$peak_region_fragments and [sum count of a cell (in matrix)] are different. And that leads to the "fraction of reads in peaks" are now different between 2 ways of calculation. Can you explain it?

**Comment by duyson1999** [comment]
I found out another information. 
- According to this https://github.com/stuart-lab/signac/issues/1344#issuecomment-1445253029 . "peak_region_fragments" is the number of fragments in peaks, and is the same as "nCount_" for scATAC-seq. 
- However, I found that  "nCount_" for scATAC-seq is equal to "peak_region_cutsites" instead! 

Ps: I used `Read10X_h5(filename='data/dataset4/atac_v1_pbmc_5k_filtered_peak_bc_matrix.h5')` -> `CreateChromatinAssay` -> `CreateSeuratObject`

**Comment by timoast** [comment]
I think the reason for confusion here is quantification of cutsites vs fragments. Cellranger counts cutsites, whereas the `FeatureMatrix()` function currently counts fragments, as does the `CountFragments()` function.
