### ISSUE TITLE
AddMotifs documentation

### ISSUE THREAD

**Issue by skilpinen** [stuart-lab/signac#1361]
This maybe just me, but I just cannot find any clue from the documentation how AddMotifs map PWM or PFM into genomic sequence? Like what parameters are used for detection of each location over the genome? Perhaps I am misunderstanding now something, but ain't PFM,PWM just info on each motif, but then actual step of finding each occurrence of these motifs throughout the genome must require some thresholds (=parameters).

**Comment by timoast** [comment]
Agree we can improve the docs here.

We run motifmatchr (https://bioconductor.org/packages/motifmatchr/) with default parameters to construct a motif x peak matrix using the PFM and genome sequence.

**Comment by timoast** [comment]
Now updated on the develop branch
