### ISSUE TITLE
How to add links defined by myself to the Seurat object using Signac?

### ISSUE THREAD

**Issue by Telogen** [stuart-lab/signac#1363]
I found Signac can only add links by the Cicero co-accessible method(`ConnectionsToLinks()`) or a correlation-based method(`LinkPeaks()`). Can I add links defined by myself to the Seurat object using Signac? Thanks Tim!

**Comment by timoast** [comment]
Yes, you can assign links using the `Links()` function, see documentation here: https://stuartlab.org/signac/reference/links

The format should  be a genomic ranges object where the start and end position is the start and end of the link.

**Comment by Telogen** [comment]
Thanks! But when I tried to perform this:
```
Links(ad_atac) <- StringToGRanges(c('chr3-133725538-133736999'))
CoveragePlot(ad_atac,region = gene,links = TRUE)
```
And I got this
```
Error in abs(x = link.df$score) : 
  non-numeric argument to mathematical function
In addition: Warning message:
In .merge_two_Seqinfo_objects(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
```
Could you give me an example of the GRanges object? Many thanks!

**Comment by Telogen** [comment]
Thanks! But when I tried to perform this:
```
Links(ad_atac) <- StringToGRanges(c('chr3-133725538-133736999'))
CoveragePlot(ad_atac,region = gene,links = TRUE)
```
And I got this
```
Error in abs(x = link.df$score) : 
  non-numeric argument to mathematical function
In addition: Warning message:
In .merge_two_Seqinfo_objects(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
```
Could you give me an example of the GRanges object? Many thanks!
