### ISSUE TITLE
How to assign links to the Seurat object?

### ISSUE THREAD

**Issue by Telogen** [stuart-lab/signac#1366]
I tried to assign links using the `Links()` function following the documentation https://stuartlab.org/signac/reference/links. 
But when I tried to perform this:
```
Links(ad_atac) <- StringToGRanges(c('chr3-133725538-133736999'))
CoveragePlot(ad_atac,region = gene,links = TRUE)
```
And I got this
```
Error in abs(x = link.df$score) : 
  non-numeric argument to mathematical function
In addition: Warning message:
In .merge_two_Seqinfo_objects(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
```
Could you give me an example of the GRanges object? Many thanks!

**Comment by timoast** [comment]
If you want to display links in a coverage plot, it must have a column named `score`

**Comment by TianLab-Bioinfo** [comment]
Thanks bro!
