### ISSUE TITLE
retrieve peak coordinates associated to a gene

### ISSUE THREAD

**Issue by yamihn** [stuart-lab/signac#1371]
Hi, I would like to know how to obtain peak coordinates associated to one or more genes.

Here for example I'm able to obtain peaks included in a specific region:

```
overlap_peaks <- findOverlaps(seurat_obj, StringToGRanges("chr1-10000000-18000000"))  
EN= granges(seurat_obj)[queryHits(overlap_peaks)]
```

instead of the region **I only know the gene name**. Thank you

**Comment by timoast** [comment]
You can use the `GetLinkedPeaks()` function
