### ISSUE TITLE
How to read in barcode, matrix and peaks file ?

### ISSUE THREAD

**Issue by Nidane** [stuart-lab/signac#1377]
Sorry this might be a simple question but I have just started with scATAC-seq... 

I am trying to analyze the data here: 
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=gse158178 

in which they only provide barcodes.tsv, matrix.mtx and peaks.bed 

barcodes.tsv is just the cell barcodes not thing more 
matrix matrix is a n*m matrix with features timed cells i assumed 
peaks file is just the location of different peaks 

i wonder how should i read in them ? 
as using Read10X etc. did not work and I am not sure how to create the fragment file etc. 

Thanks!!

**Comment by timoast** [comment]
Please see the `ReadMtx()` function: https://satijalab.org/seurat/reference/readmtx

**Comment by Nidane** [comment]
it comes out as this ?
> expression_matrix <- ReadMtx(
  mtx = "C:/Users/GSE158178_RAW/NC/matrix.mtx", features = "C:/Users/GSE158178_RAW/NC/peaks.bed", 
   cells = "C:/Users/GSE158178_RAW/NC/barcodes.tsv"
)
Error in make.unique(names = feature.names) : 
  'names' must be a character vector

I assume it's bc of the peak file the locations of the peaks (instead of gene names it's numbers) ?

**Comment by Nidane** [comment]
reading in both .mtx or .mtx.gz retrieves the same error
