### ISSUE TITLE
coverage plot ranges.group.by feature

### ISSUE THREAD

**Issue by qiuxx221** [stuart-lab/signac#1385]
Hi, I am using CoveragePlot in Signac to do some visualization. For some genes, I have 6 peaks showed in the peak track with the grey color. Of the 6 peaks, 3 of them are significant DAPs. I added an extra column in the grange metadata as score, and assigned different categorical variable, and I was hoping that I can use range.by.group function to color code different peaks. However, it return with all the grey bar in the peak track. 

I don't seem to find documentation or examples how to use that feature.  

It is not a public dataset, so I have copied some information here: 
Below is the grange of the the seurat object, 
> granges(day17.subset_1_2_sub)
GRanges object with 149662 ranges and 1 metadata column:
           seqnames            ranges strand |       score
              <Rle>         <IRanges>  <Rle> | <character>
       [1]     chr1   3010600-3011487      * |      no_DAP
       [2]     chr1   3066123-3066998      * |      no_DAP
       [3]     chr1   3379124-3380018      * |      no_DAP
....
> table(day17.subset_1_2_sub@assays$peaks@ranges$score)

cluster1 cluster2   no_DAP 
    4210     4158   141294 

Here is my cmd to make the figure: 
CoveragePlot(object = day17.subset_1_2_sub,region =new_range_for_ploting,features = var, extend.upstream = 2000, extend.downstream = 2000,ncol = 1, assay = 'peaks', expression.assay = 'RNA', peaks = TRUE,ranges.group.by = day17.subset_1_2_sub@assays$peaks@ranges$score )

All the bars in the peak track is grey, and it doesn't look like ranges.group.by = day17.subset_1_2_sub@assays$peaks@ranges$score did the coloring job? 

Could you take a look and let me know if I am using this function correct? 

```r
# insert reproducible example here
```

**Comment by timoast** [comment]
The `ranges.group.by` parameter relates to the `ranges` parameter which lets you plot additional genomic ranges, aside from the genomic ranges in the object. In your case you need to set the `peaks.group.by` parameter instead.
