### ISSUE TITLE
Error: Cannot find 'peak_region_fragments' in this Seurat object

### ISSUE THREAD

**Issue by Jokendo-collab** [stuart-lab/signac#1390]
I am getting the above error when I try to run the following line of code:

`pbmc$pct_reads_in_peaks <- pbmc$peak_region_fragments / pbmc$passed_filters * 100`

How can I get around it?

**Comment by timoast** [comment]
`peak_region_fragments` is part of the metadata generated by cellranger. To have access to this in Signac you need to have processed the raw data using cellranger and load the metadata into R and add it to the Seurat object, as shown in the vignettes.

**Comment by JiaGuangshuai** [comment]
> `peak_region_fragments` is part of the metadata generated by cellranger. To have access to this in Signac you need to have processed the raw data using cellranger and load the metadata into R and add it to the Seurat object, as shown in the vignettes.

Hello,

n the vignette, https://stuartlab.org/signac/articles/pbmc_vignette, it was mentioned that 'Note that the last three metrics can be obtained from the output of CellRanger (which is stored in the object metadata), but can also be calculated for non-10x datasets using Signac (more information at the end of this document).'

However, in the end of the vignette, I did not find the method to calculate peak_region_fragments. Was it inadvertently omitted in the updated webpage or did I overlook it?

Is it still possible to do that if I could not access to the  metadata generated by cellranger?

Thank you!
