### ISSUE TITLE
Install issue R4.3.0

### ISSUE THREAD

**Issue by suzukimasako** [stuart-lab/signac#1391]
Hello Team,

After I updated to R4.3.0, I keep having a strange issue when I install/load Signac.

> library(Signac)
Error: package or namespace load failed for ‘Signac’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/XVector/libs/XVector.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/XVector/libs/XVector.so, 0x0006): Library not loaded: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libR.dylib
  Referenced from: <FEFA222E-961F-34C6-A76C-85B8D4900B95> /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/XVector/libs/XVector.so
  Reason: tried: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libR.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libR.dylib' (no such file), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file, not in dyld cache)

I uninstall and reinstall R, but I have the same issue. I don’t know why the R is looking for a file in Version 4.2. I am not sure if this is Signac specific issue since I got the same error message when I loaded ArchR. But I'd like to know if you have a solution to solve this issue.

I am attaching the code I used with the error and warning messages and sessionInfo() output.
[Seurat5_Signac_R430.txt](https://github.com/stuart-lab/signac/files/11327277/Seurat5_Signac_R430.txt)

Many thanks!

Masako

**Comment by timoast** [comment]
Generally when you update R you will need to reinstall all your R packages, otherwise you will see error messages like this. Run `setRepositories(ind=1:3); install.packages("Signac", dependencies=TRUE)`
