### ISSUE TITLE
Error in `object.list[[x]][[nn.reduction]]`: during FindIntegrationAnchors

### ISSUE THREAD

**Issue by emanuelavilla** [stuart-lab/signac#1392]
Hello!

I am trying to integrate 3 data of sc-ATAC. Each sample is the integration between 2 conditions (normal and tumoral). So, I have 6 samples in total.  
When I did the integration of the two conditions for each sample, everything was fine. However, when I try to do the same between the 3 data (already integrated for the conditions), I got an error. 
![Screenshot 2023-04-26 alle 11 11 30](https://user-images.githubusercontent.com/85672107/234528769-b01b5ff3-3b50-479e-bce0-19fd78b2bfc2.png)

I don't understand the reason why it worked for the integration of conditions, but not for the 3 data.

**Comment by timoast** [comment]
Hi, please raise an issue in the Seurat repo as this is a Seurat function: https://github.com/satijalab/seurat
