### ISSUE TITLE
Issue about TSSEnrichment()

### ISSUE THREAD

**Issue by yingluout** [stuart-lab/signac#1397]
An error occurred when I ran TSSEnrichment() function involved Signac. The error is as the following:
> scATAC_ArmD8 <- TSSEnrichment(scATAC_ArmD8, fast = FALSE)
Extracting TSS positions
Finding + strand cut sites
Finding - strand cut sites
Computing mean insertion frequency in flanking regions
Normalizing TSS score
Error in ecdf(x = object$TSS.enrichment) : 
  'x' must have 1 or more non-missing values

While the information of the object scATAC_ArmD8 is as the following:

head(annotations)
GRanges object with 6 ranges and 5 metadata columns:
                     seqnames          ranges strand |              tx_id
                        <Rle>       <IRanges>  <Rle> |        <character>
  ENSMUSE00001236884     chr3 3508030-3508332      + | ENSMUST00000108393
  ENSMUSE00000676606     chr3 3634150-3634347      + | ENSMUST00000108394
  ENSMUSE00001345708     chr3 3638059-3638230      + | ENSMUST00000108393
  ENSMUSE00001345708     chr3 3638059-3638230      + | ENSMUST00000108394
  ENSMUSE00000149313     chr3 3641223-3641317      + | ENSMUST00000108393
  ENSMUSE00000149313     chr3 3641223-3641317      + | ENSMUST00000108394
                       gene_name            gene_id   gene_biotype     type
                     <character>        <character>    <character> <factor>
  ENSMUSE00001236884       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000676606       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00001345708       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00001345708       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000149313       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000149313       Hnf4g ENSMUSG00000017688 protein_coding     exon
  -------
  seqinfo: 22 sequences (1 circular) from mm10 genome
> head(Annotation(scATAC_ArmD8))
GRanges object with 6 ranges and 5 metadata columns:
                     seqnames          ranges strand |              tx_id
                        <Rle>       <IRanges>  <Rle> |        <character>
  ENSMUSE00001236884     chr3 3508030-3508332      + | ENSMUST00000108393
  ENSMUSE00000676606     chr3 3634150-3634347      + | ENSMUST00000108394
  ENSMUSE00001345708     chr3 3638059-3638230      + | ENSMUST00000108393
  ENSMUSE00001345708     chr3 3638059-3638230      + | ENSMUST00000108394
  ENSMUSE00000149313     chr3 3641223-3641317      + | ENSMUST00000108393
  ENSMUSE00000149313     chr3 3641223-3641317      + | ENSMUST00000108394
                       gene_name            gene_id   gene_biotype     type
                     <character>        <character>    <character> <factor>
  ENSMUSE00001236884       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000676606       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00001345708       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00001345708       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000149313       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000149313       Hnf4g ENSMUSG00000017688 protein_coding     exon
  -------
  seqinfo: 22 sequences (1 circular) from mm10 genome

> head(Fragments(scATAC_ArmD8)[[1]])
  chrom   start     end            barcode readCount
1  chr1 3000139 3000302 GTCCATCTCTCTCAAT-1         1
2  chr1 3000324 3000455 TGCCTCAGTCCAAGAG-1         6
3  chr1 3000359 3000548 AGTCAACCATGTATCG-1         1
4  chr1 3000386 3000590 TTCATTGCAAACTACC-1         1
5  chr1 3000595 3001012 TTCGCGTAGAATACTG-1         2
6  chr1 3000647 3000815 GTAATCGCACTCCTCA-1         2

I just don't know what happened and how to fix the issue.

Appreciate it if somebody could provide some help.

**Comment by yingluout** [comment]
@timoast  Could you please help me figure out this issue? Thanks a lot.

**Comment by timoast** [comment]
Can you show the output of `sessionInfo()`?

**Comment by yingluout** [comment]
> Can you show the output of `sessionInfo()`?

Hi, The information is attached.

**Comment by timoast** [comment]
The error is likely due to all of the values for signal at the TSS being zero, which indicates that there could be an issue with the annotations or fragment file you are using. Please double-check that you are using the correct gene annotations, the chromosome names match in the fragment file and gene annotations, and the cell barcodes in your object are present in the fragment file
