### ISSUE TITLE
Error CallPeaks() function

### ISSUE THREAD

**Issue by valentinaOpazo** [stuart-lab/signac#1401]
Hi, im trying to call peaks on a single-cell ATAC-seq dataset following Signac tutorial [https://stuartlab.org/signac/articles/peak_calling.html](url) but using my data and the tutorial data I have the same error. 
The code is:
`pbmcpeaks <- CallPeaks(
  object = "/home/valentina/FCV/pbmc.rds", group.by = "predicted.id",
  macs2.path= "/home/valentina/miniconda3/envs/macs2-env/bin/macs2")`

The error is:
>   File "MACS2/IO/Parser.pyx", line 188, in MACS2.IO.Parser.GenericParser.build_fwtrack
>   File "MACS2/IO/Parser.pyx", line 203, in MACS2.IO.Parser.GenericParser.build_fwtrack
>   File "MACS2/IO/Parser.pyx", line 351, in MACS2.IO.Parser.BEDParser.__fw_parse_line
> IndexError: list index out of range

I search this error but i don't find any solution that works for me

**Comment by valentinaOpazo** [comment]
When I run the same code but using _**fragments.tsv.gz**_ input file it works fine, so I assume that I fail on the parameters that I use. It's necessary to modify some parameters when the input file is a SeuratObject??

**Comment by timoast** [comment]
The `object` parameter should be a Seurat object, assay, Fragment object, or path to a fragment file (see the documentation here: https://stuartlab.org/signac/reference/callpeaks).

You have supplied the path to an rds file, which is not the supported format. Please see the examples of how to run the function in the documentation and peak calling vignette.

**Comment by valentinaOpazo** [comment]
Thank you for your helpful answer. I started the signal tutorial on Windows but how macs2 don't work on Windows I save the SeuratObject and use it on Linux to run CallPeaks() function. When I load the SeuratObject in R and run CallPeaks() 
`BC5peaks <- CallPeaks(
  object = BC5_ID,
  Assay = "peaks",
  group.by = "cell_type",
  idents = "MTCs",
  macs2.path= "/home/valentina/miniconda3/envs/macs2-env/bin/macs2",
  outdir = "/home/valentina/FCV") `  
I got this error: 

> Processing file C:\Users\56966\OneDrive - Universidad de Concepción\FCV\Datasets para Valentina\BC5\BC-5JR2022\outs\fragments.tsv.gz
can't open file
Error in SplitFragments(object = object, assay = assay, group.by = group.by,  : 
  Error: cannot open requested file

The file _C:\Users\56966\OneDrive - Universidad de Concepción\FCV\Datasets para Valentina\BC5\BC-5JR2022\outs\fragments.tsv.gz_ corresponds to my Windows path. Exist a manner to change the fragments file path? or I must be run all Signac tutorial again on Linux?

**Comment by timoast** [comment]
The object stores a path to the fragment file on-disk. If you save the object and move it to a different computer you will need to also copy over the fragment file and update the path: https://stuartlab.org/signac/articles/data_structures.html#changing-the-fragment-file-path-in-an-existing-fragment-object

**Comment by valentinaOpazo** [comment]
Thank you very much for your response
