### ISSUE TITLE
Integrating multiple sn-ATAC datasets

### ISSUE THREAD

**Issue by zhang248** [stuart-lab/signac#1405]
Dear Timoast and Signac Team,

I have four datasets named Heart-1, Heart-2, Liver-1, and Liver-2, which originate from four distinct donors. Upon merging these datasets, I have observed distinct separation in the UMAP plot for each of them.

My objective now is to perform batch correction specifically for samples within the same tissue, that is, Heart-1 and Heart-2, as well as Liver-1 and Liver-2. Although I have reviewed the available vignettes and related issues on the matter, I am still uncertain about the appropriate approach to achieve this. One potential solution I have considered is using "Reference mapping" (outlined at https://stuartlab.org/signac/articles/integrate_atac.html) by using both of Heart-1 and Liver-1 as the reference. However, I would appreciate your expert advice on whether this approach is indeed suitable for my case.

Thanks!

**Comment by timoast** [comment]
Hi, it is possible to run the integration such that you will only integrate heart samples and liver samples separately, but retain the cells in a shared embedding. What you'll need to do is first run `FindIntegrationAnchors()` as shown in the vignette, and then subset the AnchorSet object to remove disallowed dataset pairs (removing anchors between heart and liver cells). Documentation for AnchorSet subset can be found here: https://satijalab.org/seurat/reference/subset.anchorset

If you have follow-up questions please open an issue on the Seurat page
