### ISSUE TITLE
LinkPeaks error

### ISSUE THREAD

**Issue by vikaskumar1019** [stuart-lab/signac#1406]
```r
# insert reproducible example here
```
Hi ... I am trying to run the LinkPeaks function and I am getting the error:

> Dat <- LinkPeaks(object = Dat, peak.assay = "peaks", expression.assay = "SCT", genes.use = c("GRIA4", "KIF21A"))
Testing 2 genes and 289758 peaks
  |                                                  | 0 % ~calculating  Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian",  : 
  argument 'x' must be numeric.

Please let me know I can fix this. Thank you!

**Comment by timoast** [comment]
Hi, please include the output of `sessionInfo()` and the full code you're running

**Comment by timoast** [comment]
Closing this since I haven't heard back. Please reopen if you're still having issues and can provide the requested information
