### ISSUE TITLE
FindTopFeatures(), minimum number of cells 

### ISSUE THREAD

**Issue by SarahOuologuem** [stuart-lab/signac#1410]
Hi, 

I have a question regarding the FindTopFeatures() function and selecting features present in a minimum number of cells.

Here: https://stuartlab.org/signac/reference/findtopfeatures, it states that when specifying an integer, this correponds to "the minimum number of cells containing the feature for the feature to be included...".
But when looking at the source code here: https://github.com/stuart-lab/signac/blob/HEAD/R/preprocessing.R, I can't see where this is happening. 
In lines 273-275, given an integer, it filters the features based on the total counts. 
To me, for these to be the features present in a minimum number of cells, the count matrix should be binarized, the rowSums() should be performed, and afterwards filtered for "hvf.info[hvf.info$count > min.cutoff, ]"

From what I've seen & tested, when specifying an integer, the features with total counts of > min.cutoff are selected and not those present in the minimum number of cells of min.cutoff. 

Please correct me if I'm wrong. 

Thanks in advance!

**Comment by timoast** [comment]
Thanks for pointing this out, it is an error in the documentation. I have now updated it to correctly state that filtering is done on counts not cells
