### ISSUE TITLE
LinkPlot link size and color

### ISSUE THREAD

**Issue by Dragonmasterx87** [stuart-lab/signac#1412]
Hi Tim, I had a small feature request, could you please share a snippet on how to adjust the linkplot so that the line widths are based on the scaled peak intensity and the y-axis a metric of co-accessibility im guessing the linkage score [Chiou et al., 2019](https://www.nature.com/articles/s41586-021-03552-w#MOESM10)):
![image](https://github.com/stuart-lab/signac/assets/39837140/ca22cf69-5be5-4bdb-a76a-373b2a4ca67d)

Also I'm sorry for the stupid question, but can you tell me exactly how to adjust the color scale, say using something like: 

```
p + scale_fill_gradient2(low = "red",
                                 mid = "white",
                                 high = "blue",
                                 na.value = "grey50")
```
                                 
I know about #405 but I don't like the `scale_colour_viridis_d()` system I have Tritanopia and all of the purple color shades look grey to me haha.....

Cheers for the help,
🐲

**Comment by timoast** [comment]
Hi @Dragonmasterx87 

>could you please share a snippet on how to adjust the linkplot so that the line widths are based on the scaled peak intensity and the y-axis a metric of co-accessibility im guessing the linkage score

This is not currently possible as we need to map the score to the linewidth aesthetic when creating the plot, it can't be added after the plot is created as far as I know. I can try to add an option for this since I do like how it looks, it can make the strongest links clearer.

> can you tell me exactly how to adjust the color scale, say using something like

To adjust the colorscale of the link plot, you need to access the correct panel from the assembled coverage plot and use the `scale_color_gradient2` function. This can take some trial and error as it will depend on what's included in the plot, but from the example in the multiome vignette:

```r
linkplot <- p1[[1]][[3]][[3]]
linkplot + scale_color_gradient2(low = "black", # whatever colors you want here
                                 mid = "white",
                                 high = "darkgreen",
                                 na.value = "grey50")

# to assign back into the assembled coverage plot
p1[[1]][[3]][[3]] <- linkplot + scale_color_gradient2(low = "black",
                                 mid = "white",
                                 high = "darkgreen",
                                 na.value = "grey50")
```

**Comment by timoast** [comment]
`scale.linewidth` parameter now added to `LinkPlot()` in the develop branch

**Comment by Dragonmasterx87** [comment]
Thank you so much bossman. Also, I haven't said this for Signac but its amazing, other than RunChromVar making my PCs sweat buckets, Thank you so much for all of your assistance and help, for seurat and of course for signac. I really appreciate it bro.

**Comment by timoast** [comment]
@Dragonmasterx87 thanks for the kind words 🙏
