### ISSUE TITLE
CoveragePlot interpretation

### ISSUE THREAD

**Issue by BBBlanca** [stuart-lab/signac#1413]
Hi Signac team,

Thank you for developing and maintaining the signac packages for us! I might have a question regarding CoveragePlot interpretation. I wanted to visualize peaks (ATAC) to genes (RNA) links in my multiome dataset, but it seems like the links shown in the figure of the output of the CoveragePlot function are peaks-to-peaks linkage (ATAC to ATAC). I have been looking for explanation for this function but haven't find my answers. Can you explain what "Links" means in the output of CoveragePlot?
![Screen Shot 2023-05-24 at 11 34 55 AM](https://github.com/stuart-lab/signac/assets/83883191/8aaefaaa-3b2f-49cf-9c00-5f7825c0a96b)
I specifically mean the bottom purple lines at the "Links" section.

Thank you!

**Comment by timoast** [comment]
Here each link goes from a peak to the TSS of a gene, it just may be hard to see when there are multiple genes

**Comment by BBBlanca** [comment]
Hi Tim, 

Thank you for your explanations! I might have a few other questions if you don't mind. According to what you said, each link goes from a peak to the TSS of a gene. Does this mean the ATAC peak is linked to the expression of the gene? And how did you specify which TSS is linked with the peak given that one gene might have multiple TSSs? The last question is that for some peaks that are shown in the "normalized signal" section, they are not shown in the "Peaks" section (no bars shown in the corresponding location). However, for some bars shown in the "Peaks" section, there is no peaks shown in the corresponding "normalized signal" location. Could you explain this inconsistency between "normalized signal" section and "Peaks" section?
Thank you!!

**Comment by timoast** [comment]
> Does this mean the ATAC peak is linked to the expression of the gene?

Yes, please see the documentation for `LinkPeaks()` for an explanation of the method

> And how did you specify which TSS is linked with the peak given that one gene might have multiple TSSs?

We choose the TSS for the longest transcript. Note that the correlation is performed between gene expression and peak accessibility, so choice of TSS is mainly for visualisation purposes

> some peaks that are shown in the "normalized signal" section, they are not shown in the "Peaks" section

Please see documentation for `CoveragePlot()`. The peaks track shows the genomic ranges of peaks used in your object, whereas the accessibility track shows fragment counts across the region plotted

**Comment by BBBlanca** [comment]
Thank you for your explanation, Tim. I guess a better way to express my TSS question is that it seems to me that multiple TSSs in gene ERBB2 (in my attached picture) are linked with peaks. Is that correct? Or do you only pick one TSS for each gene for visualization?

**Comment by timoast** [comment]
> it seems to me that multiple TSSs in gene ERBB2 (in my attached picture) are linked with peaks

No, only one. It's hard to see because the TSS of PGAP3 also overlaps the gene body of ERBB2
