### ISSUE TITLE
'problem too large' error when merge tow big sparse matrix

### ISSUE THREAD

**Issue by zhang248** [stuart-lab/signac#1421]
Hi,

I am currently working on a project that involves handling a large number of snATAC-seq samples (~2 million cells in total). During the pre-processing steps, I divided the data into two subsets based on chromosomes (1-10 and 11-22) in order to expedite the process. At this stage, I have obtained two sparse matrices for these subsets. However, when I attempted to merge them using the 'rbind' function, an error occurred with the following message:
`Error in .rbind2Csp(x, y) :
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
`
I suspect that the non-zero values in the merged sparse matrix exceed the limit of (2**31 - 1). Therefore, I would like to know how to handle such a large matrix in R or Signac.

Thanks!

**Comment by timoast** [comment]
You are probably hitting the upper limit of the `dgCMatrix`. This will be eventually solved by adding support for Seurat5-based assays that enable different types of matrices (on-disk, 64-bit, etc.) but this will take some time to develop.

Right now there's no way to construct the matrix that's larger than the `dgCMatrix` limit with Signac. My only suggestion is if you can split the cells in a way that would make sense and process them separately, or reduce the number of peaks you're using.
