### ISSUE TITLE
hclust error in IntegrateEmbeddings with a subset of anchors

### ISSUE THREAD

**Issue by zhang248** [stuart-lab/signac#1425]
Hi,

I'm currently working on integrating multiple samples using a subset of AnchorSet for each pair, as you suggested in #1405. However, I encountered the following error:
`Error in hclust(d = dist.mat) : NA/NaN/Inf in foreign function call (arg 10)
`
It seems that this error occurs due to the presence of 0 values in the similarity matrix used as input for the 'as.dist' function, as discussed in this GitHub issue: (link: https://github.com/satijalab/seurat/issues/7348). 

Is there a way to resolve this problem?

Many thanks!

EDIT:

In fact, I'm dealing with hundreds of samples from various tissues, and there are several biological replicates for each tissue. My goal is to remove batch effects only for the replicates within each tissue. However, following the method you suggested (subsetting the AnchorSet object), I would need to calculate the anchors for each pair of hundreds of samples, which would be time-consuming, memory-intensive, and most of them would be unnecessary.

I'm wondering if there are more efficient approaches to achieve my objective. For instance, can I subset all cells for each tissue, run FindIntegrationAnchors to obtain anchors, and then merge all anchor objects from all tissues to generate a consolidated anchor object that can be used as input for the IntegrateEmbeddings function? Does this approach make sense, or do you have any other suggestions?

**Comment by timoast** [comment]
> In fact, I'm dealing with hundreds of samples from various tissues, and there are several biological replicates for each tissue. My goal is to remove batch effects only for the replicates within each tissue. However, following the method you suggested (subsetting the AnchorSet object), I would need to calculate the anchors for each pair of hundreds of samples, which would be time-consuming, memory-intensive, and most of them would be unnecessary.

It sounds like reference-based integration would help here, then you only find anchors between each query and reference rather than all pairwise comparisons

> It seems that this error occurs due to the presence of 0 values in the similarity matrix used as input for the 'as.dist' function, as discussed in this GitHub issue: (link: https://github.com/satijalab/seurat/issues/7348).

Sorry but you'll need to wait for a response from Seurat
