### ISSUE TITLE
Why Signac's blacklist is different from ENCODE's blacklist?

### ISSUE THREAD

**Issue by gsx-ucas** [stuart-lab/signac#1428]
Hi, 
I found that the blacklist provided by signac is different from the blacklist of ENCODE. For example, the mouse blacklist provided by signac [blacklist_mm10](https://github.com/stuart-lab/signac/blob/master/data/blacklist_mm10.rda) contains 3435 regions, but ENCODE's blacklist [mm10.blacklist.bed](http://mitra.stanford.edu/kundaje/akundaje/release/blacklists/mm10-mouse/mm10.blacklist.bed.gz) contains only 164 regions. Why would it be different?

**Comment by timoast** [comment]
Blacklist regions are taken from [here](https://github.com/Boyle-Lab/Blacklist), as stated in the documentation for each blacklist

**Comment by gsx-ucas** [comment]
Thank you for your reply. I figured it out now. I downloaded the first version of blacklist.
