### ISSUE TITLE
scRNA-seq and scATAC-seq integration

### ISSUE THREAD

**Issue by valentinaOpazo** [stuart-lab/signac#1432]
Hello! 
I have a scRNA-seq dataset processed with Seurat and scATAC-seq dataset processed with Signal package (each sample independently processed). Both datasets were obtained from the same sample and since I am interested only in one cell population, both datasets were carefully filtered to remove other populations. Therefore I have gene expression and chromatin accessibility data of my cells of interest. I would like to know if I can assign gene expression values (from scRNA-seq) to every cell on scATAC-seq data. 
I read the paper integration of single-cell data (DOI:https://doi.org/10.1016/j.cell.2019.05.031) but I don't understand if the FindTransferAnchors and TransferData functions enable transfers of gene expression. 
Sorry if my questions in very naive, I new about single-cell analysis.

**Comment by timoast** [comment]
Hi, please see the documentation we have for this on the website: https://stuartlab.org/signac/articles/pbmc_vignette.html
