### ISSUE TITLE
heatmap or dotplot using chromvar output values 

### ISSUE THREAD

**Issue by drosop** [stuart-lab/signac#1433]
Hi, I am trying to make a similar plot. However, when I am trying to run AverageExpression() on chromvar assay of signac object, it gives me this error

combined.msobj.av <- AverageExpression(
   object = combined.msobj,
   assay = "chromvar",
   return.seurat = TRUE,
   slot = "data"
 )

Error in if (any(data.use == Inf)) { : 
  missing value where TRUE/FALSE needed

Can you please help? And chromvar output values are already z scores, so do why we need to do AverageExpression() before doheatmap or dotplot? 

Thank you

_Originally posted by @drosop in https://github.com/stuart-lab/signac/issues/264#issuecomment-1579848697_

**Comment by timoast** [comment]
Hi, `AverageExpression()` is part of the Seurat package, please raise an issue there: https://github.com/satijalab/seurat
