### ISSUE TITLE
The requested assay is not a ChromatinAssay.

### ISSUE THREAD

**Issue by elisulvaran** [stuart-lab/signac#1434]
Hi!
Firstly, thank you so much for creating this awesome tool. I am trying to run the function GeneActivity, but I keep getting the following error:
`The requested assay is not a ChromatinAssay.`
I've seen other issues for the same error, but in those cases people were trying to use a Seurat object. I am not, I actually have a ChromatinAssay object. 
`class(merged_CA)`
`[1] "ChromatinAssay"`
`attr(,"package")`
`[1] "Signac"`

I'm gonna try to add the main lines of my code for reproducibility. Pretty much, what I did was generate multiple chromatin assays from the features matrix and the fragment files for multiple samples and then merged them. After that I'm trying to run the function and it throws the error. 

```r
# generate annotation object
annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- 'UCSC'

for(directory in directories_list){
  setwd(directory)
  # obtain counts, metadata, and create ChromatinAssay object
  counts <- Read10X_h5("./filtered_feature_bc_matrix.h5")
  metadata <- read.csv(file = "./per_barcode_metrics.csv", header = TRUE, row.names = 1)
  chrom_assay <- CreateChromatinAssay(counts = counts$Peaks, sep = c(":", "-"), 
                                      genome = "hg38", fragments = "./atac_fragments.tsv.gz", 
                                      annotation = annotation)
  # add ChromatinAssay object to a list of ChromatinAssays for multiple samples
  chrom_list <- append(chrom_list, chrom_assay)
}

# merge ChromatinAssay objects
merged_CA <- merge(x = chrom_list[[1]], y = chrom_list[2:length(chrom_list)],
                          add.cell.ids = samples)

# Obtain variable features for the RNA slot of my multiomic dataset 
DefaultAssay(multiome) <- "RNA"
multiome <- FindVariableFeatures(multiome)
# Run GeneActivity function 
gene.activities <- GeneActivity(merged_CA, features = VariableFeatures(multiome))
```
`
Error in GeneActivity(merged_CA, features = VariableFeatures(multiome)) : `
`The requested assay is not a ChromatinAssay.`

Some help on this matter would be highly appreciated! Thanks!

**Comment by timoast** [comment]
This error is due to some Seurat5 changes. If you just want to run GeneActivity, I'd suggest creating a new Seurat object like this:

```r
obj <- CreateSeuratObject(counts = merged_CA)
gene.activities <- GeneActivity(obj, features = VariableFeatures(multiome))
```

If you're using Seurat5 you also need to install Signac from the seurat5 branch: `remotes::install_github("stuart-lab/signac", ref = "seurat5")`

**Comment by elisulvaran** [comment]
This solved it, thank you so much!
