### ISSUE TITLE
TSSPlot (pmbc, group.by='high.tss) + Nolegend

### ISSUE THREAD

**Issue by wenzhong4** [stuart-lab/signac#1440]
I run  Vignettes "Human PBMCs"" in R4.3.1. The TSSPlot  fails as following:

> TSSPlot(pbmc, group.by = 'high.tss') + NoLegend()
Error in TSSPlot(pbmc, group.by = "high.tss") : 
  Position enrichment matrix not present in assay

**Comment by timoast** [comment]
Please run `TSSEnrichment` with `fast=FALSE` first

**Comment by wenzhong4** [comment]
> pbmc <- TSSEnrichment(object = pbmc, fast = FALSE)
Extracting TSS positions
Finding + strand cut sites
[W::hts_idx_load3] The index file is older than the data file: atac_v1_pbmc_10k_fragments.tsv.gz.tbi
Finding - strand cut sites
[W::hts_idx_load3] The index file is older than the data file: 
atac_v1_pbmc_10k_fragments.tsv.gz.tbi
Error in `colnames<-`(`*tmp*`, value = seq_len(length.out = region.width) -  : 
  attempt to set 'colnames' on an object with less than two dimensions

**Comment by wenzhong4** [comment]
Yes, I did run TSSEnrichment((object = pbmc, fast = FALSE).

pbmc <- TSSEnrichment(object = pbmc, fast = FALSE)

Extracting TSS positions
Finding + strand cut sites
[W::hts_idx_load3] The index file is older than the data file: atac_v1_pbmc_10k_fragments.tsv.gz.tbi
Finding - strand cut sites
[W::hts_idx_load3] The index file is older than the data file:
atac_v1_pbmc_10k_fragments.tsv.gz.tbi
Error in colnames<-(*tmp*, value = seq_len(length.out = region.width) - :
attempt to set 'colnames' on an object with less than two dimensions

________________________________

**Comment by wenzhong4** [comment]
Hello
I suggest you  to rerun your code to see TSSenrichment () function?

I  used R-4.3.1.
I downloaded data and cope the code  form Signac Analyzing PBMC scATAC-seq • Signac (stuartlab.org)<https://stuartlab.org/signac/articles/pbmc_vignette.html>
[https://stuartlab.org/signac/logo.svg]<https://stuartlab.org/signac/articles/pbmc_vignette.html>
Analyzing PBMC scATAC-seq<https://stuartlab.org/signac/articles/pbmc_vignette.html>
Signac
stuartlab.org

________________________________
