### ISSUE TITLE
Create a ATAC assay without feature_bc_matrix.h5 file

### ISSUE THREAD

**Issue by rsggsr** [stuart-lab/signac#1441]
Hi, 

Thanks for this super good tool! 
I'd like to create a seurat object using some online datasets whose platform is multiome. But what I could found is they upload the atac_fragments.tsv and atac_fragments.tsv.gz.tbi files for the ATAC part, but only provide the three files including barcodes,tsv, features.tsv matrix.mtx, that means they don't provide the feature_bc_matrix.h5 file. Is it possible still using these files to associate the scATACseq (fragment) and scRNAseq data with the same cell barcode? Thanks!!

- rsggsr

**Comment by timoast** [comment]
Yes, please see the `Read10X()` function to read in the matrix. Peak calling and quantificiation of the ATAC data can be done in R using the `CallPeaks()` and `FeatureMatrix()` functions, see documentation online: https://stuartlab.org/signac/

**Comment by rsggsr** [comment]
Hi Tim,

Thanks for your quick reply, very appreciated! However, I still have some questions which might be easy for you...

I create the Seurat object using Read10X() first to read those three files in a folder. Then I called peaks using MACS2 (built in ubuntu) to have peaks data. At the same time, I used CreateFragmentObject() to generate the fragment object. But when I'd like to use FeatureMatrix() to create a fragment count matrix, I failed with a error (shown below).

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'y' in selecting a method for function 'intersect': failed to open index file: C:\Users\LINM14\Ray-NYU\scRNAseq_rawdata\HS_epidermal_stroy\GSE212450\C_PB3\atac_fragments.tsv.gz.tbi

I believed it's something wrong with that index of fragment object. But I just couldn't get it right. I am wondering if you could help advice. Thanks!

- rsggsr
