### ISSUE TITLE
Hi, I had the same problem when I was analyzing scATAC-seq data while running the CreateChromatinAssay() Thank you in advance.       seurat[["ATAC"]] <- CreateChromatinAssay( 					 counts = counts$Peaks, 					 sep = c(":", "-"), 					 fragments = fragpath, 					 annotation = annotation, 					 genome = 'hg38' ) Error in download.file(url, destfile, quiet = TRUE) :   cannot open URL 'http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz' Calls: CreateChromatinAssay ... fetch_table_from_UCSC_database -> fetch_table_from_url Execution halted

### ISSUE THREAD

**Issue by 1061047021lql-AI** [stuart-lab/signac#1443]
Hi, I had a problem when I was analyzing scATAC-seq data while running the CreateChromatinAssay()
Thank you in advance.

seurat[["ATAC"]] <- CreateChromatinAssay( counts = counts$Peaks,
                                                                      sep = c(":", "-"),
                                                                      fragments = fragpath,
                                                                      annotation = annotation,
                                                                      genome = 'hg38' )

Error in download.file(url, destfile, quiet = TRUE) :
cannot open URL 'http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz'
Calls: CreateChromatinAssay ... fetch_table_from_UCSC_database -> fetch_table_from_url 
Execution halted!

**Comment by 1061047021lql-AI** [comment]
Hi, I had the same problem when I was analyzing scATAC-seq data while running the CreateChromatinAssay() 
Thank you in advance.       
seurat[["ATAC"]] <- CreateChromatinAssay( counts = counts$Peaks, 					 
                                                                       sep = c(":", "-"), 					 
                                                                       fragments = fragpath, 					 
                                                                       annotation = annotation, 					 
                                                                       genome = 'hg38' ) 

Error in download.file(url, destfile, quiet = TRUE) :   
cannot open URL 'http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz' 
Calls: CreateChromatinAssay ... fetch_table_from_UCSC_database -> fetch_table_from_url Execution halted

**Comment by timoast** [comment]
Remove the `genome` parameter

Please search past issues: https://github.com/stuart-lab/signac/issues/603

Please write your issue in the body of the text and not as the title
