### ISSUE TITLE
Make the TSS Enrichment calculation window user-adjustable.

### ISSUE THREAD

**Issue by twmccart** [stuart-lab/signac#1444]
The [ENCODE bulk ATAC analysis pipeline](https://www.encodeproject.org/data-standards/terms/) calculates TSS enrichment score by normalizing against 100bp flanking regions that are 2000bp downstream and upstream of the annotated TSSs. The current hard-coded behavior of Signac is to normalize against 100bp flanking regions that are only 1000bp downstream and upstream of TSSs.

**Comment by twmccart** [comment]
Fixed by PR 1402

**Comment by timoast** [comment]
Sorry for the delay, I did some testing and have merged the PR now
