### ISSUE TITLE
cannot create CreateChromatinAssay

### ISSUE THREAD

**Issue by Yijia-Jiang** [stuart-lab/signac#1450]
Hello, I am unable to create CreateChromatinAssay object, as an error message shows below:

Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  'NA' indices are not (yet?) supported for sparse Matrices

Can you help with this? Thank you very much,

**Comment by timoast** [comment]
Please include the full code that you're running and the output of `sessionInfo()`

**Comment by timoast** [comment]
Closing this since I haven't heard back, please reopen if you're still having issues and can provide the requested information
