### ISSUE TITLE
No fragment file present when extracting gene activity

### ISSUE THREAD

**Issue by akkku0918** [stuart-lab/signac#1456]
Hello,
I am new to bioinformatics and in R and from wet lab background. I am analyzing three single cell multiomics (RNA + ATAC) datasets from 10x genomics.  When I merge the three datasets, the fragment files for each datasets were present. But after integrating with harmony when I try to  extract gene activity the error comes as no fragment file present. Here I am attaching full code. 

##Create seurat object reading .h5 file and meta file
```{r}
counts_APL1 <- Read10X_h5(filename = "path/to/filtered_feature_bc_matrix.h5")

meta_APL1 <- read.csv(
file = 'path/to/per_barcode_metrics.csv',
header = TRUE,
row.names = 1)
```

```{r}
 chrom_assay <- CreateChromatinAssay(
  counts = counts_APL1$Peaks,
  sep = c(":", "-"),
  genome = 'hg38',
  fragments = 'path/to/atac_fragments.tsv.gz',
  min.cells = 3,
  min.features = 200
)
```
```{r}
data_APL1 <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = meta_APL1
)
```
```{r}
data_APL1[[]]
```
```{r}
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotations) <- 'UCSC'
Annotation(data_APL1) <- annotations
```

```{r}
data_APL21<- NucleosomeSignal(object = data_APL1) #fragment ratio 147-294: <147
data_APL2 <- TSSEnrichment(object = data_APL1, fast = FALSE)
```
##Here I get the error. I cant find any blacklist_region_fragments nor the pct_reads_in_peaks. Even the peak_region_fragments is placed in metadata in name of atac_peak_region_fragments. 
## So proceeded without these two parameters in QC
```{r}
#data_APL1$blacklist_ratio <- data_APL1$blacklist_region_fragments / data$peak_region_fragments
#data_APL1[[]]
#data$pct_reads_in_peaks <- data$peak_region_fragments / data$passed_filters * 100 
```

```{r}
VlnPlot(
  object = data_APL1,
  features = c('nCount_peaks', 
               'nucleosome_signal', 'TSS.enrichment'),
  pt.size = 0.1,
  ncol = 5
)
```

```{r}
data_APL1 <- subset(
    x = data_APL1,
    subset = atac_peak_region_fragments > 1000 &
           atac_peak_region_fragments < 100000 &
           nucleosome_signal < 4 &
           TSS.enrichment > 1)
```
##Created 3 SeuratObjects from 3 three samples

#add sample information for merging samples
```{r}
Control$dataset <- "Control"
APL1$dataset <- "APL1"
APL2$dataset <- "APL2"
```

```{r}
merged_atac <- merge(Control, y = c(APL1, APL2),  add.cell.ids = c("Control", "APL1", "APL2"), project = "Integrated_ATAC" )
```

```{r}
merged_atac@meta.data
```

```{r}
merged_atac <- FindTopFeatures(merged_atac, min.cutoff = 'q0')
merged_atac <- RunTFIDF(merged_atac)
merged_atac <- RunSVD(merged_atac)
merged_atac
```
#An object of class Seurat 
181982 features across 3848 samples within 1 assay 
Active assay: peaks (181982 features, 181982 variable features)
 1 dimensional reduction calculated: lsi

```{r}
merged_atac <- RunUMAP(object = merged_atac, reduction = 'lsi', dims = 2:30)
merged_atac <- FindNeighbors(object = merged_atac, reduction = 'lsi', dims = 2:30)
```

```{r}
merged_atac <- FindClusters(object = merged_atac, verbose = FALSE, algorithm = 3, resolution = .4)
DimPlot(object = merged_atac, label = TRUE) + NoLegend()
DimPlot(object = merged_atac, label = TRUE, group.by = "dataset") + NoLegend()
```
```{r}
#Batch correction using Harmony
integrated_atac_harmony <- RunHarmony(object = merged_atac, group.by.vars = 'dataset', reduction = 'lsi', assay.use = 'peaks', project.dim = FALSE)
integrated_atac_harmony <- RunUMAP(integrated_atac_harmony, dims = 2:10, reduction = 'harmony')
DimPlot(integrated_atac_harmony, group.by = 'dataset', pt.size = 0.5)
```

```{r}
# Do UMAP and clustering using ** Harmony embeddings instead of PCA **
integrated_atac_harmony <- integrated_atac_harmony %>%
  RunUMAP(reduction = 'harmony', dims = 2:10) %>%
  FindNeighbors(reduction = "harmony", dims = 2:10) %>%
  FindClusters(resolution = 0.3)

# visualize 
DimPlot(integrated_atac_harmony, reduction = 'umap', group.by = 'dataset')
DimPlot(integrated_atac_harmony, reduction = 'umap')
```

```{r}
gene.activities <- GeneActivity(integrated_atac_harmony)
```
##Here I get the error
##Error in GeneActivity(integrated_atac_harmony) :
    No fragment information found for requested assay

Although the fragment files were present when I created SeuratObject. Could you please help me to find this issue and better suggestion to improve the pipeline for further integration with merged scRNA dataset.

**Comment by timoast** [comment]
How did you create the `Control`, `AP1`, and `AP2` objects? Please also show the output of `sessionInfo()`

**Comment by akkku0918** [comment]
Sorry my bad.
I forgot to mention that Control, APL1, APL2  are data_Control, data_APL1, data_APL2 respectively created after QC filter subset. They were saved and read as Control, APL1, APL2. 


Please find the sessioninfo()
> session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.0 (2023-04-21 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_India.utf8
 ctype    English_India.utf8
 tz       Asia/Calcutta
 date     2023-07-27
 rstudio  2023.03.0+386 Cherry Blossom (desktop)
 pandoc   2.19.2 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package                     * version   date (UTC) lib source
 abind                         1.4-5     2016-07-21 [1] CRAN (R 4.3.0)
 AnnotationDbi               * 1.62.2    2023-07-02 [1] Bioconductor
 AnnotationFilter            * 1.24.0    2023-04-25 [1] Bioconductor
 backports                     1.4.1     2021-12-13 [1] CRAN (R 4.3.0)
 base64enc                     0.1-3     2015-07-28 [1] CRAN (R 4.3.0)
 Biobase                     * 2.60.0    2023-04-25 [1] Bioconductor
 BiocFileCache                 2.8.0     2023-04-25 [1] Bioconductor
 BiocGenerics                * 0.46.0    2023-04-25 [1] Bioconductor
 BiocIO                        1.10.0    2023-04-25 [1] Bioconductor
 BiocManager                 * 1.30.21   2023-06-10 [1] CRAN (R 4.3.1)
 BiocParallel                  1.34.2    2023-05-22 [1] Bioconductor
 biomaRt                       2.56.1    2023-06-11 [1] Bioconductor
 Biostrings                  * 2.68.1    2023-05-16 [1] Bioconductor
 biovizBase                  * 1.48.0    2023-04-25 [1] Bioconductor
 bit                           4.0.5     2022-11-15 [1] CRAN (R 4.3.1)
 bit64                         4.0.5     2020-08-30 [1] CRAN (R 4.3.1)
 bitops                        1.0-7     2021-04-24 [1] CRAN (R 4.3.0)
 blob                          1.2.4     2023-03-17 [1] CRAN (R 4.3.1)
 broom                         1.0.5     2023-06-09 [1] CRAN (R 4.3.1)
 BSgenome                    * 1.68.0    2023-04-25 [1] Bioconductor
 BSgenome.Hsapiens.UCSC.hg38 * 1.4.5     2023-07-19 [1] Bioconductor
 cachem                        1.0.8     2023-05-01 [1] CRAN (R 4.3.0)
 car                           3.1-2     2023-03-30 [1] CRAN (R 4.3.1)
 carData                       3.0-5     2022-01-06 [1] CRAN (R 4.3.1)
 checkmate                     2.2.0     2023-04-27 [1] CRAN (R 4.3.1)
 cli                           3.6.1     2023-03-23 [1] CRAN (R 4.3.0)
 cluster                       2.1.4     2022-08-22 [2] CRAN (R 4.3.0)
 codetools                     0.2-19    2023-02-01 [2] CRAN (R 4.3.0)
 colorspace                    2.1-0     2023-01-23 [1] CRAN (R 4.3.0)
 cowplot                     * 1.1.1     2020-12-30 [1] CRAN (R 4.3.0)
 crayon                        1.5.2     2022-09-29 [1] CRAN (R 4.3.0)
 curl                          5.0.1     2023-06-07 [1] CRAN (R 4.3.0)
 data.table                    1.14.8    2023-02-17 [1] CRAN (R 4.3.0)
 DBI                           1.1.3     2022-06-18 [1] CRAN (R 4.3.1)
 dbplyr                        2.3.3     2023-07-07 [1] CRAN (R 4.3.1)
 DelayedArray                  0.26.6    2023-07-02 [1] Bioconductor
 deldir                        1.0-9     2023-05-17 [1] CRAN (R 4.3.0)
 dichromat                     2.0-0.1   2022-05-02 [1] CRAN (R 4.3.0)
 digest                        0.6.33    2023-07-07 [1] CRAN (R 4.3.1)
 docopt                        0.7.1     2020-06-24 [1] CRAN (R 4.3.1)
 dplyr                       * 1.1.2     2023-04-20 [1] CRAN (R 4.3.0)
 ellipsis                      0.3.2     2021-04-29 [1] CRAN (R 4.3.0)
 EnsDb.Hsapiens.v86          * 2.99.0    2023-07-15 [1] Bioconductor
 ensembldb                   * 2.24.0    2023-04-25 [1] Bioconductor
 evaluate                      0.21      2023-05-05 [1] CRAN (R 4.3.0)
 fansi                         1.0.4     2023-01-22 [1] CRAN (R 4.3.0)
 farver                        2.1.1     2022-07-06 [1] CRAN (R 4.3.0)
 fastmap                       1.1.1     2023-02-24 [1] CRAN (R 4.3.0)
 fastmatch                     1.1-3     2021-07-23 [1] CRAN (R 4.3.0)
 filelock                      1.0.2     2018-10-05 [1] CRAN (R 4.3.1)
 fitdistrplus                  1.1-11    2023-04-25 [1] CRAN (R 4.3.0)
 forcats                     * 1.0.0     2023-01-29 [1] CRAN (R 4.3.1)
 foreign                       0.8-84    2022-12-06 [2] CRAN (R 4.3.0)
 Formula                       1.2-5     2023-02-24 [1] CRAN (R 4.3.0)
 future                        1.33.0    2023-07-01 [1] CRAN (R 4.3.1)
 future.apply                  1.11.0    2023-05-21 [1] CRAN (R 4.3.0)
 generics                      0.1.3     2022-07-05 [1] CRAN (R 4.3.0)
 GenomeInfoDb                * 1.36.1    2023-06-21 [1] Bioconductor
 GenomeInfoDbData              1.2.10    2023-07-15 [1] Bioconductor
 GenomicAlignments             1.36.0    2023-04-25 [1] Bioconductor
 GenomicFeatures             * 1.52.1    2023-06-22 [1] Bioconductor
 GenomicRanges               * 1.52.0    2023-04-25 [1] Bioconductor
 ggforce                     * 0.4.1     2022-10-04 [1] CRAN (R 4.3.1)
 ggplot2                     * 3.4.2     2023-04-03 [1] CRAN (R 4.3.0)
 ggpubr                      * 0.6.0     2023-02-10 [1] CRAN (R 4.3.1)
 ggrepel                       0.9.3     2023-02-03 [1] CRAN (R 4.3.0)
 ggridges                      0.5.4     2022-09-26 [1] CRAN (R 4.3.0)
 ggsci                         3.0.0     2023-03-08 [1] CRAN (R 4.3.1)
 ggsignif                      0.6.4     2022-10-13 [1] CRAN (R 4.3.1)
 globals                       0.16.2    2022-11-21 [1] CRAN (R 4.3.0)
 glue                          1.6.2     2022-02-24 [1] CRAN (R 4.3.0)
 goftest                       1.2-3     2021-10-07 [1] CRAN (R 4.3.0)
 gridExtra                     2.3       2017-09-09 [1] CRAN (R 4.3.0)
 gtable                        0.3.3     2023-03-21 [1] CRAN (R 4.3.0)
 harmony                     * 0.1.1     2022-11-14 [1] CRAN (R 4.3.1)
 hdf5r                         1.3.8     2023-01-21 [1] CRAN (R 4.3.1)
 Hmisc                         5.1-0     2023-05-08 [1] CRAN (R 4.3.1)
 hms                           1.1.3     2023-03-21 [1] CRAN (R 4.3.1)
 htmlTable                     2.4.1     2022-07-07 [1] CRAN (R 4.3.1)
 htmltools                     0.5.5     2023-03-23 [1] CRAN (R 4.3.0)
 htmlwidgets                   1.6.2     2023-03-17 [1] CRAN (R 4.3.0)
 httpuv                        1.6.11    2023-05-11 [1] CRAN (R 4.3.0)
 httr                          1.4.6     2023-05-08 [1] CRAN (R 4.3.0)
 ica                           1.0-3     2022-07-08 [1] CRAN (R 4.3.0)
 igraph                        1.5.0     2023-06-16 [1] CRAN (R 4.3.1)
 IRanges                     * 2.34.1    2023-06-22 [1] Bioconductor
 irlba                         2.3.5.1   2022-10-03 [1] CRAN (R 4.3.0)
 jsonlite                      1.8.7     2023-06-29 [1] CRAN (R 4.3.1)
 KEGGREST                      1.40.0    2023-04-25 [1] Bioconductor
 KernSmooth                    2.23-20   2021-05-03 [2] CRAN (R 4.3.0)
 knitr                         1.43      2023-05-25 [1] CRAN (R 4.3.0)
 labeling                      0.4.2     2020-10-20 [1] CRAN (R 4.3.0)
 later                         1.3.1     2023-05-02 [1] CRAN (R 4.3.0)
 lattice                       0.21-8    2023-04-05 [2] CRAN (R 4.3.0)
 lazyeval                      0.2.2     2019-03-15 [1] CRAN (R 4.3.0)
 leiden                        0.4.3     2022-09-10 [1] CRAN (R 4.3.0)
 lifecycle                     1.0.3     2022-10-07 [1] CRAN (R 4.3.0)
 listenv                       0.9.0     2022-12-16 [1] CRAN (R 4.3.0)
 lmtest                        0.9-40    2022-03-21 [1] CRAN (R 4.3.0)
 lubridate                   * 1.9.2     2023-02-10 [1] CRAN (R 4.3.1)
 magrittr                      2.0.3     2022-03-30 [1] CRAN (R 4.3.0)
 MASS                          7.3-58.4  2023-03-07 [2] CRAN (R 4.3.0)
 Matrix                      * 1.6-0     2023-07-08 [1] CRAN (R 4.3.1)
 MatrixGenerics                1.12.2    2023-06-11 [1] Bioconductor
 matrixStats                   1.0.0     2023-06-02 [1] CRAN (R 4.3.0)
 memoise                       2.0.1     2021-11-26 [1] CRAN (R 4.3.0)
 mime                          0.12      2021-09-28 [1] CRAN (R 4.3.0)
 miniUI                        0.1.1.1   2018-05-18 [1] CRAN (R 4.3.0)
 munsell                       0.5.0     2018-06-12 [1] CRAN (R 4.3.0)
 nlme                          3.1-162   2023-01-31 [2] CRAN (R 4.3.0)
 nnet                          7.3-18    2022-09-28 [2] CRAN (R 4.3.0)
 parallelly                    1.36.0    2023-05-26 [1] CRAN (R 4.3.0)
 patchwork                     1.1.2     2022-08-19 [1] CRAN (R 4.3.0)
 pbapply                       1.7-2     2023-06-27 [1] CRAN (R 4.3.1)
 pillar                        1.9.0     2023-03-22 [1] CRAN (R 4.3.0)
 pkgconfig                     2.0.3     2019-09-22 [1] CRAN (R 4.3.0)
 plotly                        4.10.2    2023-06-03 [1] CRAN (R 4.3.0)
 plyr                          1.8.8     2022-11-11 [1] CRAN (R 4.3.0)
 png                           0.1-8     2022-11-29 [1] CRAN (R 4.3.0)
 polyclip                      1.10-4    2022-10-20 [1] CRAN (R 4.3.0)
 prettyunits                   1.1.1     2020-01-24 [1] CRAN (R 4.3.0)
 progress                      1.2.2     2019-05-16 [1] CRAN (R 4.3.1)
 progressr                     0.13.0    2023-01-10 [1] CRAN (R 4.3.0)
 promises                      1.2.0.1   2021-02-11 [1] CRAN (R 4.3.0)
 ProtGenerics                  1.32.0    2023-04-25 [1] Bioconductor
 purrr                       * 1.0.1     2023-01-10 [1] CRAN (R 4.3.0)
 qlcMatrix                   * 0.9.7     2018-04-20 [1] CRAN (R 4.3.1)
 R6                            2.5.1     2021-08-19 [1] CRAN (R 4.3.0)
 RANN                          2.6.1     2019-01-08 [1] CRAN (R 4.3.0)
 rappdirs                      0.3.3     2021-01-31 [1] CRAN (R 4.3.0)
 RColorBrewer                  1.1-3     2022-04-03 [1] CRAN (R 4.3.0)
 Rcpp                        * 1.0.11    2023-07-06 [1] CRAN (R 4.3.1)
 RcppAnnoy                     0.0.21    2023-07-02 [1] CRAN (R 4.3.1)
 RcppRoll                      0.3.0     2018-06-05 [1] CRAN (R 4.3.0)
 RCurl                         1.98-1.12 2023-03-27 [1] CRAN (R 4.3.0)
 readr                       * 2.1.4     2023-02-10 [1] CRAN (R 4.3.1)
 reshape2                      1.4.4     2020-04-09 [1] CRAN (R 4.3.0)
 restfulr                      0.0.15    2022-06-16 [1] CRAN (R 4.3.1)
 reticulate                    1.30      2023-06-09 [1] CRAN (R 4.3.0)
 rjson                         0.2.21    2022-01-09 [1] CRAN (R 4.3.0)
 rlang                         1.1.1     2023-04-28 [1] CRAN (R 4.3.0)
 rmarkdown                     2.23      2023-07-01 [1] CRAN (R 4.3.1)
 ROCR                          1.0-11    2020-05-02 [1] CRAN (R 4.3.0)
 rpart                         4.1.19    2022-10-21 [2] CRAN (R 4.3.0)
 Rsamtools                     2.16.0    2023-04-25 [1] Bioconductor
 RSQLite                       2.3.1     2023-04-03 [1] CRAN (R 4.3.1)
 rstatix                       0.7.2     2023-02-01 [1] CRAN (R 4.3.1)
 rstudioapi                    0.15.0    2023-07-07 [1] CRAN (R 4.3.1)
 rtracklayer                 * 1.60.0    2023-04-25 [1] Bioconductor
 Rtsne                         0.16      2022-04-17 [1] CRAN (R 4.3.0)
 S4Arrays                      1.0.4     2023-05-14 [1] Bioconductor
 S4Vectors                   * 0.38.1    2023-05-02 [1] Bioconductor
 scales                        1.2.1     2022-08-20 [1] CRAN (R 4.3.0)
 scattermore                   1.2       2023-06-12 [1] CRAN (R 4.3.0)
 sctransform                   0.3.5     2022-09-21 [1] CRAN (R 4.3.0)
 sessioninfo                 * 1.2.2     2021-12-06 [1] CRAN (R 4.3.1)
 Seurat                      * 4.3.0.1   2023-06-22 [1] CRAN (R 4.3.1)
 SeuratObject                * 4.1.3     2022-11-07 [1] CRAN (R 4.3.0)
 shiny                         1.7.4.1   2023-07-06 [1] CRAN (R 4.3.1)
 Signac                      * 1.10.0    2023-05-30 [1] CRAN (R 4.3.1)
 slam                        * 0.1-50    2022-01-08 [1] CRAN (R 4.3.0)
 sp                            2.0-0     2023-06-22 [1] CRAN (R 4.3.1)
 sparsesvd                   * 0.2-2     2023-01-14 [1] CRAN (R 4.3.1)
 spatstat.data                 3.0-1     2023-03-12 [1] CRAN (R 4.3.0)
 spatstat.explore              3.2-1     2023-05-13 [1] CRAN (R 4.3.0)
 spatstat.geom                 3.2-2     2023-07-06 [1] CRAN (R 4.3.1)
 spatstat.random               3.1-5     2023-05-11 [1] CRAN (R 4.3.0)
 spatstat.sparse               3.0-2     2023-06-25 [1] CRAN (R 4.3.1)
 spatstat.utils                3.0-3     2023-05-09 [1] CRAN (R 4.3.0)
 stringi                       1.7.12    2023-01-11 [1] CRAN (R 4.3.0)
 stringr                     * 1.5.0     2022-12-02 [1] CRAN (R 4.3.0)
 SummarizedExperiment          1.30.2    2023-06-06 [1] Bioconductor
 survival                      3.5-5     2023-03-12 [2] CRAN (R 4.3.0)
 tensor                        1.5       2012-05-05 [1] CRAN (R 4.3.0)
 tibble                      * 3.2.1     2023-03-20 [1] CRAN (R 4.3.0)
 tidyr                       * 1.3.0     2023-01-24 [1] CRAN (R 4.3.0)
 tidyselect                    1.2.0     2022-10-10 [1] CRAN (R 4.3.0)
 tidyverse                   * 2.0.0     2023-02-22 [1] CRAN (R 4.3.1)
 timechange                    0.2.0     2023-01-11 [1] CRAN (R 4.3.1)
 tweenr                        2.0.2     2022-09-06 [1] CRAN (R 4.3.1)
 tzdb                          0.4.0     2023-05-12 [1] CRAN (R 4.3.1)
 utf8                          1.2.3     2023-01-31 [1] CRAN (R 4.3.0)
 uwot                          0.1.16    2023-06-29 [1] CRAN (R 4.3.1)
 VariantAnnotation             1.46.0    2023-04-25 [1] Bioconductor
 vctrs                         0.6.3     2023-06-14 [1] CRAN (R 4.3.0)
 viridisLite                   0.4.2     2023-05-02 [1] CRAN (R 4.3.0)
 withr                         2.5.0     2022-03-03 [1] CRAN (R 4.3.0)
 xfun                          0.39      2023-04-20 [1] CRAN (R 4.3.0)
 XML                           3.99-0.14 2023-03-19 [1] CRAN (R 4.3.0)
 xml2                          1.3.5     2023-07-06 [1] CRAN (R 4.3.1)
 xtable                        1.8-4     2019-04-21 [1] CRAN (R 4.3.0)
 XVector                     * 0.40.0    2023-04-25 [1] Bioconductor
 yaml                          2.3.7     2023-01-23 [1] CRAN (R 4.3.0)
 zlibbioc                      1.46.0    2023-04-25 [1] Bioconductor
 zoo                           1.8-12    2023-04-13 [1] CRAN (R 4.3.0)

 [1] C:/Users/user/AppData/Local/R/win-library/4.3
 [2] C:/Program Files/R/R-4.3.0/library

**Comment by timoast** [comment]
it's hard to know without seeing all the steps, but if you save the objects and move them to a different computer or move the fragment files you would need to update the fragment file paths. You should also verify that the fragment files are present in the path that you expect
