### ISSUE TITLE
Is it possible to only plot links for one gene within a genomic region?

### ISSUE THREAD

**Issue by jogiles** [stuart-lab/signac#1459]
Hello!

I am hoping there is a way to plot any and all links to **one** gene within a genomic region. When I set the region within LinkPlots(), it plots all links to all genes within those coordinates -- which can be a LOT and it is hard to distinguish the gene of interest and its specific links. If I use the gene name for the region argument, it only plots links within gene and omits the distal links. 

I really appreciate your help with this!

Thank you,
Josephine

**Comment by timoast** [comment]
This is not currently possible, we could try to add that in the future

**Comment by jogiles** [comment]
Ah, ok. It would be really helpful!!!! Thank you for the wonderful analysis package.

**Comment by jogiles** [comment]
Hello! Just wondering if this will be possible soon :) Thank you!!!!!

**Comment by timoast** [comment]
Hi @jogiles, I've just added this to the develop branch. You should now be able to pass a vector of gene names to the `links` parameter which will determine which links are shown in the plot (the original true/false parameter settings are also still possible to show all/none of the links)

**Comment by jogiles** [comment]
Hi @timoast ! It works perfectly!!!! Thank you SO much. This R package is a gem.
