### ISSUE TITLE
Getting coordinates for specific peaks in coverage plot

### ISSUE THREAD

**Issue by klgoss** [stuart-lab/signac#1463]
Hello, 

Is there a way to get the chromosome coordinates for each selected (red box) peak in this coverage plot?

Thank you!

![Screenshot 2023-08-02 at 4 46 25 PM](https://github.com/stuart-lab/signac/assets/53942497/12162079-fbae-4465-aa70-f709b8e7b559)

**Comment by timoast** [comment]
You can find the peaks that intersect with the region that you plotted using functions in the `GenomicRanges` package. However, the regions you indicated are not identified as peaks in your dataset (peaks shown in the grey lines below). You could try optimizing the peak calling step to make sure these are identified
