### ISSUE TITLE
Error in UseMethod(generic = "RunChromVAR", object = object) :    no applicable method for 'RunChromVAR' 

### ISSUE THREAD

**Issue by elanur-yilmaz** [stuart-lab/signac#1467]
Dear Team,
I am new at multiome analysis and running a tutorial (https://github.com/quadbio/scMultiome_analysis_vignette/blob/main/Tutorial.md) in my data set.

At "Step 4. ChromVAR: another motif enrichment analysis" while I was running seurat <- RunChromVAR(seurat, genome = BSgenome.Hsapiens.UCSC.hg38) in my data set, I got the error below.

Error in UseMethod(generic = "RunChromVAR", object = object) : 
  no applicable method for 'RunChromVAR' applied to an object of class "c('Assay', 'KeyMixin')"

I restarted the session, and checked online but did not find a solution. Can anyone help me?

Thank you very much,

Elanur

**Comment by timoast** [comment]
It's hard to know what the issue is without seeing the full code, but from the error message it looks like you're trying to run this function on a standard assay rather than a chromatin assay

**Comment by timoast** [comment]
it looks like you're trying to run this on the RNA assay rather than the ATAC, try changing the assay first
