### ISSUE TITLE
AccessiblePeaks returning different results

### ISSUE THREAD

**Issue by klgoss** [stuart-lab/signac#1470]
Hello, thanks for the great tool. 

I'm trying to get the all of the accessible chromatin regions in each of my samples. We have a "day 1" sample that's made up of 5 donors. When I get the overall number of accessible peaks at day 1 with the AccessiblePeaks function, I get 147186 peaks. However, when I break it down by donor to see the donor-donor variability, I get the following numbers:
Donor 1: 56769
Donor 2: 69612
Donor 3: 95021
Donor 4: 66292
Donor 5: 60173

When I add these all together or take the average, I cannot get the original number of 147186. I'm not sure if this is due to a bug or if I'm not understanding how the function works. Could someone please help me understand why there is a discrepancy? Any insight is greatly appreciated.

Code below and I'm using Signac version 1.9.0.9000 and Seurat version 5
```r
# Get accessible regions for each timepoint #
Idents(object = obj) <- "group"
a <- AccessiblePeaks(obj, assay = "peaks", idents = "day1")

# Get ACRs by donor on day 1
day1 <- subset(obj, group == "day1")

donor1 <- subset(day1, Sample == "donor01")
Idents(object = donor1) <- "Sample"
a <- AccessiblePeaks(donor1, assay = "peaks", idents = "donor01")

donor2 <- subset(day1, Sample == "donor02")
Idents(object = donor2) <- "Sample"
b <- AccessiblePeaks(donor2, assay = "peaks", idents = "donor02")

donor3 <- subset(day1, Sample == "donor03")
Idents(object = donor3) <- "Sample"
c <- AccessiblePeaks(donor3, assay = "peaks", idents = "donor03")

donor4 <- subset(day1, Sample == "donor04")
Idents(object = donor4) <- "Sample"
d <- AccessiblePeaks(donor4, assay = "peaks", idents = "donor04")

donor5 <- subset(day1, Sample == "donor05")
Idents(object = donor5) <- "Sample"
e <- AccessiblePeaks(donor5, assay = "peaks", idents = "donor05")
```

**Comment by timoast** [comment]
I think this is just a misunderstanding of what the function is doing. AccessiblePeaks will return peaks that have more than a certain number of total counts for a group of cells. When you run this for multiple different groups, the same peak could be accessible in the different groups of cells which is why the total number of accessible peaks for the whole population won't necessarily be the same as the number of accessible peaks for each separate group of cells.
