### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by JunxiFeng** [stuart-lab/signac#1476]
Hi,

I just want some suggestions and insights regarding the problem I encounter. 

I was trying to make a coverage plot. I followed the instructions and then successfully made one. But then I quitted R and now with the same code (I changed nothing), I failed to make one: the function doesn't produce any errors, but it just keeps running for a long time without returning anything (it was very fast before). Then I realized that this happens any types of plot I want to generate with Signac. 

I have removed the package and reinstalled, but it doesn't work. All other functions work properly, only the ones with visualization, and there's no error, they just keep running forever....

Thanks!!

**Comment by timoast** [comment]
It sounds like this is an issue with the plotting device in R, rather than anything to do with Signac. Are you running this in RStudio, R, or as an R script?

I would suggest searching some general R support sites like stackoverflow or rstudio community for users reporting similar issues

**Comment by timoast** [comment]
Closing this as I haven't heard back, please see the suggestions above
