### ISSUE TITLE
mtDNA genotyping 

### ISSUE THREAD

**Issue by RaghadShu** [stuart-lab/signac#1482]
Hi, 
Thanks for the great tool.
I am running the mtDNA genotyping viginette on one multiple myeloma sample that is originally a Multiome (GEX + ATAC)
 
This is the variants plot I get: (notice the vmr = 0)
![image](https://github.com/stuart-lab/signac/assets/143171933/9ecf96da-da5c-4c22-82cb-bab4fa8d10af)

Can you help me understand what this means, and why is it the case? and how to choose a high-confidance threshold for the vmr in this case.

Best,
Raghad

**Comment by timoast** [comment]
Can you show the variants dataframe that you're using to generate this plot?

**Comment by RaghadShu** [comment]
Yes, this is the variable sites table obtained from IdentifyVariants()
 
[MM3_variable_sites.txt](https://github.com/stuart-lab/signac/files/12547438/MM3_variable_sites.txt)

**Comment by timoast** [comment]
I think your data might be too low coverage. It's also possible that there are not many variants present in this, as most sites seem to have mean 0 (which is the mean counts for that variant across all the cells), suggesting that most of the covered sites are the wild-type allele

**Comment by RaghadShu** [comment]
That makes sense. I would like to double-check something: my understanding is that sc-Multiome sequencing (GEX + ATAC) only sequences what's inside the nucleus for each cell. So I am wondering if it is even possible to detect any mitochondrial genome/variants (since mitochondria are not in the nucleus) in the 10X Multiome data. 

It's a bit unclear to me if the variantes detected in the vignette is from scATAC-seq only or also mtscATAC-seq too.

**Comment by RaghadShu** [comment]
Hello, no response?

**Comment by timoast** [comment]
You can read the paper that generated that data here: https://www.nature.com/articles/s41587-020-0645-6

The data is generated by mtscATAC-seq

**Comment by RaghadShu** [comment]
Yes, but I am wondering if it's correct to estimate mtDNA from scATAC (like in here: https://github.com/caleblareau/mgatk/wiki/Process-mtDNA-from-CellRanger-ATAC)

**Comment by timoast** [comment]
Better to ask over there: https://github.com/caleblareau/mgatk/issues
