### ISSUE TITLE
Ability to add fragment files hosted on cloud storage platforms to ChromatinAssay

### ISSUE THREAD

**Issue by sabrinacamp2** [stuart-lab/signac#1484]
Hi,

Thank you for the great tool! 

Recently, some folks in our group have wanted to share a Signac processed scATAC RDS object with others. However, upon receiving the object they are unable to use functions that access the fragment files (e.g. `CoveragePlot`) without,
1. Storing a local copy of all fragment files and indicies on their computer
2. Updating the fragment file paths in the object

I saw that you can use files hosted on remote servers, but it would be nice if you could also specify a cloud storage path in the object as well. Our lab may be in the minority, but all of our data is hosted on cloud storage platforms.

Thanks for considering this feature request,
Sabrina

**Comment by timoast** [comment]
This is supported, there is no difference between a remote server and cloud storage, both are data accessed over the internet.

You need to ensure the file is accessible over ftp or http. Some documentation for how to make objects in S3 accessible can be found here: https://repost.aws/knowledge-center/read-access-objects-s3-bucket

**Comment by sabrinacamp2** [comment]
Ah ok, thanks for letting me know. I see now the issue is that my cloud account does not have the right permissions to allow public read access to the object. I'll have to look into how to get around that. Thanks again!
