### ISSUE TITLE
AddChromatinModule With Genes From Publication

### ISSUE THREAD

**Issue by colinraposo** [stuart-lab/signac#1487]
Hi Tim

I was wondering if it was possible to use `AddChromatinModule` to add a chromatin score from a published peak set. 

I tried to use `AddChromatinModule` to add a score for differential peaks up in a published scATAC-seq cluster, and ran into this issue with the following code:

``` 
# top 5 peaks from cluster as example
my_peaks <- c("chr5-113156811-113157312",  "chr11-95907730-95908231" ,  "chr4-135406062-135406563",  "chr4-21989645-21990146", "chr2-83695398-83695899" )

features <- list("my_module" =  my_peaks)

so <- AddChromatinModule(so, features = features_tex, assay = "peaks", genome = BSgenome.Mmusculus.UCSC.mm10)
```
```
Error in sparseMatrix(i = unlist(x = feat.idx, use.names = FALSE), j = unlist(x = j,  : 
  'i' and 'j' must not contain NA
```

I checked that if I took random features from my object by `head(rownames(so))` , I was not leading to this same issue.

Using the code from the original GitHub post where you described this feature, I was able to trace the issue back to indexing of the peaks. As you can see here, when I use features from my object as the input, I am able to create an index, while using peaks from the published set, I am unable to.

```
# two peak sets - one based on publication and one based on seurat object as control
so_peaks <- head(rownames(so))
my_peaks <- c("chr5-113156811-113157312",  "chr11-95907730-95908231" ,  "chr4-135406062-135406563",  "chr4-21989645-21990146", "chr2-83695398-83695899" )

features_2 <- list("so_module" =  so_peaks,
                   "my_module" =  my_peaks)

ChromatinModuleIdx <- function(object, features, genome, assay) {
 feat.idx <- sapply(X = features, FUN = fmatch, rownames(x = object[[assay]]))
 return(feat.idx)
}

ChromatinModuleIdx(so, features = features_2, assay = "peaks", genome = BSgenome.Mmusculus.UCSC.mm10)
```
```
$so_module
[1] 1 2 3 4 5 6

$my_module
[1] NA NA NA NA NA
```

My question is if it's possible to modify the `AddChromatinModule`  to score my cells based on this other peak set? I assume the issue lies with the binning of peaks for my dataset and the one that was published not being perfectly aligned. Is it possible to remedy this?

Thanks!

**Comment by timoast** [comment]
The peaks need to be present in the count matrix. I would suggest adding these peaks to the list of peaks you're quantifying for the assay.

**Comment by colinraposo** [comment]
Thanks Tim - this make sense
