### ISSUE TITLE
Sample merging

### ISSUE THREAD

**Issue by mode1990** [stuart-lab/signac#1489]
Hi, I have utilized Signac to jointly analyze GEX+ATAC data (12 samples) from Cellranger arc. I have performed the preprocessing including qc and peakcalling as described in this vignette for each sample separately. I was wondering how can I efficiently merge and integrate samples using e.g. Harmony and then create a joint neighbor graph for the integrated object. Thanks a lot for your response and guidance.

**Comment by timoast** [comment]
Have you seen the vignettes on merging and integration?

https://stuartlab.org/signac/articles/merging
https://stuartlab.org/signac/articles/integrate_atac
