### ISSUE TITLE
Error when importing scATAC data from GEO

### ISSUE THREAD

**Issue by mano2991** [stuart-lab/signac#1497]
I'm trying to analyze scATAC data available in the GEO database. The accession I'm working with is GSM5091379, which contains both scRNA-seq and snATAC-seq data.

```
Warning: Expected 3 pieces. Additional pieces discarded in 1 rows [67].Warning: Expected 3 pieces. Missing pieces filled with `NA` in 534 rows [1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 24, ...].Error in .get_data_frame_col_as_numeric(df, granges_cols[["start"]]) : 
  some values in the "start" column cannot be turned into numeric values
```

The code i have used. (https://stuartlab.org/signac/articles/snareseq) 

```
rna <- Read10X("E12_RNA/",gene.column = 1)
atac <- Read10X("E12",gene.column=1)
fragments <- "fragments.sort.bed.gz"
snare <- CreateSeuratObject(counts = rna)
snare[['ATAC']] <- CreateChromatinAssay(counts = atac, sep = c(":", "-"), genome = "mm10", fragments = fragments)
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)
```
I'm seeking assistance to understand and resolve the error message. It appears there might be non-numeric values in the "start" column of the data being read. Guidance on how to correct or bypass this error would be greatly appreciated.

**Comment by timoast** [comment]
This dataset is formatted differently to the SNARE-seq data, you cannot follow the exact same steps to read it in. It's always useful to look at the data files and see what format they are in, for example by running `gzip -dc GSM5091379_CTX_1_features.bed.gz | head`

Please see example code here:
https://github.com/stuart-lab/signac/blob/develop/vignettes/pbmc_vignette.Rmd#L91-L107
