### ISSUE TITLE
Add modifiable parameters for calculating TSS Enrichment score

### ISSUE THREAD

**Issue by Itallia** [stuart-lab/signac#1503]
Hello team,

I am wondering if it would be possible to modify the TSSEnrichment function to allow parameters to be changed in how the TSS enrichment score is calculated, for example the size of the windows used for the regions around the TSS and at the flanking regions. I would personally like to reduce the region surrounding the single-base TSS site from 1000bp to 100bp (+/-50bp surrounding the TSS), an approach that has been used successfully in packages such as ArchR. Defaults for these parameters could stay on the ENCODE standard, but making them modifiable would allow more flexibility for users. I hope you will consider making this simple change.

Thank you,
Dr. Itallia V. Pacentine

**Comment by timoast** [comment]
This has been added to Signac and is available on the develop branch, see https://github.com/stuart-lab/signac/pull/1402
