### ISSUE TITLE
Possbile  Signac::FilterCells bug

### ISSUE THREAD

**Issue by sisterdot** [stuart-lab/signac#1509]
hey, 

thanks a lot for developing and maintaining this very helpful package!!!!

i am possibly observing a bug in the  Signac::FilterCells function.

given a test fragments file
```
zcat fragments.tsv.gz
chr1	9989	10162	GCTGCAATCCAGGGAG-1	1
chr10	25101623	25101727	GCTGCAATCCAGGGAG-1	1
```

and running the code
```
 Signac::FilterCells("fragments.tsv.gz",c("GCTGCAATCCAGGGAG-1","GCTGCAATCCAGGGAG-1"),"test.gz",verbose=T)

Keeping 1 cell barcodes

Compressing filtered file
Indexing fragment file
```

i am obtaining a unexpected filtered fragment file, with a duplication of one of the entries
``` 
zcat test.gz
chr1	9989	10162	GCTGCAATCCAGGGAG-1	1
chr1	9989	10162	GCTGCAATCCAGGGAG-1	1
chr10	25101623	25101727	GCTGCAATCCAGGGAG-1	1
```

it might all come from here:
https://github.com/stuart-lab/signac/blob/master/src/filter.cpp

```
R version 4.2.2 (2022-10-31)
Signac_1.9.0
```

thanks for your help!

**Comment by timoast** [comment]
Hi @sisterdot, thanks for reporting. This was a bug causing the first line of the fragment file to be duplicated if there was no fragment header and the first line of the fragment file was from a cell to be retained. This is now fixed on the develop branch.
