### ISSUE TITLE
Gene not in dataset

### ISSUE THREAD

**Issue by ccomo0730** [stuart-lab/signac#1513]
Hello! I am trying to show a link between the gene Sox2 and the upstream gene Sox2ot. Sox2ot is a long non coding RNA, but when I try to visualize it, it isn't found. Is there any way to find this gene or add it?
chr3-34614864-34732142

Thanks!

**Comment by timoast** [comment]
You can add any gene annotation information you want, this is a step controlled by the user not by the software package. You will need to ensure these gene coordinates are present in the gene annotation you are adding.
