### ISSUE TITLE
gene not found after geneactivity()

### ISSUE THREAD

**Issue by linzhangTuesday** [stuart-lab/signac#1536]
Hi I am checking expression of a gene using dotplot/vlnplot after run GeneActivity() on my scATAC-seq object

The peak profile around that gene can be viewed by CoveragePlot() and that gene is present in annotation$gene_name

However, vlnplot/dotplot cannot find it and that gene is missing from my_scATAC_object@assays$RNA@counts/data slot

Any suggestions/comments would be appreciated. Thanks!

**Comment by timoast** [comment]
Please include the full code and output of `sessionInfo()`

**Comment by linzhangTuesday** [comment]
Thanks for the message. turns out that gene is really long. resolved after setting  max.width =NULL for geneactivity(). Thanks anyway.
