### ISSUE TITLE
CoveragePlot Error in `slice_sample()`

### ISSUE THREAD

**Issue by fahmadimoughari** [stuart-lab/signac#1542]
Hi,

I have a seurat object which is created by "merge" on multiple samples, before merging, I harmonized the peaks using reduce. I wanted to run CoveragePlot on it, but I faced the following error:
 `Error in `slice_sample()`:
! Problem while computing indices.
Caused by error in `sample.int()`:
! invalid first argument
Backtrace:
     x
  1. +-global make.coverage(...)
  2. | \-Signac::CoveragePlot(...)
  3. |   \-Signac:::SingleCoveragePlot(...)
  4. |     \-Signac:::CoverageTrack(...)
  5. |       +-dplyr::slice_sample(.data = coverages, n = sampling)
  6. |       \-dplyr:::slice_sample.data.frame(.data = coverages, n = sampling)
  7. |         +-dplyr::slice(...)
  8. |         \-dplyr:::slice.data.frame(...)
  9. |           \-dplyr:::slice_rows(.data, ..., caller_env = caller_env(), error_call = current_env())
 10. |             \-dplyr:::slice_eval(mask, dots, error_call = error_call)
 11. |               +-base::withCallingHandlers(...)
 12. |               \-mask$eval_all(quo(impl(!!!dots)))
 13. +-dplyr (local) impl(...)
 14. | \-dplyr:::...elt2(i)
 15. |   \-rlang::eval_bare(sym(paste0("..", i)), frame)
 16. +-rlang (local) local(...)
 17. +-base::local(...)
 18. | \-base::eval.parent(substitute(eval(quote(expr), envir)))
 19. |   \-base::eval(expr, p)
 20. |     \-base::eval(expr, p)
 21. |       \-base::eval(...)
 22. |         \-base::eval(...)
 23. |           \-dplyr:::sample_int(n, size(n), replace = replace, wt = weight_by)
 24. |             \-base::sample.int(n, size, prob = wt, replace = replace)
 25. \-base::.handleSimpleError(...)
 26.   \-dplyr (local) h(simpleError(msg, call))
 27.     \-rlang::abort(bullets, call = error_call, parent = cnd)
Execution halted
srun: error: node06: task 0: Exited with exit code 1`

Any idea whats the cause of this issue?

**Comment by timoast** [comment]
Hi, please show the full code you're running and the output of `sessionInfo()`

**Comment by fahmadimoughari** [comment]
The issue is resolved because previously I was changing the metadata of Seurat obj and that caused downstream issues.
