### ISSUE TITLE
Not all hexamers represented in input region

### ISSUE THREAD

**Issue by rogercasalsfr** [stuart-lab/signac#1543]
Hi,
I'm trying to reproduce the tutorial vignettes on a different data. All the steps were performed (except the peak calling). 
And when I arrive at the footprint function I found the following error: 

``` > pbmc <- Footprint(
+   object = pbmc,
+   motif.name = c("GATA2", "CEBPA", "EBF1"),
+   genome = BSgenome.Hsapiens.UCSC.hg38
+ )
Computing Tn5 insertion bias
Extracting reads in requested region
Error in InsertionBias.ChromatinAssay(object = object, genome = genome,  : 
  Not all hexamers represented in input region ```

I've tried to change the motifs names and also include a region, but always the same error. I also tried to use the function InsertionBias, but it still appears me the same error. I was hoping if you could help me.

Thank you.

**Comment by timoast** [comment]
you should try running `InsertionBias()` with a larger region. However, the default region is the first chromosome, so if you don't have enough Tn5 insertions in the whole chromosome to compute the insertion bias for each hexamer you likely have very sparse data that wouldn't be suitable for footprinting anyway
