### ISSUE TITLE
Want to add motif corresponding to peaks in Coverage Plot

### ISSUE THREAD

**Issue by raunakkar** [stuart-lab/signac#1552]
Hi @timoast,
Thank you for this wonderful package. I am very naive in this field and was looking for some guidance as to how to add motifs in a coverage plot? I have paired (ATAC + RNA) multiome data and have added Motif object to my dataset. However I want to annotate a peak as a putative TF binding site and visualize in Coverage plot. Something similar to this (doi: https://doi.org/10.1016/j.xgen.2023.100263) :
![Screenshot from 2023-12-09 14-44-29](https://github.com/stuart-lab/signac/assets/106430495/765c9de5-8ef5-4fc5-8728-1679b26fd3b5)
For now I have coverage plots like this:
[coverage_GNLY.pdf](https://github.com/stuart-lab/signac/files/13623553/coverage_GNLY.pdf)
Any suggestions would be amazing.

Thank you in advance.

**Comment by timoast** [comment]
Hi, you can set the `region.highlight` parameter and give the coordinates of the motif position that you want to highlight

**Comment by raunakkar** [comment]
Thank you for the prompt response. Unfortunately not exactly what I am looking for. What I am looking for is some way to annotate the set of peaks for their motif enrichment _de novo_, rather than manually annotating them. Like had there been a parameter in the coverage plot where I can supply the motif file and the set of peaks in the region would be annotated for motif enrichment.
I don't know if this makes sense? Please do correct me if I am wrong.

Thank you.
