### ISSUE TITLE
Variable features after adding gene activity to Seurat object

### ISSUE THREAD

**Issue by czfoo** [stuart-lab/signac#1568]
### Discussed in https://github.com/stuart-lab/signac/discussions/1567

<div type='discussions-op-text'>

<sup>Originally posted by **czfoo** December 20, 2023</sup>
Hi everyone,

After I ran the GeneActivity function and tried to add it to my Seurat object with the CreateAssayObject function, I noticed that the var.features list is empty. How do I get that list populated? The original gene activities matrix before I performed the CreateAssayObject function has them stored under dimsension 1.</div>

**Comment by timoast** [comment]
When you add an assay the variable features are not automatically set, you need to run `FindVariableFeatures()` for RNA or `FindTopFeatures()` for ATAC data. Alternatively you can set the variable features manually using the `VariableFeatures()` assignment function. 

> The original gene activities matrix before I performed the CreateAssayObject function has them stored under dimsension 1.

I think what you're referring to here is that the rownames of the matrix are the gene names, this is different to a set of variable features
