### ISSUE TITLE
Add motifs annotation de novo in Coverage Plot

### ISSUE THREAD

**Issue by raunakkar** [stuart-lab/signac#1571]
Dear @timoast. I am opening a new issue as the previous one did not answer the question I was looking for. Most probably i couldn't convey what I was asking for. 
What I am looking for is some way to annotate the set of peaks in a given region for their motif enrichment _de novo_, rather than manually annotating them in the coverage plot. Like had there been a parameter in the coverage plot where I can supply the motif file and the set of peaks in the region would be annotated for motif enrichment.
I don't know if this makes sense? Please do correct me if I am wrong.

Thank you.

_Originally posted by @raunakkar in https://github.com/stuart-lab/signac/issues/1552#issuecomment-1849316522_

**Comment by timoast** [comment]
If you want to plot the position of motif instances you can supply these as genomic ranges using the `ranges` parameter in `CoveragePlot`. You could also color by different motif types if you wanted to by including metadata in the genomic ranges.
