### ISSUE TITLE
Problem when running GeneActivity() function

### ISSUE THREAD

**Issue by Mariateresa91** [stuart-lab/signac#1575]
Dear all,
I am trying to create a gene activity matrix of a scATAC-seq dataset, but I am always getting this error:

![image](https://github.com/stuart-lab/signac/assets/155670828/713d203f-c62d-4b52-a24a-af8a97a03d1f)

Now, I am new to Signac, and my input is a .h5 file containing both scRNA-seq and scATAC-seq data, but I have done the analysis also taking only the ATAC-seq dataset. I don't know what I am doing wrong honestly. Here is the code I have used:

```
counts <- Read10X_h5("filtered_feature_bc_matrix.h5")
fragpath <- "atac_fragments.tsv"

# create a Seurat object containing the RNA data
pbmc <- CreateSeuratObject(counts = counts$Gene Expression,assay = "RNA")

# create ATAC assay and add it to the object
pbmc[["ATAC"]] <- CreateChromatinAssay(counts = counts$Peaks,sep = c(":", "-"),fragments = fragpath, annotation = annotation_ce11)
genome(pbmc[["ATAC"]]) = 'ce11'

# analyze gene expression data
DefaultAssay(pbmc) <- "RNA"
pbmc <- SCTransform(pbmc)
pbmc <- RunPCA(pbmc)

# analyze ATAC-seq data
pbmc <- FindTopFeatures(pbmc, min.cutoff = 5)
pbmc <- RunTFIDF(pbmc)
pbmc <- RunSVD(pbmc)

# joint UMAP
pbmc <- FindMultiModalNeighbors(object = pbmc,reduction.list = list("pca", "lsi"), dims.list = list(1:50, 2:40),modality.weight.name = "RNA.weight",verbose = TRUE)
pbmc <- RunUMAP(object = pbmc,nn.name = "weighted.nn",verbose = TRUE)
pbmc = RunTSNE(object = pbmc,nn.name = "weighted.nn",tsne.method = "Rtsne")
pbmc = FindNeighbors(object = pbmc, reduction = 'lsi',dims = 2:30)
pbmc = FindClusters(object = pbmc, verbose = FALSE, algorithm = 3)
a = GeneActivity(pbmc, assay = "ATAC")
```

Here is my annotation:

![image](https://github.com/stuart-lab/signac/assets/155670828/b219c5eb-b103-4439-ba12-f2aae49133b9)

Here are the fragments:

![image](https://github.com/stuart-lab/signac/assets/155670828/476261d5-27df-4b5b-8bcf-f736f6e1f256)

Here is the GRanges object:

![image](https://github.com/stuart-lab/signac/assets/155670828/f3f59df1-9b78-4991-b7eb-cf9be9860c13)

and the error is present also when adding the seqlengths to pbmc[["ATAC"]].

Any help would be appreciated!

Mariateresa

**Comment by timoast** [comment]
Can you show the output of `sessionInfo()`?

**Comment by Mariateresa91** [comment]
> Can you show the output of `sessionInfo()`?

Here it is:

![image](https://github.com/stuart-lab/signac/assets/155670828/984ef88e-1b9a-4e30-bbb9-f4c776f06424)

**Comment by timoast** [comment]
Please install the latest Signac release and see if you still have this error

**Comment by timoast** [comment]
Closing this as I haven't heard back, please reopen if you're still having problems
