### ISSUE TITLE
Help with analyzing ATAC data mapped to a human-mouse genome

### ISSUE THREAD

**Issue by davhg96** [stuart-lab/signac#1577]
Hi,
I am trying to analyse 2 ATAC seq samples that have been mapped to a GRCh38 + mm10 genome. When building the objects seurat bounces the _ separators between the genome and the fragment to -

This creates some issues later when merging the objects to compare both samples. And probably down the line when annotating everything.

Some input on hot to navigate this would be great. Maybe going back to SeuratObject 4?

Best

**Comment by timoast** [comment]
Hi, I don't know of an easy way to prevent Seurat from replacing the underscore characters in feature names. I think the best thing to do here is change that yourself to some other character
