### ISSUE TITLE
Error when running pbmc <- TSSEnrichment(object = pbmc, fast = FALSE)

### ISSUE THREAD

**Issue by sropri92** [stuart-lab/signac#1582]
Hi,

I am going through the vignette on Analyzing PBMC scATAC-seq. I run the following line and get this error:

> pbmc <- TSSEnrichment(object = pbmc, fast = FALSE)
Extracting TSS positions
Finding + strand cut sites
Finding - strand cut sites
Computing mean insertion frequency in flanking regions
Normalizing TSS score
Error in slot(object = object, name = layer) : 
  argument "slot" is missing, with no default

I am using the data described in the vignette as well as the genome annotation described (EnsDb.Hsapiens.v75). My annotation also looks correct but you can please check below. I would appreciate any help on how to solve this issue as I have tried a couple things and am stuck. Appreciate the help.

> head(Annotation(pbmc))
GRanges object with 6 ranges and 5 metadata columns:
                  seqnames        ranges strand |           tx_id   gene_name         gene_id
                     <Rle>     <IRanges>  <Rle> |     <character> <character>     <character>
  ENSE00001489430     chrX 192989-193061      + | ENST00000399012      PLCXD1 ENSG00000182378
  ENSE00001536003     chrX 192991-193061      + | ENST00000484611      PLCXD1 ENSG00000182378
  ENSE00002160563     chrX 193020-193061      + | ENST00000430923      PLCXD1 ENSG00000182378
  ENSE00001750899     chrX 197722-197788      + | ENST00000445062      PLCXD1 ENSG00000182378
  ENSE00001489388     chrX 197859-198351      + | ENST00000381657      PLCXD1 ENSG00000182378
  ENSE00001719251     chrX 197861-197923      + | ENST00000429181      PLCXD1 ENSG00000182378
                    gene_biotype     type
                     <character> <factor>
  ENSE00001489430 protein_coding     exon
  ENSE00001536003 protein_coding     exon
  ENSE00002160563 protein_coding     exon
  ENSE00001750899 protein_coding     exon
  ENSE00001489388 protein_coding     exon
  ENSE00001719251 protein_coding     exon
  -------
  seqinfo: 25 sequences (1 circular) from hg19 genome
> head(Fragments(pbmc)[[1]])
  chrom start   end            barcode readCount
1  chr1 10066 10279 TTAGCTTAGGAGAACA-1         2
2  chr1 10072 10279 TTAGCTTAGGAGAACA-1         2
3  chr1 10079 10316 ATATTCCTCTTGTACT-1         2
4  chr1 10084 10340 CGTACAAGTTACCCAA-1         1
5  chr1 10085 10271 TGTGACAGTACAACGG-1         1
6  chr1 10085 10339 CATGCCTTCTCTGACC-1         1

**Comment by Jimmyyun** [comment]
Have the same error... 

`> obj <- TSSEnrichment(object = obj, fast = FALSE)
Extracting TSS positions
Finding + strand cut sites
Finding - strand cut sites
Computing mean insertion frequency in flanking regions
Normalizing TSS score
Error in slot %in% slotNames(x = object) : 
  argument "slot" is missing, with no default`

**Comment by timoast** [comment]
This should be fixed on the develop branch, please see https://github.com/stuart-lab/signac/issues/1538

**Comment by sropri92** [comment]
Thank you Tim

**Comment by Jimmyyun** [comment]
Hey Tim,
Updating to "develop" version is not allowing to run HTODemux. 
`Error in .subscript.2ary(x, , j, drop = TRUE) : subscript out of bounds`
