### ISSUE TITLE
Calling Peaks Vignette - Link broken

### ISSUE THREAD

**Issue by felixm3** [stuart-lab/signac#1588]
At the [calling peaks vignette](https://stuartlab.org/signac/articles/peak_calling), the link at "See our vignette for the code..." is broken.

<img width="858" alt="image" src="https://github.com/stuart-lab/signac/assets/43228120/740f4890-4365-4ef4-ac35-6175497b0d55">

<img width="437" alt="image" src="https://github.com/stuart-lab/signac/assets/43228120/2ab454be-6663-4032-bd9c-6bd69ec2db5d">

**Comment by timoast** [comment]
Thanks for noticing this, it is now fixed in the vignette on the develop branch and will be fixed next time the website is updated. Here is the correct link: https://stuartlab.org/signac/articles/pbmc_vignette.html
