### ISSUE TITLE
How to properly merge scATACseq objects?

### ISSUE THREAD

**Issue by TeodoraTockovska** [stuart-lab/signac#1595]
Hi! I have a quick question. I followed the scATACseq integration [vignette](https://stuartlab.org/signac/articles/integrate_atac) to test integrating my datasets. I wanted to conduct downstream analyses but upon trying to run the CoveragePlot function using a peak, I noticed that the Fragment class was removed from my integrated Seurat object. What is the correct method to add the Fragment classes for the 2 datasets that I merged? Is it possible to do?

Thank you!

**Comment by timoast** [comment]
Hi @TeodoraTockovska, the fragment information should still be present. Make sure you are looking at the correct assay (eg, "peaks" or "ATAC")

**Comment by TeodoraTockovska** [comment]
Hi Tim, thanks for your comment. 

I went through the vignette again using the sample data and I confirmed that the fragments are present in the integrated object. The error was a result of making a mistake while testing the code from the integration [vignette](https://stuartlab.org/signac/articles/integrate_atac). I merged the Seurat objects (which contain both RNA and ATAC assays) using the merge() function, and that resulted in the removal of fragments. I found the [merge vignette](https://stuartlab.org/signac/articles/merging) which I will use to combine my multiome ATAC assays prior to integration.

I just wanted to clarify how to perform an integrative analysis using multiple multiome datasets. For instance, I have 4 multiome datasets which consist of both gene expression (GEX) and chromatin data. My goal for analyzing the samples is to ultimately compare samples based on condition type and run a trajectory analysis on the chromatin data. My Seurat objects for each dataset have 2 assays, and after peak calling, there would be 3 assays in each Seurat object (i.e. RNA, ATAC, peaks). 

I can easily perform integration on the GEX data just by merging the Seurat objects and following the Seurat integration workflows. But, for the chromatin data, I must follow the merge vignette to correctly combine the chromatin data first before integration. So, to my understanding, to keep both modalities in 1 object, I can run the chromatin integration first, then run the GEX integration on the same Seurat object.

Is my understanding correct about how to conduct an integrative analysis using multiple multiome samples?

**Comment by timoast** [comment]
> I just wanted to clarify how to perform an integrative analysis using multiple multiome datasets

You can basically follow the merge vignette except adding the RNA assay to each object before merging. Depending on whether you see batch effects and want to correct them, you can run an integration method (Seurat or Harmony for example) on the RNA and/or ATAC assays.

See this discussion for more: https://github.com/stuart-lab/signac/discussions/438

> Also, what are your thoughts on the [integration tutorial](https://www.10xgenomics.com/analysis-guides/batch-effect-correction-in-chromium-single-cell-atac-data) created by 10X, which uses Harmony? Would you recommend it?

I think Harmony is a good integration method, and is quite fast. Seurat integration also works well for ATAC.

The problem with that vignette from 10x is that they are using different peak sets for the different datasets, with artificially creates massive batch differences. If you follow our [merge vignette](https://stuartlab.org/signac/articles/merging) you can see that these batch effects can often be avoided by properly defining a common set of peaks first. You would need a common peak set later in the analysis anyway if you want to do any sort of comparison across datasets.

**Comment by TeodoraTockovska** [comment]
Hi Tim, 

Thanks for providing the clarifications, it is very helpful! I have no further questions. 

Have a nice day and thank you and your team for an incredible package!

**Comment by TeodoraTockovska** [comment]
Hi Tim, 

I have run into an issue with adding the gene expression data prior to merging. I followed the merging vignette and I have reached the section about [creating the objects](https://stuartlab.org/signac/articles/merging#create-the-objects). I tried to add the gene expression data but the number of cells do not match between my ATAC and RNA datasets. 

Below I show how I attempt the RNA assay addition, but it resulted in an error. I suspect that I need to have the same barcodes for each modality to add it. 

```
counts_sample1 <- Read10X_h5("sample1/filtered_feature_bc_matrix.h5")
gene_expression_sample1 <- counts_sample1$GeneExpression
```

```
sample1_assay <- CreateChromatinAssay(sample1_counts, 
                                      fragments = frags_sample1)
sample1_seurat_obj <- CreateSeuratObject(sample1_assay, 
                                         assay = "ATAC", 
                                         meta.data=md_sample1)
gex_assay <- SeuratObject::CreateAssayObject(counts = gene_expression_sample1)
```

```
# Number of cells per assay and which matched
colnames(sample1_assay) %>% length # 10913
colnames(gex_assay) %>% length # 8309
colnames(sample1_assay)[which(colnames(sample1_assay) %in% colnames(gex))] %>% length # 8213

sample1_seurat_obj[["RNA"]] <- gex_assay
Error in `[[<-`:
! Cannot add new cells with [[<-
Run `rlang::last_trace()` to see where the error occurred.
```

I get the same error when I try to create the Seurat object using the RNA assay and try to add the chromatin assay. Since sample1 contains 8213 matching barcodes between the 2 modalities, I used the subset() function and providing the cells on my Seurat object containing the ATAC data. Is this appropriate to do? I managed to create a Seurat object that contains both assays with 8213 cells. I plan to perform QC on the merged datasets as well since the data reflect the raw data.

**Comment by timoast** [comment]
> I suspect that I need to have the same barcodes for each modality to add it.

>  I used the subset() function and providing the cells on my Seurat object containing the ATAC data. Is this appropriate to do? I managed to create a Seurat object that contains both assays with 8213 cells.

Yes this is correct

> Lastly, I plan to perform QC on the Seurat objects that contain both modalities, prior to merging the chromatin data, since the datasets reflect the raw data. Or should I merge the datasets and then perform QC on the merged chromatin data? I am uncertain about the order of analyses.

Either is fine

**Comment by TeodoraTockovska** [comment]
Thanks for your help, I was able to successfully integrate the data. I am closing this issue.

**Comment by maithermbarros** [comment]
@TeodoraTockovska  I am trying to integrate 2 multiome datasets too but still confused on how to do it. Would you mind sharing your code, please? I could send you my email address if so. Thanks a lot!
