### ISSUE TITLE
function 'as_cholmod_sparse' not provided by package 'Matrix'

### ISSUE THREAD

**Issue by realmungmung** [stuart-lab/signac#1599]
Following the PBMC signac intruction, got this error when running pbmc <- RunSVD(pbmc):

Error in irlba(A = t(x = object), nv = n, work = irlba.work, tol = tol) : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'

Tried the solution:
install.packages("irlba", type="source")
install.packages("Matrix", type = "source")
install.packages("SeuratObject", type = "source")

But still got the same error after reopen the Rstudio again

**Comment by realmungmung** [comment]
Got these errors when installing irlba packages in Rstudio:

ld: warning: search path '/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0' not found
ld: warning: search path '/opt/gfortran/lib' not found
ld: library 'gfortran' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Matrix.so] Error 1
ERROR: compilation failed for package ‘Matrix’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Matrix’
Warning in install.packages :
  installation of package ‘Matrix’ had non-zero exit status
ERROR: dependency ‘Matrix’ is not available for package ‘irlba’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/irlba’
Warning in install.packages :
  installation of package ‘irlba’ had non-zero exit status

**Comment by realmungmung** [comment]
also after I installed the packages in R, it showed that Matrix and irlba are not installed when I opened Rstudio

**Comment by realmungmung** [comment]
after installation, it showed:
1: In install.packages("SeuratObject", type = "source") :
  installation of package ‘Matrix’ had non-zero exit status
2: In install.packages("SeuratObject", type = "source") :
  installation of package ‘SeuratObject’ had non-zero exit status
In install.packages("irlba", type = "source") :
  installation of package ‘irlba’ had non-zero exit status

**Comment by realmungmung** [comment]
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.2 (2023-10-31)
 os       macOS Sonoma 14.2.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Los_Angeles
 date     2024-01-19
 rstudio  2023.12.0+369 Ocean Storm (desktop)
 pandoc   3.1.1 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version    date (UTC) lib source
 abind                  1.4-5      2016-07-21 [1] CRAN (R 4.3.0)
 AnnotationDbi        * 1.64.1     2023-11-02 [1] Bioconductor
 AnnotationFilter     * 1.26.0     2023-10-26 [1] Bioconductor
 backports              1.4.1      2021-12-13 [1] CRAN (R 4.3.0)
 base64enc              0.1-3      2015-07-28 [1] CRAN (R 4.3.0)
 Biobase              * 2.62.0     2023-10-26 [1] Bioconductor
 BiocFileCache          2.10.1     2023-10-26 [1] Bioconductor
 BiocGenerics         * 0.48.1     2023-11-02 [1] Bioconductor
 BiocIO                 1.12.0     2023-10-26 [1] Bioconductor
 BiocParallel           1.36.0     2023-10-26 [1] Bioconductor
 biomaRt                2.58.0     2023-10-26 [1] Bioconductor
 Biostrings             2.70.1     2023-10-26 [1] Bioconductor
 biovizBase           * 1.50.0     2023-10-26 [1] Bioconductor
 bit                    4.0.5      2022-11-15 [1] CRAN (R 4.3.0)
 bit64                  4.0.5      2020-08-30 [1] CRAN (R 4.3.0)
 bitops                 1.0-7      2021-04-24 [1] CRAN (R 4.3.0)
 blob                   1.2.4      2023-03-17 [1] CRAN (R 4.3.0)
 BSgenome               1.70.1     2023-11-02 [1] Bioconductor
 cachem                 1.0.8      2023-05-01 [1] CRAN (R 4.3.0)
 checkmate              2.3.1      2023-12-04 [1] CRAN (R 4.3.1)
 cli                    3.6.2      2023-12-11 [1] CRAN (R 4.3.1)
 cluster                2.1.6      2023-12-01 [1] CRAN (R 4.3.1)
 codetools              0.2-19     2023-02-01 [1] CRAN (R 4.3.2)
 colorspace             2.1-0      2023-01-23 [1] CRAN (R 4.3.0)
 cowplot                1.1.2      2023-12-15 [1] CRAN (R 4.3.1)
 crayon                 1.5.2      2022-09-29 [1] CRAN (R 4.3.0)
 curl                   5.2.0      2023-12-08 [1] CRAN (R 4.3.1)
 data.table             1.14.10    2023-12-08 [1] CRAN (R 4.3.1)
 DBI                    1.2.1      2024-01-12 [1] CRAN (R 4.3.2)
 dbplyr                 2.4.0      2023-10-26 [1] CRAN (R 4.3.1)
 DelayedArray           0.28.0     2023-11-06 [1] Bioconductor
 deldir                 2.0-2      2023-11-23 [1] CRAN (R 4.3.1)
 dichromat              2.0-0.1    2022-05-02 [1] CRAN (R 4.3.0)
 digest                 0.6.34     2024-01-11 [1] CRAN (R 4.3.1)
 dotCall64              1.1-1      2023-11-28 [1] CRAN (R 4.3.1)
 dplyr                * 1.1.4      2023-11-17 [1] CRAN (R 4.3.1)
 ellipsis               0.3.2      2021-04-29 [1] CRAN (R 4.3.0)
 EnsDb.Hsapiens.v75   * 2.99.0     2024-01-16 [1] Bioconductor
 ensembldb            * 2.26.0     2023-10-26 [1] Bioconductor
 evaluate               0.23       2023-11-01 [1] CRAN (R 4.3.1)
 fansi                  1.0.6      2023-12-08 [1] CRAN (R 4.3.1)
 farver                 2.1.1      2022-07-06 [1] CRAN (R 4.3.0)
 fastDummies            1.7.3      2023-07-06 [1] CRAN (R 4.3.0)
 fastmap                1.1.1      2023-02-24 [1] CRAN (R 4.3.0)
 fastmatch              1.1-4      2023-08-18 [1] CRAN (R 4.3.0)
 filelock               1.0.3      2023-12-11 [1] CRAN (R 4.3.1)
 fitdistrplus           1.1-11     2023-04-25 [1] CRAN (R 4.3.0)
 foreign                0.8-86     2023-11-28 [1] CRAN (R 4.3.1)
 Formula                1.2-5      2023-02-24 [1] CRAN (R 4.3.0)
 future                 1.33.1     2023-12-22 [1] CRAN (R 4.3.1)
 future.apply           1.11.1     2023-12-21 [1] CRAN (R 4.3.1)
 generics               0.1.3      2022-07-05 [1] CRAN (R 4.3.0)
 GenomeInfoDb         * 1.38.5     2023-12-30 [1] Bioconductor 3.18 (R 4.3.2)
 GenomeInfoDbData       1.2.11     2024-01-12 [1] Bioconductor
 GenomicAlignments      1.38.1     2024-01-13 [1] Bioconductor 3.18 (R 4.3.2)
 GenomicFeatures      * 1.54.1     2023-10-30 [1] Bioconductor
 GenomicRanges        * 1.54.1     2023-10-30 [1] Bioconductor
 ggplot2              * 3.4.4      2023-10-12 [1] CRAN (R 4.3.1)
 ggrepel                0.9.5      2024-01-10 [1] CRAN (R 4.3.1)
 ggridges               0.5.5      2023-12-15 [1] CRAN (R 4.3.1)
 globals                0.16.2     2022-11-21 [1] CRAN (R 4.3.0)
 glue                   1.7.0      2024-01-09 [1] CRAN (R 4.3.1)
 goftest                1.2-3      2021-10-07 [1] CRAN (R 4.3.0)
 gridExtra              2.3        2017-09-09 [1] CRAN (R 4.3.0)
 gtable                 0.3.4      2023-08-21 [1] CRAN (R 4.3.0)
 hdf5r                * 1.3.9      2024-01-14 [1] CRAN (R 4.3.1)
 Hmisc                  5.1-1      2023-09-12 [1] CRAN (R 4.3.0)
 hms                    1.1.3      2023-03-21 [1] CRAN (R 4.3.0)
 htmlTable              2.4.2      2023-10-29 [1] CRAN (R 4.3.1)
 htmltools              0.5.7      2023-11-03 [1] CRAN (R 4.3.1)
 htmlwidgets            1.6.4      2023-12-06 [1] CRAN (R 4.3.1)
 httpuv                 1.6.13     2023-12-06 [1] CRAN (R 4.3.1)
 httr                   1.4.7      2023-08-15 [1] CRAN (R 4.3.0)
 ica                    1.0-3      2022-07-08 [1] CRAN (R 4.3.0)
 igraph                 1.6.0      2023-12-11 [1] CRAN (R 4.3.1)
 IRanges              * 2.36.0     2023-10-26 [1] Bioconductor
 irlba                * 2.3.5.1    2022-10-03 [1] CRAN (R 4.3.0)
 jsonlite               1.8.8      2023-12-04 [1] CRAN (R 4.3.1)
 KEGGREST               1.42.0     2023-10-26 [1] Bioconductor
 KernSmooth             2.23-22    2023-07-10 [1] CRAN (R 4.3.2)
 knitr                  1.45       2023-10-30 [1] CRAN (R 4.3.1)
 labeling               0.4.3      2023-08-29 [1] CRAN (R 4.3.0)
 later                  1.3.2      2023-12-06 [1] CRAN (R 4.3.1)
 lattice                0.22-5     2023-10-24 [1] CRAN (R 4.3.1)
 lazyeval               0.2.2      2019-03-15 [1] CRAN (R 4.3.0)
 leiden                 0.4.3.1    2023-11-17 [1] CRAN (R 4.3.1)
 lifecycle              1.0.4      2023-11-07 [1] CRAN (R 4.3.1)
 listenv                0.9.0      2022-12-16 [1] CRAN (R 4.3.0)
 lmtest                 0.9-40     2022-03-21 [1] CRAN (R 4.3.0)
 magrittr               2.0.3      2022-03-30 [1] CRAN (R 4.3.0)
 MASS                   7.3-60.0.1 2024-01-13 [1] CRAN (R 4.3.1)
 Matrix               * 1.6-5      2024-01-11 [1] CRAN (R 4.3.1)
 MatrixGenerics         1.14.0     2023-10-26 [1] Bioconductor
 matrixStats            1.2.0      2023-12-11 [1] CRAN (R 4.3.1)
 memoise                2.0.1      2021-11-26 [1] CRAN (R 4.3.0)
 mime                   0.12       2021-09-28 [1] CRAN (R 4.3.0)
 miniUI                 0.1.1.1    2018-05-18 [1] CRAN (R 4.3.0)
 munsell                0.5.0      2018-06-12 [1] CRAN (R 4.3.0)
 nlme                   3.1-164    2023-11-27 [1] CRAN (R 4.3.1)
 nnet                   7.3-19     2023-05-03 [1] CRAN (R 4.3.2)
 parallelly             1.36.0     2023-05-26 [1] CRAN (R 4.3.0)
 patchwork            * 1.2.0      2024-01-08 [1] CRAN (R 4.3.1)
 pbapply                1.7-2      2023-06-27 [1] CRAN (R 4.3.0)
 pillar                 1.9.0      2023-03-22 [1] CRAN (R 4.3.0)
 pkgconfig              2.0.3      2019-09-22 [1] CRAN (R 4.3.0)
 plotly                 4.10.4     2024-01-13 [1] CRAN (R 4.3.1)
 plyr                   1.8.9      2023-10-02 [1] CRAN (R 4.3.1)
 png                    0.1-8      2022-11-29 [1] CRAN (R 4.3.0)
 polyclip               1.10-6     2023-09-27 [1] CRAN (R 4.3.1)
 prettyunits            1.2.0      2023-09-24 [1] CRAN (R 4.3.1)
 progress               1.2.3      2023-12-06 [1] CRAN (R 4.3.1)
 progressr              0.14.0     2023-08-10 [1] CRAN (R 4.3.0)
 promises               1.2.1      2023-08-10 [1] CRAN (R 4.3.0)
 ProtGenerics           1.34.0     2023-10-26 [1] Bioconductor
 purrr                  1.0.2      2023-08-10 [1] CRAN (R 4.3.0)
 R6                     2.5.1      2021-08-19 [1] CRAN (R 4.3.0)
 RANN                   2.6.1      2019-01-08 [1] CRAN (R 4.3.0)
 rappdirs               0.3.3      2021-01-31 [1] CRAN (R 4.3.0)
 RColorBrewer           1.1-3      2022-04-03 [1] CRAN (R 4.3.0)
 Rcpp                   1.0.12     2024-01-09 [1] CRAN (R 4.3.1)
 RcppAnnoy              0.0.21     2023-07-02 [1] CRAN (R 4.3.0)
 RcppHNSW               0.5.0      2023-09-19 [1] CRAN (R 4.3.1)
 RcppRoll               0.3.0      2018-06-05 [1] CRAN (R 4.3.0)
 RCurl                  1.98-1.14  2024-01-09 [1] CRAN (R 4.3.1)
 reshape2               1.4.4      2020-04-09 [1] CRAN (R 4.3.0)
 restfulr               0.0.15     2022-06-16 [1] CRAN (R 4.3.0)
 reticulate             1.34.0     2023-10-12 [1] CRAN (R 4.3.1)
 rjson                  0.2.21     2022-01-09 [1] CRAN (R 4.3.0)
 rlang                  1.1.3      2024-01-10 [1] CRAN (R 4.3.1)
 rmarkdown              2.25       2023-09-18 [1] CRAN (R 4.3.1)
 ROCR                   1.0-11     2020-05-02 [1] CRAN (R 4.3.0)
 rpart                  4.1.23     2023-12-05 [1] CRAN (R 4.3.1)
 Rsamtools              2.18.0     2023-10-26 [1] Bioconductor
 RSpectra               0.16-1     2022-04-24 [1] CRAN (R 4.3.0)
 RSQLite                2.3.4      2023-12-08 [1] CRAN (R 4.3.1)
 rstudioapi             0.15.0     2023-07-07 [1] CRAN (R 4.3.0)
 rtracklayer            1.62.0     2023-10-26 [1] Bioconductor
 Rtsne                  0.17       2023-12-07 [1] CRAN (R 4.3.1)
 S4Arrays               1.2.0      2023-10-26 [1] Bioconductor
 S4Vectors            * 0.40.2     2023-11-25 [1] Bioconductor 3.18 (R 4.3.2)
 scales                 1.3.0      2023-11-28 [1] CRAN (R 4.3.1)
 scattermore            1.2        2023-06-12 [1] CRAN (R 4.3.0)
 sctransform            0.4.1      2023-10-19 [1] CRAN (R 4.3.1)
 sessioninfo            1.2.2      2021-12-06 [1] CRAN (R 4.3.0)
 Seurat               * 5.0.1      2023-11-17 [1] CRAN (R 4.3.1)
 SeuratObject         * 5.0.1      2023-11-17 [1] CRAN (R 4.3.2)
 shiny                  1.8.0      2023-11-17 [1] CRAN (R 4.3.1)
 Signac               * 1.12.9004  2024-01-18 [1] Github (stuart-lab/signac@0c43d88)
 sp                   * 2.1-2      2023-11-26 [1] CRAN (R 4.3.1)
 spam                   2.10-0     2023-10-23 [1] CRAN (R 4.3.1)
 SparseArray            1.2.3      2023-12-26 [1] Bioconductor 3.18 (R 4.3.2)
 spatstat.data        * 3.0-4      2024-01-15 [1] CRAN (R 4.3.1)
 spatstat.explore       3.2-5      2023-10-22 [1] CRAN (R 4.3.1)
 spatstat.geom        * 3.2-7      2023-10-20 [1] CRAN (R 4.3.1)
 spatstat.random        3.2-2      2023-11-29 [1] CRAN (R 4.3.1)
 spatstat.sparse        3.0-3      2023-10-24 [1] CRAN (R 4.3.1)
 spatstat.utils         3.0-4      2023-10-24 [1] CRAN (R 4.3.1)
 stringi                1.8.3      2023-12-11 [1] CRAN (R 4.3.1)
 stringr                1.5.1      2023-11-14 [1] CRAN (R 4.3.1)
 SummarizedExperiment   1.32.0     2023-11-06 [1] Bioconductor
 survival               3.5-7      2023-08-14 [1] CRAN (R 4.3.2)
 tensor                 1.5        2012-05-05 [1] CRAN (R 4.3.0)
 tibble                 3.2.1      2023-03-20 [1] CRAN (R 4.3.0)
 tidyr                  1.3.0      2023-01-24 [1] CRAN (R 4.3.0)
 tidyselect             1.2.0      2022-10-10 [1] CRAN (R 4.3.0)
 utf8                   1.2.4      2023-10-22 [1] CRAN (R 4.3.1)
 uwot                   0.1.16     2023-06-29 [1] CRAN (R 4.3.0)
 VariantAnnotation      1.48.1     2023-11-18 [1] Bioconductor 3.18 (R 4.3.2)
 vctrs                  0.6.5      2023-12-01 [1] CRAN (R 4.3.1)
 viridisLite            0.4.2      2023-05-02 [1] CRAN (R 4.3.0)
 withr                  3.0.0      2024-01-16 [1] CRAN (R 4.3.1)
 xfun                   0.41       2023-11-01 [1] CRAN (R 4.3.1)
 XML                    3.99-0.16  2023-11-29 [1] CRAN (R 4.3.1)
 xml2                   1.3.6      2023-12-04 [1] CRAN (R 4.3.1)
 xtable                 1.8-4      2019-04-21 [1] CRAN (R 4.3.0)
 XVector                0.42.0     2023-10-26 [1] Bioconductor
 yaml                   2.3.8      2023-12-11 [1] CRAN (R 4.3.1)
 zlibbioc               1.48.0     2023-10-26 [1] Bioconductor
 zoo                    1.8-12     2023-04-13 [1] CRAN (R 4.3.0)

**Comment by timoast** [comment]
Please see https://github.com/stuart-lab/signac/issues/1596

**Comment by realmungmung** [comment]
downloaded GNU Fortran compiler from https://mac.r-project.org/tools/ to help installing irlba
