### ISSUE TITLE
Error in AddMotifs!

### ISSUE THREAD

**Issue by ZivTQ** [stuart-lab/signac#1606]
Hi,
I'm so sorry to bother you! I met some problems in runing Signa.
All of the previous steps are well. However, I met errors in AddMotifs!

Here is the codes and errors:
```r
Idents(sce_ATAC) <- sce_ATAC$AnnotatedcellType
DefaultAssay(sce_ATAC) <- "Peaks"
library(BSgenome.Hsapiens.UCSC.hg38)
library(TFBSTools)
library(JASPAR2020)

library(chromVARmotifs)
data("human_pwms_v2")

sce_ATAC <- AddMotifs(
  object = sce_ATAC,
  genome = BSgenome.Hsapiens.UCSC.hg38,
  pfm = human_pwms_v2,
  assay = "Peaks"
)


Building motif matrix
Warning in CreateMotifMatrix(features = object, pwm = pfm, genome = genome,  :
  Not all seqlevels present in supplied genome
Error in fixupDN.if.valid(value, x@Dim) : 
  length of Dimnames[[1]] (1) is not equal to Dim[1] (0)
In addition: Warning message:
In .merge_two_Seqinfo_objects(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
```

I changed the PFM, but I get the same errors:

```r
`PFM = getMatrixSet(x = JASPAR2020, opts = list(collection = "CORE", 
                                               tax_group = 'vertebrates', 
                                               ll_versions = FALSE, species = "Homo sapiens"))
sce_ATAC <- AddMotifs(
  object = sce_ATAC,
  genome = BSgenome.Hsapiens.UCSC.hg38,
  pfm = PFM,
  assay = "Peaks"
)
```

I am looking forward to your help!
Thank you very much!

**Comment by ZivTQ** [comment]
> The message here `The 2 combined objects have no sequence levels in common` suggests that the chromosome names are not matching in your peaks and the BSgenome object. Can you show the output of `head(rownames(sce_ATAC))`?

Thanks for your reply.
`head(rownames(sce_ATAC))

[1] "1-10027-10346"   "1-180552-181055" "1-181268-181581" "1-191278-191522"
[5] "1-267872-268084" "1-629087-629302"
`

**Comment by timoast** [comment]
So they are in the NCBI format rather than UCSC, you would need to change the seqnames of the BSgenome that you're using so that they match.

For example: `seqlevelsStyle(BSgenome.Hsapiens.UCSC.hg38) <- "NCBI"`

**Comment by ZivTQ** [comment]
> So they are in the NCBI format rather than UCSC, you would need to change the seqnames of the BSgenome that you're using so that they match.
> 
> For example: `seqlevelsStyle(BSgenome.Hsapiens.UCSC.hg38) <- "NCBI"`

Thank you. My problem was solved.
I'm sorry for my ignorance!

With best wishes
