### ISSUE TITLE
Discrepancy in my data versus following PBMC Tutorial

### ISSUE THREAD

**Issue by carversh** [stuart-lab/signac#1613]
Hi, I am following the PBMC tutorial and running into an error. Overall it appears that the peak_region_fragments isn't being automatically created when I read in my data, but this occurs in the PBMC tutorial.

```
# reading in processed atac matrix
m <- readMM(file='snATAC_counts.mtx')
# coerce the matrix or data frame to numeric type 
m = m*1
# creating barcode and feature labels
barcodes <- fread(file='barcodes_atac.csv', header=F)[[1]]
features <- fread(file='peaks.csv', header=F)[[1]]
# adding these feature and barcode names to the matrix
rownames(m) <- features
colnames(m) <- barcodes
# Create Seurat Chromatin Assay
chrom_assay <- CreateChromatinAssay(
    counts = m,
    sep = c(":", "-"),
    fragments = 'fragments.tsv.gz',
    min.cells = 0,
    min.features = 0
)
# read in metadata
metadata <- read.csv(
  file = "metadata.csv",
  header = TRUE,
  row.names = 12
)

# create seurat object from chrom_assay
ATAC <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = metadata
)

# Subset the Seurat object based on metadata barcodes
ATAC <- subset(ATAC, cells = rownames(metadata))

ATAC
```
ChromatinAssay data with 227255 features for 130418 cells
Variable features: 0 
Genome: 
Annotation present: FALSE 
Motifs present: FALSE 
Fragment files: 1 
```
ATAC[['peaks']]
```
ChromatinAssay data with 227255 features for 130418 cells
Variable features: 0 
Genome: 
Annotation present: FALSE 
Motifs present: FALSE 
Fragment files: 1 
```
granges(ATAC)
```
GRanges object with 227255 ranges and 0 metadata columns:
           seqnames            ranges strand
              <Rle>         <IRanges>  <Rle>
       [1]     chr1     190840-191925      *
       [2]     chr1     629708-630559      *
       [3]     chr1     631640-631957      *
       [4]     chr1     632495-633098      *
       [5]     chr1     633741-634673      *
       ...      ...               ...    ...
  [227251]     chrY 56867602-56868075      *
  [227252]     chrY 56868639-56874760      *
  [227253]     chrY 56876006-56876385      *
  [227254]     chrY 56877531-56877939      *
  [227255]     chrY 56879496-56880556      *
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths
```
# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)

seqlevels(annotations) <- paste0('chr', seqlevels(annotations))

# change to UCSC style since the data was mapped to hg19
genome(annotations) <- "hg38"
```
Warning message in .merge_two_Seqinfo_objects(x, y):
"The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)"
Warning message in .merge_two_Seqinfo_objects(x, y):
"The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)"
Warning message in .merge_two_Seqinfo_objects(x, y):
"The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)"
Warning message in .merge_two_Seqinfo_objects(x, y):
"The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)"
Warning message in .merge_two_Seqinfo_objects(x, y):
"The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)"
Warning message in .merge_two_Seqinfo_objects(x, y):
"The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)"
Warning message in .merge_two_Seqinfo_objects(x, y):
"The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)"
Warning message in .merge_two_Seqinfo_objects(x, y):
"The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)"
Warning message in .merge_two_Seqinfo_objects(x, y):
...
  suppressWarnings() to suppress this warning.)"
Warning message in .merge_two_Seqinfo_objects(x, y):
"The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)"

```
# add the gene information to the object
Annotation(ATAC) <- annotations

# compute nucleosome signal score per cell
ATAC <- NucleosomeSignal(object = ATAC)

# compute TSS enrichment score per cell
ATAC <- TSSEnrichment(object = ATAC, fast = TRUE)
```
Error in `x[[i, drop = TRUE]]`:
! 'peak_region_fragments' not found in this Seurat object
 
Traceback:

1. ATAC$peak_region_fragments
2. `$.Seurat`(ATAC, peak_region_fragments)
3. x[[i, drop = TRUE]]
4. `[[.Seurat`(x, i, drop = TRUE)
5. tryCatch(expr = arg_match(arg = i, values = meta.cols, multiple = TRUE), 
 .     error = function(e) {
 .         abort(message = paste(paste(sQuote(x = setdiff(x = i, 
 .             y = meta.cols)), collapse = ", "), "not found in this Seurat object\n", 
 .             e$body), call = rlang::caller_env(n = 4L))
 .     })
6. tryCatchList(expr, classes, parentenv, handlers)
7. tryCatchOne(expr, names, parentenv, handlers[[1L]])
8. value[[3L]](cond)
9. abort(message = paste(paste(sQuote(x = setdiff(x = i, y = meta.cols)), 
 .     collapse = ", "), "not found in this Seurat object\n", e$body), 
 .     call = rlang::caller_env(n = 4L))
10. signal_abort(cnd, .file)

**Comment by timoast** [comment]
`peak_region_fragments` is part of the cellranger metadata and is not something that is computed by Signac. If this was not in the metadata that you added, then it's expected that it won't be a part of the object.
