### ISSUE TITLE
Performing TF footprinting based on a specific motif and on a set of peaks? 

### ISSUE THREAD

**Issue by Amalia-N-C** [stuart-lab/signac#1615]
Hi,

Thanks for making Seurat and Signac available for anyone to use! It makes single-cell seq analysis accessible, even for beginners. 

Recently I performed differential accessible peak analysis and motif enrichment on peaks that were found to be differentially accessible. I was wondering if transcription factor footprinting could be done on only the sets of peaks that were found to be differentially accessible and only looking at motifs that were detected through motif enrichment. 

I tried to supply both motifs and regions to the footprint function like so:

bone <- [Footprint](https://stuartlab.org/signac/reference/footprint)(
  object = bone,
  motif.name = [c](https://rdrr.io/r/base/c.html)("GATA2", "CEBPA", "EBF1"),
  genome = BSgenome.Hsapiens.UCSC.hg19,
  regions = sig.diff.region
)

but I got the following error: 

Error in Footprint.ChromatinAssay(object = object[[assay]], regions = regions,  : 
  Supplied both a motif name and set of regions. Choose one only.

Is it not advised to do this? I am looking for a way to graphically show the results of the motif enrichment analysis. 

Thanks!

**Comment by timoast** [comment]
Hi @Amalia-N-C 

That is correct, you can only supply either the names of motifs to footprint of a set of regions. If you want to use motifs only present in a certain set of peaks, you would need to manually specify what those regions are and supply them using the `regions` parameter in `Footprint()`
