### ISSUE TITLE
Get an error when running TSSPlot

### ISSUE THREAD

**Issue by pobmmu** [stuart-lab/signac#1618]
I am trying to plot the TSS enrichment but even though the TSSEnrichment function ran normally, the TSSplot function is always returning an error. 

Error in TSSPlot(combined, assay = "ATAC") : 
  Position enrichment matrix not present in assay

**Comment by timoast** [comment]
You need to first run `TSSEnrichment()` with `fast=FALSE`

**Comment by pobmmu** [comment]
When I run the TSSEnrichment(object, fast=FALSE), I get:

_Extracting TSS positions
Finding + strand cut sites
Finding - strand cut sites
Computing mean insertion frequency in flanking regions
Normalizing TSS score
Error in slot(object = object, name = layer) : 
  argument "slot" is missing, with no default_

My object is a seurat object with 2 integrated dataset with 4 assays = RNA, ATAC, SCT and integrated. My default assay is set to ATAC.

**Comment by timoast** [comment]
Please see https://github.com/stuart-lab/signac/issues/1538
