### ISSUE TITLE
Pseudo bulking of clusters generated with signac-pipeline

### ISSUE THREAD

**Issue by hesbornomwandho** [stuart-lab/signac#1623]
Hello,
i want to generate .bam files for each cluster generated by signac and use it for down stream analysis(calling enhancers and super-enhancers for the clusters). Any suggestions

**Comment by timoast** [comment]
You can try this: https://github.com/timoast/sinto

**Comment by wdg118** [comment]
Hi @timoast ,

How can you convert a fragment file back to a BAM file using Sinto? It seems Sinto only converts BAM files to fragment files. I need BAM files for deepTools. 

Thanks!
