### ISSUE TITLE
Issue Analyzing scATAC data with NCBI genome

### ISSUE THREAD

**Issue by nic-ghub2** [stuart-lab/signac#1627]
Hi, 

I am trying to analyze a scATAC dataset I have that was created using an NCBI genome. I am having issues creating the 'annotation' in the step below: 

`extract gene annotations from EnsDb
annotations <- [GetGRangesFromEnsDb](https://stuartlab.org/signac/reference/getgrangesfromensdb)(ensdb = EnsDb.Hsapiens.v75)

change to UCSC style since the data was mapped to hg19
[seqlevels](https://stuartlab.org/signac/reference/seqinfo-methods)(annotations) <- [paste0](https://rdrr.io/r/base/paste.html)('chr', [seqlevels](https://stuartlab.org/signac/reference/seqinfo-methods)(annotations))
[genome](https://stuartlab.org/signac/reference/seqinfo-methods)(annotations) <- "hg19"`

Could you direct me to the way I could extract gene annotations from an NCBI gtf file? It seems like only currently ensembl genomes are shown in the vignettes and I cannot find a way to input NCBI annotations. 

Thank you for all your help!!

**Comment by timoast** [comment]
If your data is mapped to NCBI, skip the step that converts the chromosomes to UCSC style. The annotations are already in NCBI format

**Comment by nic-ghub2** [comment]
Thanks! I am more confused on the first step, where it says "extract gene annotations from EnsDb". I am confused on how to provide my NCBI genome because i cant create an ensembl database from it
