### ISSUE TITLE
How to Provide NCBI genome for annotation

### ISSUE THREAD

**Issue by nic-ghub2** [stuart-lab/signac#1631]
Hello,

I am having issues figuring out how to provide an NCBI genome to create the annoatation in the step below:

`extract gene annotations from EnsDb
annotations <- [GetGRangesFromEnsDb](https://stuartlab.org/signac/reference/getgrangesfromensdb)(ensdb = EnsDb.Hsapiens.v75)

Could you direct me to the way I could extract gene annotations from an NCBI gtf file?

Thank you

**Comment by timoast** [comment]
The annotations are already in NCBI format, you don't need to do anything. You can check the format by running the `seqlevelStyle()` function:

```
> seqlevelsStyle(annotations)
[1] "NCBI"
```
