### ISSUE TITLE
LinkPeaks error argument 'x' must be numeric

### ISSUE THREAD

**Issue by hannahvanm** [stuart-lab/signac#1633]
Hi there, 

Thanks again for this great package. I'm working on integrated multiome samples. I'm trying to use LinkPeaks using the following code. 
```
T20_T24_multiome_linkpeaks <- LinkPeaks(
  object = T20_T24_multiome_linkpeaks,
  peak.assay = "ATAC",
  expression.assay = "RNA"
  )
```
Here's the error that comes back: 
```
Testing 13413 genes and 124802 peaks Found gene coordinates for 11633 genes 0 % ~calculating 
Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian",  : 
  argument 'x' must be numeric
```
I used forgeBSgenomeDataPkgFromNCBI to forge the genome for the RegionStats step prior to this, using the same NCBI genome that I used for the Chromatin assay, so both the object and the BSgenome should be NCBI format- which seemed to the problem in a similar error (#1109) 

However, it does seem that there could be a mismatch occurring, as this is a separate error occurring when I try to use AddMotifs, but I'm not sure how/ why. 
```
Not all seqlevels present in supplied genome Warning: The 2 combined objects have no sequence levels in common. (Use suppressWarnings() to suppress this warning.)
Error in fixupDN.if.valid(value, x@Dim) : length of Dimnames[[1]] (1) is not equal to Dim[1] (0)
```
Any guidence is greatly appreciated. 

Session Info: 
[multiome_session_info.txt](https://github.com/stuart-lab/signac/files/14366714/multiome_session_info.txt)

**Comment by timoast** [comment]
My guess is that the chromosome names in the genome that you provide do not match the chromosome names in your peaks, and so the DNA sequences of the peaks cannot be retrieved. Can you show the seqnames of the genome object you're using and the first few peaks in your dataset?

**Comment by hannahvanm** [comment]
Ah yes, that is the case. I tried changing both the genome and the peaks chr names (after what's seen in these screenshots) using seqlevelsStyle(x) <- NCBI , but they still didn't match. Is this something you would change manually using a different approach? Thanks for your help! 

<img width="667" alt="Screenshot 2024-02-22 at 10 09 42 AM" src="https://github.com/stuart-lab/signac/assets/101760761/8f1f6cd1-99ea-4dcd-9c7c-579bb7475461">


<img width="550" alt="Screenshot 2024-02-22 at 10 23 02 AM" src="https://github.com/stuart-lab/signac/assets/101760761/ff268600-5d7f-42f9-896d-1ff7450517d3">

**Comment by timoast** [comment]
You need to change the seqlevelStyle of the BSgenome to UCSC

**Comment by skkanlei** [comment]
I change the seqlevelStyle to UCSC, but I also meet the same error。

macs2_counts <- FeatureMatrix(
  fragments = Fragments(rds),
  features = peaks,
  cells = colnames(rds)
)

head(annotations)
seqlevelsStyle(annotations) <- "UCSC"
rds[["peaks"]] <- CreateChromatinAssay(
  counts = macs2_counts,
  sep = c(":", "-"),
  annotation = annotations,
  genome = "bosTau9"
)

DefaultAssay(rds) <- "peaks"

rds1 <- LinkPeaks(
  object = rds1,
  peak.assay = "peaks",
  expression.assay = "ACTIVITY",
  genes.use = c("SOX9"),
  verbose = T
)

> Testing 1 genes and 206397 peaks
>   |                                                  | 0 % ~calculating  Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian",  : 
>   argument 'x' must be numeric

**Comment by skkanlei** [comment]
![image](https://github.com/stuart-lab/signac/assets/155239917/3449edb3-2c59-4a13-bea9-418f3fe6db1e)
![image](https://github.com/stuart-lab/signac/assets/155239917/d205c516-dee3-47fa-b7f3-1abeaad37c9a)

**Comment by timoast** [comment]
Can you run from the beginning in a fresh R session? If you already ran RegionStats once with the wrong genome that might cause issues

**Comment by hannahvanm** [comment]
Hi there, I havn't been able to change the seqlevelStyle of the forged genome. Here's what I ran + the  warning. 
`seqlevelsStyle(BSgenome.Pmarinus.NCBI.kPetMar1.pri) <- "UCSC"`
`Warning: cannot switch kPetMar1.pri's seqlevels to UCSC style`

After this command, the chromosome names looks the same. 

<img width="642" alt="Screenshot 2024-02-29 at 1 27 14 PM" src="https://github.com/stuart-lab/signac/assets/101760761/ff437327-fcc5-43a8-8b54-fb26efcdbe4a">

**Comment by timoast** [comment]
@hannahvanm check the [renameSeqlevels](https://rdrr.io/bioc/GenomeInfoDb/man/seqlevels-wrappers.html) function to see how to manually change the seqlevels
