### ISSUE TITLE
 After CreateChromatinAssay, my chrom_assay@ranges@seqinfo slot is NA

### ISSUE THREAD

**Issue by skkanlei** [stuart-lab/signac#1635]
So sorry to trouble you again!
My session is the same as above. 
My code is 

I am creating a seurat object using signac 1.11.0
My data aligned to ensembl - ARS-UCD1.2

gtffile <- "/home/yulab1/QiXin/reference/Bos_taurus.ARS-UCD1.2.110.filtered.gtf"
#generate the SQLite database file
DB <- ensDbFromGtf(gtf = gtffile)
#load the DB file directly
EDB <- EnsDb(DB)
annotations <- GetGRangesFromEnsDb(EDB)

t131_new <- Read10X(data.dir ="/home/QiXin/cattle_raw/13T2/filtered_feature_bc_matrix/")
atac_t13_new <- t131_new$Peaks
load("combined_peaks.rdata")

frag.file <- "/home/QiXin/cattle_raw/13T2/atac_fragments.tsv.gz"

fragmentdata <- CreateFragmentObject(
  path = frag.file,
  cells = colnames(atac_t13_new)
)

counts_t13_new <- FeatureMatrix(
  fragments = fragmentdata,
  features = combined.peaks,
  cells = colnames(atac_t13_new)
)

chrom_assay_t13_new <- CreateChromatinAssay(
  counts = counts_t13_new,
  sep = c(":", "-"),
  fragments = frag.file,
  min.cells = 10,
  genome = "ARS-UCD1.2"
)

t13_new <- CreateSeuratObject(chrom_assay_t13_new, project = "t13", assay = "ATAC")
Annotation(t13_new) <- annotations
t13_new <- RenameCells(t13_new, add.cell.id="t13")

rdslist <- list(d4,t3,t13,t13_new)
rds <- rdslist[[1]]
for(i in 2:length(rdslist)){
  rds <- merge(rds, rdslist[[i]])
}

rds <- NucleosomeSignal(object = rds)
rds <- TSSEnrichment(object = rds, fast = FALSE)
peaks <- CallPeaks(
  object = rds,
  group.by = "orig.ident",
  outdir = "/home/QiXin/cattle_raw/",
  macs2.path = "/home/QiXin/.conda/envs/python39/bin/macs2",
  effective.genome.size = 2.7e+09
)

macs2_counts <- FeatureMatrix(
  fragments = Fragments(rds),
  features = peaks,
  cells = colnames(rds)
)

rds[["peaks"]] <- CreateChromatinAssay(
  counts = macs2_counts,
  sep = c(":", "-"),
  annotation = annotations,
  genome = "ARS-UCD1.2"
)

DefaultAssay(rds) <- "peaks"
rds <- RegionStats(rds, genome = BSgenome.Btaurus.UCSC.bosTau9)

And the NA is like this
>rds@assays$ATAC@ranges@seqinfo
Seqinfo object with 72 sequences from an unspecified genome; no seqlengths:
  seqnames       seqlengths isCircular genome
  1                    <NA>       <NA>   <NA>
  2                    <NA>       <NA>   <NA>
  3                    <NA>       <NA>   <NA>
  4                    <NA>       <NA>   <NA>
  5                    <NA>       <NA>   <NA>
  ...                   ...        ...    ...
  NKLS02002203.1       <NA>       <NA>   <NA>
  NKLS02002206.1       <NA>       <NA>   <NA>
  NKLS02002207.1       <NA>       <NA>   <NA>
  NKLS02002208.1       <NA>       <NA>   <NA>
  NKLS02002210.1       <NA>       <NA>   <NA>

And after CallPeaks, the result still has NA.

> head(rds[['peaks']][[]])
                AA AC AG AT CA CC CG CT GA GC GG GT TA TC TG TT GC.percent sequence.length
1-247351-247701 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA         NA             351
1-266349-266644 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA         NA             296
1-278429-279005 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA         NA             577
1-329519-330023 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA         NA             505
1-332343-332720 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA         NA             378
1-336342-336716 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA         NA             375

Thank you very much!

_Originally posted by @skkanlei in https://github.com/stuart-lab/signac/issues/1634#issuecomment-1961244474_

**Comment by skkanlei** [comment]
rds@assays$ATAC@ranges@seqinfo
Seqinfo object with 72 sequences from an unspecified genome; no seqlengths:
seqnames       seqlengths isCircular genome
1                       NA             NA            NA

**Comment by skkanlei** [comment]
And I want to know if I want to run RegionStats without BSgenome, I want to use my annotations
What should I do ?

**Comment by timoast** [comment]
So your issue is that the dinucleotide frequencies computed by the `RegionStats` function are `NA`.

This most likely happens because the BSgenome you are using has different chromosome naming to the chromosomes that your data are mapped to. You said that you mapped to the Ensembl genome but are using the UCSC BSgenome object here. They will likely have different naming conventions. Please check in your data and alter the seqlevelStyle in the BSgenome object accordingly.

You most likely see a warning message appear when running `RegionStats` stating that not all the seqlevels are present in the supplied genome.

> And I want to know if I want to run RegionStats without BSgenome, I want to use my annotations

This function requires a genome sequence not gene annotations.

**Comment by skkanlei** [comment]
> So your issue is that the dinucleotide frequencies computed by the `RegionStats` function are `NA`.
> 
> This most likely happens because the BSgenome you are using has different chromosome naming to the chromosomes that your data are mapped to. You said that you mapped to the Ensembl genome but are using the UCSC BSgenome object here. They will likely have different naming conventions. Please check in your data and alter the seqlevelStyle in the BSgenome object accordingly.
> 
> You most likely see a warning message appear when running `RegionStats` stating that not all the seqlevels are present in the supplied genome.
> 
> > And I want to know if I want to run RegionStats without BSgenome, I want to use my annotations
> 
> This function requires a genome sequence not gene annotations.

Thank you for your reply, I solved my question by changing BSgenome(seqlevelsStyle(BSgenome) <- "ensembl")
