### ISSUE TITLE
Issue on installation: object ‘LayerData<-’ is not exported by 'namespace:SeuratObject'

### ISSUE THREAD

**Issue by yurasong** [stuart-lab/signac#1636]
Dear,

I am facing the error while installation, the message is as below.

```
Error: object ‘LayerData<-’ is not exported by 'namespace:SeuratObject'
Execution halted
ERROR: lazy loading failed for package ‘Signac’
``` 

Environment is as below.
- MacOS 14.1.2 (23B92)
- R: R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
- Seurat 4.4.0
- SeuratObject 4.1.4

For your information, when I have installed on Linux (Ubuntu 18.04 with R version 4.3.0, Seurat 4.4.0) did not face same issue. 

Thanks in advance!

**Comment by timoast** [comment]
You need to update SeuratObject to v5. We will increase the SeuratObject version requirement in the dependencies soon
