### ISSUE TITLE
TSSEnrichment Error

### ISSUE THREAD

**Issue by nic-ghub2** [stuart-lab/signac#1640]
Hello,

I am running into this error:` "Error: logical subscript contains NAs"` when trying to run TSSEnrichment on my sample.

I created an annotation using:

```
annotation <- rtracklayer::import("/path/to/gtffile.gtf")
genome(annotation) <- "kf"
annotation$gene_name <- annotation$gene
Annotation(multiome) <- annotation
```

When I look at head(Annotation(multiome)):

![Screenshot 2024-02-26 at 11 50 37 AM](https://github.com/stuart-lab/signac/assets/160288302/d64a4841-746e-4026-8588-b052bda33d2b)

When I look at head(Fragments(multiome)[[1]]):
![Screenshot 2024-02-26 at 11 50 55 AM](https://github.com/stuart-lab/signac/assets/160288302/72495bab-3718-4916-8403-dbe4985d4be3)

The chrom  names are matching the seqnames so I am confused why I am having this error.. Is it because there are NAs for gene_biotype?

Additionally, when I look at `seqlevelsStyle(annotation)`, I get:
`[1] "RefSeq"`

But this gtf is from NCBI - when I try to run `seqlevelsStyle(annotation) <- 'NCBI'`, I get

Error in .replace_seqlevels_style(x_seqlevels, value) :
found no sequence renaming map compatible with seqname style "NCBI" for this object

Thank you!

**Comment by nic-ghub2** [comment]
I also added annotation$tx_id <- annotation$transcript_id but still having the same issue

**Comment by timoast** [comment]
My guess is it's because your gene biotypes contain NAs. Try removing those and see if it solves your issue

**Comment by nic-ghub2** [comment]
Thank you! It is able to run now, but the TSSEnrichment graph is completely empty:
<img width="1440" alt="Screenshot 2024-02-27 at 10 31 04 AM" src="https://github.com/stuart-lab/signac/assets/160288302/81671faf-2ca2-4e4d-a8ed-22d72ce0296d">

Do you have any troubleshooting tips? Thanks!
