### ISSUE TITLE
Get error when running FindMotifs with >102 peaks set for features=

### ISSUE THREAD

**Issue by yanc0828** [stuart-lab/signac#1643]
When I tried to run motif analysis on single-cell ATAC-seq data, I got this error message when running FindMotifs:

              Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian",  : 
                'x' contains missing values

I think the issue is due to the size of peaks used as features= in FindMotifs(). When there are <=102 peaks, I did not get this error. When there are >102 peaks, the error appeared. 

Here is the code I used when running into this error:
```r
da_peaks <- FindMarkers(
  object = my.data,
  ident.1 = identity1,
  ident.2 = identity2
  only.pos = TRUE,
  test.use = 'LR',
  min.pct = 0.05,
  latent.vars = count.of.peaks)

top.da.peak <- rownames(da_peaks[da_peaks$p_val < 0.005, ]) 

enriched.motifs <- FindMotifs(
  object = my.data,
  features = top.da.peak
)
```

**Comment by BartBryant** [comment]
@yanc0828 
i am having similar issue with 'FindMotifs(  )' fxn with error 'error in density...' how did you resolve it?

**Comment by yanc0828** [comment]
@BartBryant 
The reason why I got that error message was that the 103rd peak was with a position that does not start with "chr". After I filtered out peaks with positions that don't start with "chr", it worked.

**Comment by BartBryant** [comment]
@yanc0828 
i did the code below to filter rows that did not start with 'chr', this got the correct object to feed into



#according to Github, one user had issue with an observation/row 
#not having 'chr'
# Filter rows where row names start with 'chr'
filtered_da_peaks <- da_peaks[grepl("^chr", row.names(da_peaks)), ]

#this yields an object from 39334 to 39308
#so try again 
# get top differentially accessible peaks
top.da.peak <- rownames(filtered_da_peaks[filtered_da_peaks$p_val < 0.005, ])

# test enrichment
enriched.motifs <- FindMotifs(
  object = AVF,
  features = top.da.peak
)
<img width="1512" alt="Screenshot 2024-04-01 at 11 39 56 AM" src="https://github.com/stuart-lab/signac/assets/135715545/6efb455e-f4bd-4cf7-ab45-c4a8f3617864">
![Screenshot 2024-04-01 at 11 39 56 AM (2)](https://github.com/stuart-lab/signac/assets/135715545/51ce60cf-1f1b-4c71-81f1-31b29762236b)

**Comment by yanc0828** [comment]
Yeah, I used the similar code like yours to filter out the peaks
