### ISSUE TITLE
Issue on installation: object ‘LayerData<-’ is not exported by 'namespace:SeuratObject'

### ISSUE THREAD

**Issue by Syayaq** [stuart-lab/signac#1649]
Hi,

I am facing the error while installation, the message is as below.

> library(Signac)
错误: package or namespace load failed for ‘Signac’:
 'namespace:SeuratObject'没有出口‘LayerData<-’这个对象

Environment is as below.

R: R version 4.3.2
Seurat 4.4.0
SeuratObject 4.1.4

I hope to use Seurat V4,so can I use the appropriate version of signac without updating SeuratObject to v5?And which version of signac should I choose?

Thanks in advance!

**Comment by timoast** [comment]
Please see https://github.com/stuart-lab/signac/issues/1636
