### ISSUE TITLE
Directly mapping ATAC to RNA data [analysis question]

### ISSUE THREAD

**Issue by jgarces02** [stuart-lab/signac#1652]
Hi, 

I've got a dataset with simultaneous ATAC and RNA from the same cell ([multiome kit](https://www.10xgenomics.com/products/single-cell-multiome-atac-plus-gene-expression)). I was following [the tutorial](https://stuartlab.org/signac/articles/pbmc_vignette.html#integrating-with-scrna-seq-data) and got the following question: I started the analysis only with RNA data and performed the annotation according to it. For transferring it to the ATAC data, could it be enough just to match the cell IDs from my RNA to the ATAC data instead of using the [FindTransferAnchors](https://stuartlab.org/signac/articles/pbmc_vignette.html#integrating-with-scrna-seq-data) function?

Thanks a lot.

**Comment by timoast** [comment]
Yes, for multiome there's no need to do RNA/ATAC integration. If you've already annotated the cells using the RNA assay, the cells are the same so no need to try to annotate the ATAC assay separately.
