### ISSUE TITLE
scRNAseq data import without .h5 file

### ISSUE THREAD

**Issue by BartBryant** [stuart-lab/signac#1663]
hello signac

I have multiome (scATACseq and scRNAseq) data and your tutorials use the .h5 file. Can we use the three files (barcodes, matrix, features) instead? If so, how?

thx
barT

**Comment by timoast** [comment]
Please see the section "What if I don’t have an H5 file?" in the [PBMC vignette](https://stuartlab.org/signac/articles/pbmc_vignette)
