### ISSUE TITLE
issue with 'CreateSeuratObject(  ),'error in counts$'Gene Expression'

### ISSUE THREAD

**Issue by BartBryant** [stuart-lab/signac#1664]
I am following Signac multiomic tutorial
https://stuartlab.org/signac/articles/pbmc_multiomic

I have loaded my .h5 data for scRNAseq and path to my scATACseq with 'fragpath'

with the CreateSeuratObject( ) getting issue below 

# create a Seurat object containing the RNA adata
AVF <- CreateSeuratObject(
  counts = counts$`Gene Expression`,
  assay = "RNA"
)

#Error in counts$`Gene Expression` : 
#  $ operator not defined for this S4 class

suggestions to rectify?
thx for help,
barT
<img width="1512" alt="Screenshot 2024-03-23 at 9 36 38 AM" src="https://github.com/stuart-lab/signac/assets/135715545/dd1fe449-3728-47f6-bb50-c621c742db58">

**Comment by timoast** [comment]
The matrix you have here is just a count matrix (only one modality). If you have run a multiome experiment, you should read the h5 file to obtain both the RNA and ATAC count matrices as is shown in the vignette.

**Comment by BartBryant** [comment]
thanks for the clarification, 

and thanks for keeping Signac updated as I have struggled with other R packages for scATACseq which are not maintained and run on older Seurat and R versions.
