### ISSUE TITLE
FindMotifs( ) error, 'Error in density.default(x=query.feature[[featmatch]], kernel=......'

### ISSUE THREAD

**Issue by BartBryant** [stuart-lab/signac#1666]
Have error when running 'FindMotifs(  )'
Specifically, getting below error

enriched.motifs <- FindMotifs(
+   object = AVF,
+   features = top.da.peak
+ )
Selecting background regions to match input sequence characteristics
Matching GC.percent distribution
Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian",  : 
  'x' contains missing values

thanks for the help

<img width="1512" alt="Screenshot 2024-03-28 at 4 35 05 PM" src="https://github.com/stuart-lab/signac/assets/135715545/e420eb03-d97a-4af4-9d82-74238f44cac8">

**Comment by BartBryant** [comment]
additional info:  
i also checked the genome working with (mm10)

<img width="1512" alt="Screenshot 2024-03-28 at 4 44 44 PM" src="https://github.com/stuart-lab/signac/assets/135715545/5d5e18a4-ce18-4208-a191-9b6b20f4a671">

**Comment by BartBryant** [comment]
All 

I used the following code, for those that might have this issue

#according to Github, one user had issue with an observation/row 
#not having 'chr'
# Filter rows where row names start with 'chr'
filtered_da_peaks <- da_peaks[grepl("^chr", row.names(da_peaks)), ]

#this yields an object from 39334 to 39308
#so try again 
# get top differentially accessible peaks
top.da.peak <- rownames(filtered_da_peaks[filtered_da_peaks$p_val < 0.005, ])

# test enrichment
enriched.motifs <- FindMotifs(
  object = AVF,
  features = top.da.peak
)

<img width="1512" alt="Screenshot 2024-04-01 at 11 41 54 AM" src="https://github.com/stuart-lab/signac/assets/135715545/da0e755a-fab9-485f-be70-27c1399e527f">
![Screenshot 2024-04-01 at 11 41 54 AM (2)](https://github.com/stuart-lab/signac/assets/135715545/43e039cc-3e5f-41d7-a5b4-7e66771b9cc8)

**Comment by timoast** [comment]
Great! Glad you were able to solve it
