### ISSUE TITLE
Error with install signac 

### ISSUE THREAD

**Issue by emanuelavilla** [stuart-lab/signac#1670]
Hello!

I was analysing my single-cell ATAC data and ran FindMotifs. I got an error, to which I found a solution in another issue ([here](https://github.com/stuart-lab/signac/issues/549)) and tried to install it from the seurat5 branch as suggested. However, I got an error:

![Screenshot 2024-04-02 alle 13 43 07](https://github.com/stuart-lab/signac/assets/85672107/d968fdd7-941f-4255-9a98-94def5544e60)

**Comment by timoast** [comment]
Hi @emanuelavilla, the seurat5 branch has been merged into the main release of Signac. This branch no longer exists (and there's no longer any need to install from that branch since it's merged). You can view the active branches here: https://github.com/stuart-lab/signac/branches
