### ISSUE TITLE
AddChromatinModule function creates NA values in some cells

### ISSUE THREAD

**Issue by Ryuichi30** [stuart-lab/signac#1680]
Hi,  I have performed AddChromatinModule function to add chromatin accessibility variation in genomic regions with some transcription factor binding to metadata. All3 <- AddChromatinModule(All3, features=dfdf, genome=BSgenome.Mmusculus.UCSC.mm10, assay = NULL, verbose = TRUE)  Then, I noticed that some cells have NA values in the metadata. Does AddChromatinModule function sometimes create NA values? If so, please let me know why they create NA values.  

Thanks, 
Ryuichi

**Comment by timoast** [comment]
If the number of input regions is too small chromVAR seems to return NA. The `AddChromatinModule()` function is a wrapper for chromVAR, and computes the chromVAR deviations for those peaks in your dataset. The reason why small number of input peaks can produce NA values is a question for the chromVAR developers: https://github.com/GreenleafLab/chromVAR
