### ISSUE TITLE
Error in ClosestFeature function

### ISSUE THREAD

**Issue by emanuelavilla** [stuart-lab/signac#1681]
I am running this code 

ATAC.merged.cf <- ClosestFeature(ATAC.merged, regions = rownames(ATAC.merged.DARs)) ,

where ATAC.merged is my object and ATAC.merged.DARs the result of FindAllMArkers and looks like 

![Screenshot 2024-04-09 alle 11 43 34](https://github.com/stuart-lab/signac/assets/85672107/7fd64ffd-74ac-4ca3-b823-27f1e26560f3)

However, it returned this error I cannot understand

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'seqlevels': unable to find an inherited method for function ‘seqinfo’ for signature ‘"NULL"’

**Comment by timoast** [comment]
Can you show the output of `Annotation(ATAC.merged)`?

**Comment by emanuelavilla** [comment]
I checked and it was NULL. So I added the gene annotation to the merged object and now everything works.
Thanks
