### ISSUE TITLE
rror in LinkPeaks

### ISSUE THREAD

**Issue by shabs24** [stuart-lab/signac#1698]
Hi,

I am trying to generate coverage plots for some of the genes that are expressed in my data. It works for other genes but not for these 3 genes and gives me an error 

Testing 3 genes and 75234 peaks
Error in LinkPeaks(object = WT, peak.assay = "ATAC", expression.assay = "SCT",  : 
  Could not find gene coordinates for requested genes

I can see the peaks in the promoter region in one of the genes and in the distal region in other gene in the annotation files.

Is it  possible to plot the coverage around a gene even if it is not defined as  peak.

This is the code I am using
WT <- LinkPeaks(
        object = WT,
        peak.assay = "ATAC",
        expression.assay = "SCT",
        genes.use = genes
    )

Any suggestions?

**Comment by timoast** [comment]
The error message suggests that the genes you are requesting are not present in the gene annotations stored in the object.

> Is it possible to plot the coverage around a gene even if it is not defined as peak.

Yes, a coverage plot can be created for any region of the genome

**Comment by shabs24** [comment]
> The error message suggests that the genes you are requesting are not present in the gene annotations stored in the object.
> 
> > Is it possible to plot the coverage around a gene even if it is not defined as peak.
> 
> Yes, a coverage plot can be created for any region of the genome

Thanks for your help! I was able to resolve by adding  lncRNA in my annotations while importing the genomic ranges from EnsDb.
