### ISSUE TITLE
result <- ImmuCellAI_new( expr_data_log2, microarray,1,1) Error in `rownames<-`(`*tmp*`, value = colnames(countData)) :    attempt to set 'rownames' on an object with no dimensions Called from: `rownames<-`(`*tmp*`, value = colnames(countData))

### ISSUE THREAD

**Issue by elbakrifz** [stuart-lab/signac#1704]
I am using a normalize data with package affy to have log2 format data for being input to immucellAI, but I get this error message, result <- ImmuCellAI_new( expr_data_log2, microarray,1,1)
Error in `rownames<-`(`*tmp*`, value = colnames(countData)) : 
  attempt to set 'rownames' on an object with no dimensions
Called from: `rownames<-`(`*tmp*`, value = colnames(countData))

**Comment by timoast** [comment]
Hi, I'm not sure what package this function is from but it's not part of Signac. Please open an issue in the repository for the package you're using.
