### ISSUE TITLE
Error with seqlevelsStyle(annotations) <- "UCSC" command

### ISSUE THREAD

**Issue by sandrews02** [stuart-lab/signac#1707]
I am trying to change the seqlevelsStyle to UCSC as I load in my ATAC data. However, I get the following error message:

Here is the code from my project specifically:
grange.counts.nsi1 <- StringToGRanges(rownames(nsi1.atac.counts), sep = c(":", "-"))
grange.use.nsi1 <- seqnames(grange.counts.nsi1) %in% standardChromosomes(grange.counts.nsi1)
nsi1.atac.counts <- nsi1.atac.counts[as.vector(grange.use.nsi1), ]
annotations.nsi1 <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotations.nsi1) <- "UCSC"

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'grepl': object 'doc' not found

I have run this code successfully before, but after an update to a few packages, it no longer runs succesfully. Is there a way to circumvent this error?

**Comment by timoast** [comment]
You can run this instead:

```
seqlevels(annotations.nsi1) <- paste0('chr', seqlevels(annotations.nsi1))
```
