### ISSUE TITLE
Generate .tbi file from fragments.tsv.gz

### ISSUE THREAD

**Issue by wz0527** [stuart-lab/signac#1708]
Hi,

I have seen the method that generates .tbi index using Linux command, as mentioned in issue #242

But currently, I don't have access to install tabix on our research server.

I was wondering if there is any R method to generate .tbi file from relevant fragment.tsv.gz file.

Thanks!

**Comment by timoast** [comment]
You can use the `indexTabix()` function from Rsamtools: https://rdrr.io/bioc/Rsamtools/man/indexTabix.html
