### ISSUE TITLE
The normalized signal is zero in CoveragePlot after subset

### ISSUE THREAD

**Issue by ZhengJIN94** [stuart-lab/signac#1711]
Hi, 

I tried to use "subset" function to select several clusters to downstream analysis.
**However, after "subset", the CoveragePlot seems not correct.** 
**What is the correct operation after subset function? I didn't find related tutorial in the website.**

Thank you so much if anyone can answer me!

Here is my code to subset

`obj_sub <- subset(obj_harmony, idents = c(0, 2, 3, 4, 10, 11, 13, 14))`

Here is my code and plot result

Before:
`CoveragePlot(object = obj_harmony, group.by = 'seurat_clusters', region = "Itgam", window = 20, annotation = TRUE)`

<img width="841" alt="image" src="https://github.com/stuart-lab/signac/assets/38369581/f7349e88-a1e7-49df-bed3-0dcd439188b3">

After:
`CoveragePlot(object = obj_tumor, group.by = 'seurat_clusters', region = "Gypa", window = 20, annotation = TRUE) `

<img width="837" alt="image" src="https://github.com/stuart-lab/signac/assets/38369581/6c990ac7-abb8-41a1-97a8-90c6fd59d8c8">

**Comment by timoast** [comment]
Hi @ZhengJIN94, I wasn't able to reproduce this issue. Can you include your full code and output of `sessionInfo()`?

**Comment by timoast** [comment]
Closing this as I haven't heard back and can't reproduce it, please reopen if you are still having problems and can provide the info requested above
