### ISSUE TITLE
CreatefragmentObject empty

### ISSUE THREAD

**Issue by yamihn** [stuart-lab/signac#1714]
Hello people, I have 4 fragment file in tsv.gz indexed. 
I want to create a fragment object for each of them.
When I do:
fragments_obj <- CreateFragmentObject(
  path = "./data/fragment.tsv.gz"
)
The fragmentobject Is empty..
Why? I want to use all the cells of fragment object.

**Comment by timoast** [comment]
Please see the documentation for CreateFragmentObject: https://stuartlab.org/signac/reference/createfragmentobject

The `cells` parameter determines what cells are expected to be in the fragment object

**Comment by yamihn** [comment]
Sorry, I already read the documentario, but if I left NULL in cells parameters, i expect that all the cells in the fragment  file are considered, right? In my case, zero cells have been count
