### ISSUE TITLE
gene not found in biotypes for GeneActivities()

### ISSUE THREAD

**Issue by cristanchoa** [stuart-lab/signac#1726]
Hi, Thanks for the great program!

As mentioned in https://github.com/stuart-lab/signac/discussions/1132, when I run gene activities some of my genes of interest are missing. When I look at coverage plot, these regions clearly have reads, so it seems like it must not be annotated in the biotypes as a gene. I have used "NULL", "protein_coding", and "processed_transcript".  What is the basis for the database Signac is using?  Is there a way to use an alternative biotypes database? 

Of note, this is a multiomic database and the RNA for all these genes is found. 

Ana

**Comment by timoast** [comment]
Hi Ana, the gene information used by `GeneActivity()` comes from the gene annotations that you add to the object. You can check in those annotations whether your gene is present and what biotype it has, for example:

```r
gene <- "CD8A"  # for example
annotations <- Annotation(object)
annotations[annotations$gene_name == gene, ]
```

**Comment by cristanchoa** [comment]
Thanks, Tim! 

I figured it out and leaving the answer here in case it causes others to have consternation. 

The gene in question was in the annotation, but what I did realize is that the size of the gene was bigger than the default 5E^5. For anyone studying brain, since many genes are quite large, consider changing "max.width" to NULL.
