### ISSUE TITLE
Multiome object on new machine, CoveragePlot Error: TabixFile: Fragment file is not indexed

### ISSUE THREAD

**Issue by NathanKochhar** [stuart-lab/signac#1730]
An error that I came across and found a work around for is “Error: TabixFile: Fragment file is not indexed.”, which arose from calling CoveragePlot when using a seurat multiome object that was created on one machine and loaded in on another. The solution is to also move the fragment files to the new machine and change the fragments path within the ATAC assay of the seurat object.
```r
obj@assays[["ATAC"]]@fragments[[1]]@path <- "new/frag/path"
```
I hope this helps anyone that came across this issue!

**Comment by timoast** [comment]
I recommend to use the `UpdatePath()` function which will verify that the fragment file is the same as was originally used when constructing the object, see example here: https://stuartlab.org/signac/articles/data_structures#changing-the-fragment-file-path-in-an-existing-fragment-object
