### ISSUE TITLE
Question for interpreting motif analysis result 

### ISSUE THREAD

**Issue by dbswls0322** [stuart-lab/signac#1732]
Dear Signac developer.
 I'm one of signac users.

 First of all, I deeply appreciate your contribution for this package.
 I just have a simple question for the motif analysis result.
 
 As you can see on your website. https://stuartlab.org/signac/articles/motif_vignette
![image](https://github.com/stuart-lab/signac/assets/125324934/13d51fcc-67fd-49e1-b8bc-f2bf8e259aee)

 We obtained this document file after running FindMotifs function.
 I just wonder what fold.enrichment means.

 Is it just A group's motif enrichment/ B group's enrichment? or log2fold change of enrichment?
 Can you please make it sure?

 Best Regards.

**Comment by timoast** [comment]
It is the fold enrichment of the motif over the background set of peaks (percentage of query peaks with the motif divided by percentage of background peaks with the motif)

**Comment by dbswls0322** [comment]
Thank you so much for your clear answer.
 I got more understanding about your tool now!

 Have a good day :)
