### ISSUE TITLE
convert signac object to archR

### ISSUE THREAD

**Issue by Byronxy** [stuart-lab/signac#1733]
Dear signac developers,
 Thanks for developing such a good tool. I'm currently using signac to do the preprocessing analysis of my scATAC-seq data and I hope to also use some tools in archR for downstream analysis. Is it possible for a qucik conversion between these two objects. I found others have developed a tool convert archR to signac (https://github.com/swaruplabUCI/ArchRtoSignac). I'm wondering if there is a tool that can convert signac to archR. Thanks

**Comment by timoast** [comment]
Please see https://github.com/stuart-lab/signac/issues/633

**Comment by MugenQin** [comment]
> Dear signac developers, Thanks for developing such a good tool. I'm currently using signac to do the preprocessing analysis of my scATAC-seq data and I hope to also use some tools in archR for downstream analysis. Is it possible for a qucik conversion between these two objects. I found others have developed a tool convert archR to signac (https://github.com/swaruplabUCI/ArchRtoSignac). I'm wondering if there is a tool that can convert signac to archR. Thanks

Hi, I also want to convert my Signac object to ArchR object. Did you solve that problem?
