### ISSUE TITLE
RunSLSI error

### ISSUE THREAD

**Issue by myylee** [stuart-lab/signac#1747]
Hi Signac team, 

Thanks for the great package. 

I have a large multiome dataset and I want to annotate a query snATAC-seq dataset with the multiome reference. Thus, I'm running the line below.

reference = RunSLSI(reference, assay = 'ATAC', graph = 'wsnn6Run2', n=30)

However, it crushes with the error shown below: 
<img width="1252" alt="Screen Shot 2024-07-12 at 2 30 05 PM" src="https://github.com/user-attachments/assets/7031e738-238b-4296-91e1-908b3f7b6dd7">

For the multiome dataset, there are 117122 cells, so I believe the error happened when trying to build a cell-cell similarity kernel of 117122 x 117122. 

Any recommendations on how to solve this? 

On the other hand, I also ran RunSPCA with the same graph, trying to learn a supervised projection to annotated scRNA-seq data and that step succeeded. Why did this work but not RunSLSI?

Any help is greatly appreciated!  

Michelle Lee

**Comment by timoast** [comment]
Hi, this function is part of Seurat, please open an issue there: https://github.com/satijalab/seurat
