### ISSUE TITLE
Motif "positions" slot is NULL

### ISSUE THREAD

**Issue by YaoyJiang** [stuart-lab/signac#1751]
Since I am using a reference genome of a non-model organism, I did not use the AddMotifs function because it throws an error due to unmatched features: "No features in common between the ChromatinAssay and Motif objects." Therefore, I separated this process into individual steps.

First, I created a motif matrix using the CreateMotifMatrix function. Then, I modified the row names of the motif matrix by replacing "_" with "-" in the chromosome names (make NW_024429180.1-57127-58173 to NW-024429180.1-57127-58173 ).
After making these changes, I used the CreateMotifObject and SetAssayData functions, which allowed me to successfully add the "motif" slot.

However, the issue I am facing now is that the "positions" slot is NULL，I wonder if there is a way to know the exact motif position and add it to the "positions" slot

**below is the code I used:**

DefaultAssay(combined_AM) <- "ATAC"
pfm_set <- getMatrixSet(
  x = JASPAR2020,
  opts = list(collection = "CORE",
              tax_group = 'vertebrates',
              all_versions = FALSE)
)
motif.matrix <- CreateMotifMatrix(features = granges(combined_AM),
                                  pwm = pfm_set,
                                  genome = bcm,#bcm <- Bsgenome.BCM.Maur2.0
                                  use.counts = FALSE)

motif_features <- rownames(motif.matrix)
new_motif_features <- gsub("_", "-", motif_features)
rownames(motif.matrix) <- new_motif_features

motif.object <- CreateMotifObject(data = motif.matrix,
                                  pwm = pfm_set)

combined_AM <- SetAssayData(combined_AM,
                            assay = 'ATAC',
                            slot = 'motifs',
                            new.data = motif.object)

**Comment by timoast** [comment]
To get motif positions you can run something like this:

```r
motif.positions <- motifmatchr::matchMotifs(pwms = pfm, subject = object, out = "positions", genome = genome)
```

Positions will be `NULL` if you don't add it to the object, so this is expected behaviour rather than a bug

**Comment by YaoyJiang** [comment]
> To get motif positions you can run something like this:
> 
> ```r
> motif.positions <- motifmatchr::matchMotifs(pwms = pfm, subject = object, out = "positions", genome = genome)
> ```
> 
> Positions will be `NULL` if you don't add it to the object, so this is expected behaviour rather than a bug

Thanks a lot for your reply! However I met new error:

`motif.positions <- motifmatchr::matchMotifs(pwms = pfm_set,
                                            subject = combined_AM,
                                            out = "positions",
                                            genome = Bsgenome.BCM.Maur2.0)`
here is the error:
`Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘matchMotifs’ for signature ‘"PWMatrixList", "Seurat"’`

And I check `class(combined_AM[["ATAC"]])`
It was a siganc ChromatinAssay:

`[1] "ChromatinAssay"
attr(,"package")
[1] "Signac"`

Appreciate your help!
