### ISSUE TITLE
An error about "RunChromVAR"

### ISSUE THREAD

**Issue by ZengMuo** [stuart-lab/signac#1758]
Hi, Timoast.
I have successfully run the "Addmotifs" step, but when I allow "RunChromVAR", it shows an error. The error is as follows:

pbmc <- RunChromVAR(
  object = pbmc,
  genome = BSgenome.Sscrofa.UCSC.susScr11
)
Computing GC bias per region
Selecting background regions
Computing deviations from background
OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 128: 资源暂时不可用
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 8253326 max
OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 128: 资源暂时不可用
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 8253326 max
OpenBLAS blas_thread_init: pthread_create failed for thread 48 of 128: 资源暂时不可用
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 8253326 max
OpenBLAS blas_thread_init: pthread_create failed for thread 49 of 128: 资源暂时不可用
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 8253326 max
......

**Comment by timoast** [comment]
This is an issue with chromVAR, the `RunChromVAR` function in Signac is just a convenience function to run chromVAR on the Seurat object. Please open an issue in the chromVAR repo instead: https://github.com/GreenleafLab/chromVAR

**Comment by ZengMuo** [comment]
Hi Tim,

I have resolved the issue. Thank you for your assistance.

Best regards
Mu
