### ISSUE TITLE
Significant Discrepancy in Peak Counts Between Cell Ranger ATAC and Signac Peak Calling

### ISSUE THREAD

**Issue by mano2991** [stuart-lab/signac#1760]
I am currently analyzing single-cell ATAC-seq data to compare two samples: Injured and Treated. I used Cell Ranger ATAC for initial processing and peak calling, and it identified approximately 60,000 peaks in the Treated sample and 58,000 peaks in the Injured sample. However, when I attempted to call peaks again using Signac, I encountered a significant reduction in the number of peaks:

1. Treated Sample: Reduced to 4,000 unique peaks
2. Injured Sample: Reduced to 55,000 unique peaks
3. Common Peaks: 43,000

Additionally, I noticed that the peak sizes appeared to be smaller when visualized using CoveragePlot in Signac.

My Questions:
Why is there such a drastic reduction in the number of peaks when recalling them in Signac, especially in the Treated sample? I wouldn't expect such a large difference compared to the peaks called by Cell Ranger ATAC.

Why do the peak sizes appear reduced in Signac's CoveragePlot visualization? Is this a known issue, or might I be doing something wrong during the peak-calling process in Signac?

Should I rely on the peaks called by Cell Ranger ATAC for my comparison, or is there a specific reason to recall peaks in Signac when comparing these two samples?

Any insights or suggestions would be greatly appreciated, as I'm quite confused by these discrepancies. Thank you in advance for your help!

```
peaks_calling_Macs2 <- CallPeaks(
  object = data,
  group.by = "dataset",
  macs2.path = "~/miniconda/bin/macs2")
```

![image](https://github.com/user-attachments/assets/73b378a8-b9dc-443e-8014-e56491b5dcb2)

**Comment by timoast** [comment]
These are different peak calling methods so it's expected that there are differences. The `CallPeaks` function runs MACS2, so if you have specific questions about how the MACS2 peak calling works please direct your questions to the MACS2 authors.

If the cellranger peaks are working well for your analysis then my suggestion would be to continue using those
