### ISSUE TITLE
how to do monocle3 by standard 10x output files

### ISSUE THREAD

**Issue by GaF123** [stuart-lab/signac#1764]
Thank you so much for your excellent package!

I tried to use my own 10x cellranger output files to do monocle3 ananlysis. But found that the tutorial doesn't work with them. Could you please show how to do it with standard 10x cellranger files?

Thank you so much!

**Comment by timoast** [comment]
The required inputs are the same: a counts matrix and a fragment file. This is provided by the 10x cellranger pipeline. Please check some of the other vignettes for example code showing how to create a Seurat object from the 10x cellranger files.
