### ISSUE TITLE
Seqinfo object 

### ISSUE THREAD

**Issue by Guliariel** [stuart-lab/signac#1765]
Hello,

Since my environment does not let me run commands with big files/ lots of memory I am using interactive mode to perform different analysis.
Unfortunately when I am working on this mode (it is like an offline mode) I am not able to run this command:
chrom.assay <- CreateChromatinAssay(counts = counts.ls[[experim]],
fragments = fragment.ls[[experim]],
genome = genome,
min.cells = min_cell,
min.features = min_feat)

The error msg I receive:  Error in download.file(url, destfile, quiet = TRUE) :
  cannot open URL 'https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz'

When I run the script regularly (not on the interactive mode) it works .

I would very much appreciate your help in this regard
Thank you very much,
Gal

```r
# insert reproducible example here
```

**Comment by timoast** [comment]
If you are providing the name of a genome to use in the `genome` parameter, this requires an internet connection to get the information from UCSC. If you don't have an internet connection, you can either leave the `genome` parameter as `NULL` or provide a `Seqinfo` object with the seqinfo for your genome
