### ISSUE TITLE
Unable to find 'nCount_peaks' in Signac data

### ISSUE THREAD

**Issue by ptk1601** [stuart-lab/signac#1772]
Hello!

Major thanks for making such an amazing R package. I am trying to find significant motifs in my Signac data. Unfortunately, I cannot find the 'nCount_peaks' variable in my data to generate the da_peaks object. Rather, all I see is nCount_RNA and nCount_ATAC. Is there something I missed while integrating my multiome data? Would love to see if I can find any solutions!

**Comment by timoast** [comment]
Hi, can you show the code you're running?

**Comment by ptk1601** [comment]
Apologies for the wall of code, but this is the code I used to generate the ATAC-seq object, and please let me know if you need anything else!

stat3ff_peaks <- read.table(
  file = "/Users/kimpt/Library/CloudStorage/Box-Box/Single cell gene matrix files_CR7.1.0/Mice Single cell/STAT3 project/Multiome/ATAC and GEX combined/Stat3_ff_R/atac_peaks.bed",
  col.names = c("chr", "start", "end")
)

k14creERTstat3ff_peaks <- read.table(
  file = "/Users/kimpt/Library/CloudStorage/Box-Box/Single cell gene matrix files_CR7.1.0/Mice Single cell/STAT3 project/Multiome/ATAC and GEX combined/Discuss/K14CreERT_Stat3ff_2/atac_peaks.bed",
  col.names = c("chr", "start", "end")
)

stat3ff_peaks <- makeGRangesFromDataFrame(stat3ff_peaks)
k14creERTstat3ff_peaks <- makeGRangesFromDataFrame(k14creERTstat3ff_peaks)

combined.peaks <- reduce(x = c(stat3ff_peaks, k14creERTstat3ff_peaks))

# Filter out bad peaks based on length
peakwidths <- width(combined.peaks)
combined.peaks <- combined.peaks[peakwidths  < 10000 & peakwidths > 20]
combined.peaks

# Fragment input

stat3ff_fragpath <- "//Users/kimpt/Library/CloudStorage/Box-Box/Single cell gene matrix files_CR7.1.0/Mice Single cell/STAT3 project/Multiome/ATAC and GEX combined/Stat3_ff_R/atac_fragments.tsv.gz"
k14creERTstat3ff_fragpath <- "/Users/kimpt/Library/CloudStorage/Box-Box/Single cell gene matrix files_CR7.1.0/Mice Single cell/STAT3 project/Multiome/ATAC and GEX combined/Discuss/K14CreERT_Stat3ff_2/atac_fragments.tsv.gz"
stat3ff_fragcounts <- CountFragments(fragments = stat3ff_fragpath)
k14creERTstat3ff_fragcounts <- CountFragments(fragments = k14creERTstat3ff_fragpath)

stat3ff_frags <- CreateFragmentObject(path = stat3ff_fragpath, cells = stat3ff_cells)
k14creERTstat3ff_frags <- CreateFragmentObject(path = k14creERTstat3ff_fragpath, cells = k14creERTstat3ff_cells)

# FeatureMatrix generation

stat3ff.counts <- FeatureMatrix(
  fragments = stat3ff_frags,
  features = combined.peaks,
  cells = stat3ff_cells
)
k14creERTstat3ff.counts <- FeatureMatrix(
  fragments = k14creERTstat3ff_frags,
  features = combined.peaks,
  cells = k14creERTstat3ff_cells
)

# Retrieving gene annotations for mm10 (mouse genome)

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("biovizBase")
BiocManager::install("EnsDb.Mmusculus.v79")

library(EnsDb.Mmusculus.v79)

annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- 'mm10'

# Chromatin assay and Seurat object

stat3ff_assay <- CreateChromatinAssay(stat3ff.counts, fragments = stat3ff_frags, genome = 'mm10', annotation = annotations)
stat3ff_object <- CreateSeuratObject(stat3ff_assay, assay = "ATAC", project = "stat3ff")
k14creERTstat3ff_assay <- CreateChromatinAssay(k14creERTstat3ff.counts, fragments = k14creERTstat3ff_frags, genome = 'mm10', annotation = annotations)
k14creERTstat3ff_object <- CreateSeuratObject(k14creERTstat3ff_assay, assay = "ATAC", project = "k14creERTstat3ff")

# Merging the ATAC objects

stat3ff_object <- RenameCells(stat3ff_object, add.cell.id = "stat3ff")
k14creERTstat3ff_object <- RenameCells(k14creERTstat3ff_object, add.cell.id = "k14creERTstat3ff")

ATAC_merged <- merge(
  x = stat3ff_object,
  y = list(k14creERTstat3ff_object)
)

DefaultAssay(ATAC_merged) <- "ATAC"
ATAC_merged <- RunTFIDF(ATAC_merged)
ATAC_merged <- FindTopFeatures(ATAC_merged, min.cutoff = 'q0')
ATAC_merged <- RunSVD(ATAC_merged)
ATAC_merged <- RunUMAP(ATAC_merged, reduction = 'lsi', dims = 1:50, reduction.name = "umap.atac", reduction.key = "atacUMAP_")

ATAC_merged.list <- SplitObject(ATAC_merged, split.by = "orig.ident")

p5 <- DimPlot(ATAC_merged, reduction = "umap.atac",  label = TRUE, label.size = 2.5, repel = TRUE) + ggtitle("ATAC")


integration.anchors <- FindIntegrationAnchors(
  object.list = ATAC_merged.list,
  reduction = "rlsi",
  dims = 1:30
)

ATAC_integrated <- IntegrateEmbeddings(
  anchorset = integration.anchors,
  reductions = ATAC_merged[["lsi"]],
   new.reduction.name = "integrated_lsi",
  dims.to.integrate = 1:30)


ATAC_integrated@active.assay <- "ATAC"
ATAC_integrated@active.assay <- "integrated"

ATAC_integrated <- FindNeighbors(ATAC_integrated, reduction = "integrated_lsi", dims = 1:15)
ATAC_integrated <- FindClusters(ATAC_integrated, resolution = 0.25, cluster.name = "lsi_clusters")

ATAC_integrated <- RunUMAP(RNA_integrated, umap.method = "uwot", reduction = "integrated_lsi", dims = 1:15)

**Comment by timoast** [comment]
it looks like you named your assay "ATAC" rather than "peaks"

the nCount information is added for each assay, and named according to the assay name. In your case the information will be stored as nCount_ATAC
