### ISSUE TITLE
Issue Integrating two 10x multimodal datasets

### ISSUE THREAD

**Issue by sky5198** [stuart-lab/signac#1779]
Hello, I am having trouble integrating two multimodal datasets. For both datasets, RNA and ATAC-sequencing was performed in the same cell. 

I ran the code below after I followed the https://stuartlab.org/signac/articles/pbmc_multiomic for each dataset:
multimodal.dataset1 <- FindMultiModalNeighbors(multimodal.dataset1, reduction.list = list("pca", "lsi"),
                                        dims.list = list(1:50, 2:50)) #contains RNA and ATAC sequencing for dataset1

multimodal.dataset2 <- FindMultiModalNeighbors(multimodal.dataset2, reduction.list = list("pca", "lsi"),
                                          dims.list = list(1:50, 2:50)) #contains RNA and ATAC sequencing for dataset2

multimodal.dataset1 <- RunUMAP(multimodal.dataset1, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
multimodal.dataset1 <- FindClusters(multimodal.dataset1, graph.name = "wsnn", algorithm = 3, verbose = FALSE)

multimodal.dataset2 <- RunUMAP(multimodal.dataset2, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
multimodal.dataset2 <- FindClusters(multimodal.dataset2, graph.name = "wsnn", algorithm = 3, verbose = FALSE)

I then want to combine multimodal.dataset1 and multimodal.dataset2. Is there a way to do this?

**Comment by timoast** [comment]
Please see the merge vignette: https://stuartlab.org/signac/articles/merging
