### ISSUE TITLE
No Cluster ID's present when making UMAP for Joint RNA and ATAC analysis: 10x multiomic tutorial

### ISSUE THREAD

**Issue by zgb963** [stuart-lab/signac#1806]
Hello,

I've been following the Joint RNA and ATAC analysis: 10x multiomic tutorial with my own snRNAseq + snATACseq data. I've completed all steps until the Joint UMAP visualization step. I skipped the annotating cell types step because I don't have annotations for this data yet, which is from the Primary Visual Cortex (V1) from Macaca fascicularis. I'm trying to create a UMAP for my 7 samples, but I'm not sure why it isn't generating a normal UMAP with cluster id's for each cluster. Below is my code for sample 1.

```
# build a joint neighbor graph using both assays
liftoff_1_MI5_V1_SO <- FindMultiModalNeighbors(
  object = liftoff_1_MI5_V1_SO,
  reduction.list = list("pca", "lsi"), 
  dims.list = list(1:50, 2:40),
  modality.weight.name = "RNA.weight",
  verbose = TRUE
)

# build a joint UMAP visualization
liftoff_1_MI5_V1_SO <- RunUMAP(
  object = liftoff_1_MI5_V1_SO,
  nn.name = "weighted.nn",
  assay = "RNA",
  verbose = TRUE
)

DimPlot(liftoff_1_MI5_V1_SO, label = TRUE, repel = TRUE, reduction = "umap") + NoLegend()

# not sure why everything is one color? 
```
<img width="1700" alt="Screenshot 2024-10-18 at 6 14 15 PM" src="https://github.com/user-attachments/assets/e8b6cd4d-b2ba-4b9e-a9a7-0c0aae873243">

It seems to color all the cells by `orig.ident` which is not what I was expecting. I then tried the standard Seurat steps from their Guided Clustering Tutorial to generate the UMAP, but I was getting errors.

```
liftoff_1_MI5_V1_SO <- FindNeighbors(liftoff_1_MI5_V1_SO, dims = 1:30, return.neighbor = TRUE)
# Computing nearest neighbor graph
# Computing SNN

liftoff_1_MI5_V1_SO <- FindClusters(liftoff_1_MI5_V1_SO, resolution = c(0.4, 0.5, 0.6, 0.7, 0.8))
# Error in FindClusters.Seurat(liftoff_1_MI5_V1_SO, resolution = c(0.4,  : 
#   Provided graph.name not present in Seurat object

liftoff_1_MI5_V1_SO <- RunUMAP(liftoff_1_MI5_V1_SO, dims = 1:30)
DimPlot(liftoff_1_MI5_V1_SO, reduction = "umap", label = TRUE)
```

I'm not sure why I'm getting this error? Do I need to run the Seurat steps to generate the UMAP for each sample? Do I need to run the standard Seurat Find Neighbors, Find Clusters, RunUMAP, & DimPlot separately for the RNA assay and the ATAC assay before making a joint UMAP? How can I calculate the resolution for the joint (snRNAseq + snATACseq) UMAP? How can I make the UMAP so that each cluster has a cluster ID and each cluster has a different color like normal?

**Comment by timoast** [comment]
You need to run the `FindClusters()` function if you want to cluster your dataset, please see the documentation on the Seurat website: https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis#wnn-analysis-of-10x-multiome-rna-atac

**Comment by zgb963** [comment]
@timoast as seen above, I already ran the `FindClusters()` function using the Seurat tutorial but I keep getting the following error.

```
liftoff_1_MI5_V1_SO <- FindClusters(liftoff_1_MI5_V1_SO, resolution = c(0.4, 0.5, 0.6, 0.7, 0.8))
# Error in FindClusters.Seurat(liftoff_1_MI5_V1_SO, resolution = c(0.4,  : 
#   Provided graph.name not present in Seurat object
```
I'm not sure why I'm getting this error? Do I need to run the Seurat steps to generate the UMAP for each sample? Do I need to run the standard Seurat Find Neighbors, Find Clusters, RunUMAP, & DimPlot separately for the RNA assay and the ATAC assay before making a joint UMAP? How can I calculate the resolution for the joint (snRNAseq + snATACseq) UMAP? How can I make the UMAP so that each cluster has a cluster ID and each cluster has a different color like normal?
