### ISSUE TITLE
Motif footprinting for my data

### ISSUE THREAD

**Issue by dp-sun** [stuart-lab/signac#1808]
Now I am analyzing the footprints of some TFs, however, I got the error of 'Error in stop_if_wrong_length("'seqnames'", ans_len) : 
  'seqnames' must have the length of the object to construct (1) or length 1'

# Get a list of motif position frequency matrices from the JASPAR database
pwm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(collection = "CORE", tax_group = 'insects', all_versions = FALSE)
)

# add motif information
obj.atac2 <- AddMotifs(
  object = obj.atac2,
  genome = FBdm6,
  pfm = pwm
)

# gather the footprinting information for sets of motifs
obj.atac2 <- Footprint(
  object = obj.atac2,
  motif.name = c("Pdp1"),
  genome = FBdm6,
  groupp.by='predicted.id',
  in.peaks = 'TRUE'
)

In this analysis, I used my built genome GRange object, there is no problem with other functions like "RunChromVAR" or "AddMotifs", bu t got the error from "Footprint".

Just let me know if you need other information. Thanks!

**Comment by timoast** [comment]
You have two typos: `groupp.by='predicted.id'` -> `group.by='predicted.id'` and `in.peaks = 'TRUE'` -> `in.peaks = TRUE`

Can you fix these, and also include your full code and session info?

**Comment by timoast** [comment]
Closing this as I haven't heard back, please reopen if you still have issues
