### ISSUE TITLE
Coverage Plot: Move axis and gene annotations above tracks

### ISSUE THREAD

**Issue by harrsha4** [stuart-lab/signac#1811]
Hello, 
     I was wondering if there was an option (CoveragePlot function) to rearrange the coordinate information and genes (normally at the bottom) to the top as in this image: 

![image](https://github.com/user-attachments/assets/3635cf3f-4fb6-4d5d-85ce-518583be4adf)

Thank you!

**Comment by timoast** [comment]
You can follow the documentation here: https://stuartlab.org/signac/articles/visualization#customizing-plots
