### ISSUE TITLE
custom path for fragment files

### ISSUE THREAD

**Issue by Jingyi-Wu-lab** [stuart-lab/signac#1817]
I hope to run Coverageplot with other people's Seurat object peaks assay, but it reports that:

Error: TabixFile: file(s) do not exist:
  ‘/home//Documents/atac_fragments.tsv.gz’
  ‘/home/Documents/atac_fragments.tsv.gz.tbi’

I have atac_fragment files downloaded and stored on my local computer. I wonder if I can customize the path so the coverage plot can find it.

**Comment by timoast** [comment]
Please see the documentation here: https://stuartlab.org/signac/articles/data_structures#changing-the-fragment-file-path-in-an-existing-fragment-object
