### ISSUE TITLE
FindTransferAnchors error !!

### ISSUE THREAD

**Issue by synatkeamsk** [stuart-lab/signac#1846]
Dear Developers, 

I have run script from Signac tutorial and got error when I reach the below part 

``` 
pbmc_rna <- readRDS("pbmc_10k_v3.rds")
pbmc_rna <- UpdateSeuratObject(pbmc_rna)
transfer.anchors <- FindTransferAnchors(
  reference = pbmc_rna,
  query = pbmc,
  reduction = 'cca'
)
``` 
I got the following error !! 

```
Error: No features to use in finding transfer anchors. To troubleshoot, try explicitly providing features to the features parameter and ensure that they are present in both reference and query assays. 

``` 
I tried to troubleshooted it by looking whether people have encountered the same issue, but I could not fix it. I am wondering whether you could help look and suggest some solutions. 

Kind Regards,

synat

**Comment by timoast** [comment]
My guess is that you don't have a gene activity assay in your ATAC object or it is not the default assay. For further questions related to `FindTransferAnchors`, please open an issue in Seurat as this is a Seurat function and not part of Signac
