### ISSUE TITLE
Gene activity matrix creation

### ISSUE THREAD

**Issue by zhangjl-work** [stuart-lab/signac#1850]
Hi, does the GeneActivity function, which calculates the gene activity matrix, have anything to do with the sequencing depth?
For example, the same sample was sequenced in two data sets, both with about 5000 cells, in data 1, the median high-quality fragments per cell reached 20000, and in data 2, the median high-quality fragments per cell was 7000.
Obviously, the sequencing depth of data 1 is higher, but the expression of some genes in the gene activity matrix calculated by this method shows an inverse trend, and the expression of some genes in data 1 is lower than that in data 2. Is this reasonable? I look forward to your reply.

following is my code :

# Step 1: Gene activity matrix creation
  gene.activities <- GeneActivity(seurat_obj)
  
  # Step 2: Add the gene activity matrix to the Seurat object as a new assay and normalize
  seurat_obj[['RNA']] <- CreateAssayObject(counts = gene.activities)
  seurat_obj <- NormalizeData(
    object = seurat_obj,
    assay = 'RNA',
    normalization.method = 'LogNormalize',
    scale.factor = median(seurat_obj$nCount_RNA)
  )

![tmp](https://github.com/user-attachments/assets/cf4c22b7-a0f0-4480-aa87-96b3fd29dc4f)

**Comment by timoast** [comment]
The `GeneActivity` function counts the number of fragments that overlap a set of gene annotations for each cell. This is the raw count, so it will be influenced by sequencing depth. You are also running the Seurat `NormalizeData` function here which normalizes according to the total counts for each cell.
