### ISSUE TITLE
Geneactivity without fragments

### ISSUE THREAD

**Issue by alekseybelikov** [stuart-lab/signac#1865]
Hi, I find that the current Geneactivity() function can only work for scatac-seq data with peaks and fragement information. However, plenty of current data do not provide such information, and I think it is also an important feature, mentioned by this question with no answer:
https://www.biostars.org/p/9525109/

Therefore, I think it is still necessary to keep the original seurat functin, known as
activity.matrix <- CreateGeneActivityMatrix(peak.matrix = peaks, annotation.file = "./ad paper dataset/Homo_sapiens.GRCh37.87.gtf",
seq.levels = c(1:22, "X", "Y"), upstream = 2000, verbose = TRUE)
For the current work. Or do we have any similar fuctions that can help us directly construct gene activity score matrix directly from peaks matrix? Thanks a lot.

**Comment by timoast** [comment]
Hi, the `CreateGeneActivityMatrix` function you're referring to was part of Seurat, and was never a Signac function. If you're like the function to be added back to Seurat you should raise an issue there: https://github.com/satijalab/seurat/issues

Alternatively, the code for that function is publicly available and you can of course still run it without it being in the current Seurat release.

I understand your frustration that many public datasets do not provide fragment files. This is unfortunate and hopefully will change over time.
