### ISSUE TITLE
re-upload the fragment file provided in this tutorial

### ISSUE THREAD

**Issue by sd68515** [stuart-lab/signac#1867]
https://stuartlab.org/signac/1.2.0/articles/snareseq.html
Could you please re-upload the fragment file provided in this tutorial? Both Dropbox links seem to be invalid. Thank you!

>The fragment file can be downloaded here: https://www.dropbox.com/s/se3uag0cvld4xqg/fragments.sort.bed.gz?dl=0
>The fragment file index can be downloaded here: https://www.dropbox.com/s/kvb8fiewkjz3kzf/fragments.sort.bed.gz.tbi?dl=0

**Comment by timoast** [comment]
Please check the current version of the website, you are looking at the archived version for v1.2.0:

https://stuartlab.org/signac/articles/snareseq
