### ISSUE TITLE
Help with creating a heatmap to show marker expression

### ISSUE THREAD

**Issue by jjv4001** [stuart-lab/signac#1870]
Is there a way to construct a peak marker heatmap, similar to what was generated using ArchR?
![Peak-Marker-Heatmap_1 (1)](https://github.com/user-attachments/assets/573ebf04-e61b-498f-b538-a042aaeb8936)

**Comment by timoast** [comment]
You can use the `DoHeatmap()` function in Seurat and `ScaleData` to create the z-scores
