### ISSUE TITLE
Add split.by option to CoveragePlot() and PlotFootprint()

### ISSUE THREAD

**Issue by CiaranKennedy** [stuart-lab/signac#523]
Hi there,

I'm just wondering if it would be possible to add the split.by function to CoveragePlot() and PlotFootprint() (there are probably a few others that it would be useful on, but those are the main ones I can think of off the top of my head).

I think it would be useful where users might have multiple samples, so you could have the plots set to group.by the cluster identities and then a separate plot for each sample to make comparing side-by-side a bit easier. I know you can append the name of the sample to the identity to separate them all out individually, but for example if I have a set of 4 samples each with 17 cell types it becomes a lot to look at.

Or if there are any other suggestions for how to achieve something similar I'm open to them too. 

Thanks,
Ciarán

**Comment by timoast** [comment]
This has now been added to the latest Signac version
